#!/usr/bin/env python
# Copyright 2014 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

"""This script runs unit tests of the code in the perf directory.

This script DOES NOT run benchmarks. run_benchmark does that.
"""

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), os.pardir, 'telemetry'))

from telemetry.testing import unittest_runner

import chrome_proxy_config


if __name__ == '__main__':
  sys.exit(unittest_runner.Run(chrome_proxy_config.Config(['integration_tests',
                                                           'live_tests'])))
