/*
 * Copyright 2009 The Native Client Authors. All rights reserved.
 * Use of this source code is governed by a BSD-style license that can
 * be found in the LICENSE file.
 */

/*
 * Defines ARM multiplication instructions.
 */

#include "native_client/src/trusted/validator_arm/arm_mulops.h"
#include "native_client/src/trusted/validator_arm/arm_insts.h"
#include "native_client/src/trusted/validator_arm/arm_inst_modeling.h"

/* Defines multiply operations. */
static const ModeledOpInfo kMulOps[] = {
  { "mla",
    ARM_MLA,
    kArmUndefinedAccessModeName,
    ARM_DP_RS,
    TRUE,
    "%C\t%r, %z, %y, %x",
    ARM_WORD_LENGTH,
    NULLName,
    { CONTAINS_ZERO, 0x0, 0x2, CONTAINS_ZERO, CONTAINS_ZERO, CONTAINS_ZERO,
      CONTAINS_ZERO, 0x0, 0x9 }},
  { "mla",
    ARM_MLA,
    kArmUndefinedAccessModeName,
    ARM_DP_RS,
    TRUE,
    "%Cs\t%r, %z, %y, %x",
    ARM_WORD_LENGTH,
    NULLName,
    { CONTAINS_ZERO, 0x0, 0x3, CONTAINS_ZERO, CONTAINS_ZERO, CONTAINS_ZERO,
      CONTAINS_ZERO, 0x0, 0x9 }},
  { "mul",
    ARM_MUL,
    kArmUndefinedAccessModeName,
    ARM_DP_RS,
    TRUE,
    "%C\t%r, %z, %y",
    ARM_WORD_LENGTH,
    NULLName,
    { CONTAINS_ZERO, 0x0, 0x0, CONTAINS_ZERO, ANY, CONTAINS_ZERO,
      CONTAINS_ZERO, 0x0, 0x9 }},
  { "mul",
    ARM_MUL,
    kArmUndefinedAccessModeName,
    ARM_DP_RS,
    TRUE,
    "%Cs\t%r, %z, %y",
    ARM_WORD_LENGTH,
    NULLName,
    { CONTAINS_ZERO, 0x0, 0x1, CONTAINS_ZERO, ANY, CONTAINS_ZERO,
      CONTAINS_ZERO, 0x0, 0x9 }},
  { "smla",
    ARM_SMLA_XY,
    kArmUndefinedAccessModeName,
    ARM_DP_RS,
    TRUE,
    "%M\t%r, %z, %y, %x",
    ARM_WORD_LENGTH,
    NULLName,
    { CONTAINS_ZERO, 0x0, 0x10, CONTAINS_ZERO, CONTAINS_ZERO, CONTAINS_ZERO,
      CONTAINS_ZERO, ANY, 0x8 }},
  { "smuad",
    ARM_SMUAD,
    kArmUndefinedAccessModeName,
    ARM_DP_RS,
    TRUE,
    "%C\t%r, %z, %y",
    ARM_WORD_LENGTH,
    NULLName,
    { CONTAINS_ZERO, 0x3, 0x10, CONTAINS_ZERO, 0xF, CONTAINS_ZERO,
      CONTAINS_ZERO, 0x0, 0x1 }},
  { "smuadx",
    ARM_SMUADX,
    kArmUndefinedAccessModeName,
    ARM_DP_RS,
    TRUE,
    "%C\t%r, %z, %y",
    ARM_WORD_LENGTH,
    NULLName,
    { CONTAINS_ZERO, 0x3, 0x10, CONTAINS_ZERO, 0xF, CONTAINS_ZERO,
      CONTAINS_ZERO, 0x1, 0x1 }},
  { "smlad",
    ARM_SMLAD,
    kArmUndefinedAccessModeName,
    ARM_DP_RS,
    TRUE,
    "%C\t%r, %z, %y, %x",
    ARM_WORD_LENGTH,
    NULLName,
    { CONTAINS_ZERO, 0x3, 0x10, CONTAINS_ZERO, CONTAINS_ZERO, CONTAINS_ZERO,
      CONTAINS_ZERO, 0x0, 0x1 }},
  { "smladx",
    ARM_SMLADX,
    kArmUndefinedAccessModeName,
    ARM_DP_RS,
    TRUE,
    "%C\t%r, %z, %y, %x",
    ARM_WORD_LENGTH,
    NULLName,
    { CONTAINS_ZERO, 0x3, 0x10, CONTAINS_ZERO, CONTAINS_ZERO, CONTAINS_ZERO,
      CONTAINS_ZERO, 0x1, 0x1 }},
  { "smlal",
    ARM_SMLAL,
    kArmUndefinedAccessModeName,
    ARM_DP_RS,
    TRUE,
    "%C\t%x, %r, %z, %y",
    ARM_WORD_LENGTH,
    NULLName,
    { CONTAINS_ZERO, 0x0, 0xE, CONTAINS_ZERO, CONTAINS_ZERO, CONTAINS_ZERO,
      CONTAINS_ZERO, 0x0, 0x9 }},
  { "smlal",
    ARM_SMLAL,
    kArmUndefinedAccessModeName,
    ARM_DP_RS,
    TRUE,
    "%Cs\t%x, %r, %z, %y",
    ARM_WORD_LENGTH,
    NULLName,
    { CONTAINS_ZERO, 0x0, 0xF, CONTAINS_ZERO, CONTAINS_ZERO, CONTAINS_ZERO,
      CONTAINS_ZERO, 0x0, 0x9 }},
  { "smlal",
    ARM_SMLAL_XY,
    kArmUndefinedAccessModeName,
    ARM_DP_RS,
    TRUE,
    "%M\t%x, %r, %z, %y",
    ARM_WORD_LENGTH,
    NULLName,
    { CONTAINS_ZERO, 0x0, 0x14, CONTAINS_ZERO, CONTAINS_ZERO, CONTAINS_ZERO,
      CONTAINS_ZERO, ANY, 0x8 }},
  { "smlald",
    ARM_SMLALD,
    kArmUndefinedAccessModeName,
    ARM_DP_RS,
    TRUE,
    "%C\t%x, %r, %z, %y",
    ARM_WORD_LENGTH,
    NULLName,
    { CONTAINS_ZERO, 0x3, 0x14, CONTAINS_ZERO, CONTAINS_ZERO, CONTAINS_ZERO,
      CONTAINS_ZERO, 0x0, 0x1 }},
  { "smlaldx",
    ARM_SMLALDX,
    kArmUndefinedAccessModeName,
    ARM_DP_RS,
    TRUE,
    "%C\t%x, %r, %z, %y",
    ARM_WORD_LENGTH,
    NULLName,
    { CONTAINS_ZERO, 0x3, 0x14, CONTAINS_ZERO, CONTAINS_ZERO, CONTAINS_ZERO,
      CONTAINS_ZERO, 0x1, 0x1 }},
  { "smlaw",
    ARM_SMLAWB,
    kArmUndefinedAccessModeName,
    ARM_DP_RS,
    TRUE,
    "%T\t%r, %z, %y, %x",
    ARM_WORD_LENGTH,
    NULLName,
    { CONTAINS_ZERO, 0x0, 0x12, CONTAINS_ZERO, CONTAINS_ZERO, CONTAINS_ZERO,
      CONTAINS_ZERO, 0x0, 0x8 }},
  { "smlaw",
    ARM_SMLAWT,
    kArmUndefinedAccessModeName,
    ARM_DP_RS,
    TRUE,
    "%T\t%r, %z, %y, %x",
    ARM_WORD_LENGTH,
    NULLName,
    { CONTAINS_ZERO, 0x0, 0x12, CONTAINS_ZERO, CONTAINS_ZERO, CONTAINS_ZERO,
      CONTAINS_ZERO, 0x2, 0x8 }},
  { "smusd",
    ARM_SMUSD,
    kArmUndefinedAccessModeName,
    ARM_DP_RS,
    TRUE,
    "%C\t%r, %z, %y",
    ARM_WORD_LENGTH,
    NULLName,
    { CONTAINS_ZERO, 0x3, 0x10, CONTAINS_ZERO, 0xF, CONTAINS_ZERO,
      CONTAINS_ZERO, 0x2, 0x1 }},
  { "smusdx",
    ARM_SMUSDX,
    kArmUndefinedAccessModeName,
    ARM_DP_RS,
    TRUE,
    "%C\t%r, %z, %y",
    ARM_WORD_LENGTH,
    NULLName,
    { CONTAINS_ZERO, 0x3, 0x10, CONTAINS_ZERO, 0xF, CONTAINS_ZERO,
      CONTAINS_ZERO, 0x3, 0x1 }},
  { "smlsd",
    ARM_SMLSD,
    kArmUndefinedAccessModeName,
    ARM_DP_RS,
    TRUE,
    "%C\t%r, %z, %y, %x",
    ARM_WORD_LENGTH,
    NULLName,
    { CONTAINS_ZERO, 0x3, 0x10, CONTAINS_ZERO, CONTAINS_ZERO, CONTAINS_ZERO,
      CONTAINS_ZERO, 0x2, 0x1 }},
  { "smlsdx",
    ARM_SMLSDX,
    kArmUndefinedAccessModeName,
    ARM_DP_RS,
    TRUE,
    "%C\t%r, %z, %y, %x",
    ARM_WORD_LENGTH,
    NULLName,
    { CONTAINS_ZERO, 0x3, 0x10, CONTAINS_ZERO, CONTAINS_ZERO, CONTAINS_ZERO,
      CONTAINS_ZERO, 0x3, 0x1 }},
  { "smlsld",
    ARM_SMLSLD,
    kArmUndefinedAccessModeName,
    ARM_DP_RS,
    TRUE,
    "%C\t%x, %r, %z, %y",
    ARM_WORD_LENGTH,
    NULLName,
    { CONTAINS_ZERO, 0x3, 0x14, CONTAINS_ZERO, CONTAINS_ZERO, CONTAINS_ZERO,
      CONTAINS_ZERO, 0x2, 0x1 }},
  { "smlsldx",
    ARM_SMLSLDX,
    kArmUndefinedAccessModeName,
    ARM_DP_RS,
    TRUE,
    "%C\t%x, %r, %z, %y",
    ARM_WORD_LENGTH,
    NULLName,
    { CONTAINS_ZERO, 0x3, 0x14, CONTAINS_ZERO, CONTAINS_ZERO, CONTAINS_ZERO,
      CONTAINS_ZERO, 0x3, 0x1 }},
  { "smmul",
    ARM_SMMUL,
    kArmUndefinedAccessModeName,
    ARM_DP_RS,
    TRUE,
    "%C\t%r, %z, %y",
    ARM_WORD_LENGTH,
    NULLName,
    { CONTAINS_ZERO, 0x3, 0x15, CONTAINS_ZERO, 0xF, CONTAINS_ZERO,
      CONTAINS_ZERO, 0x0, 0x1 }},
  { "smmulr",
    ARM_SMMULR,
    kArmUndefinedAccessModeName,
    ARM_DP_RS,
    TRUE,
    "%C\t%r, %z, %y",
    ARM_WORD_LENGTH,
    NULLName,
    { CONTAINS_ZERO, 0x3, 0x15, CONTAINS_ZERO, 0xF, CONTAINS_ZERO,
      CONTAINS_ZERO, 0x1, 0x1 }},
  { "smmla",
    ARM_SMMLA,
    kArmUndefinedAccessModeName,
    ARM_DP_RS,
    TRUE,
    "%C\t%r, %z, %y, %x",
    ARM_WORD_LENGTH,
    NULLName,
    { CONTAINS_ZERO, 0x3, 0x15, CONTAINS_ZERO, CONTAINS_ZERO, CONTAINS_ZERO,
      CONTAINS_ZERO, 0x0, 0x1 }},
  { "smmlar",
    ARM_SMMLAR,
    kArmUndefinedAccessModeName,
    ARM_DP_RS,
    TRUE,
    "%C\t%r, %z, %y, %x",
    ARM_WORD_LENGTH,
    NULLName,
    { CONTAINS_ZERO, 0x3, 0x15, CONTAINS_ZERO, CONTAINS_ZERO, CONTAINS_ZERO,
      CONTAINS_ZERO, 0x1, 0x1 }},
  { "smmls",
    ARM_SMMLS,
    kArmUndefinedAccessModeName,
    ARM_DP_RS,
    TRUE,
    "%C\t%r, %z, %y, %x",
    ARM_WORD_LENGTH,
    NULLName,
    { CONTAINS_ZERO, 0x3, 0x15, CONTAINS_ZERO, CONTAINS_ZERO, CONTAINS_ZERO,
      CONTAINS_ZERO, 0x2, 0x9 }},
  { "smmlsr",
    ARM_SMMLSR,
    kArmUndefinedAccessModeName,
    ARM_DP_RS,
    TRUE,
    "%C\t%r, %z, %y, %x",
    ARM_WORD_LENGTH,
    NULLName,
    { CONTAINS_ZERO, 0x3, 0x15, CONTAINS_ZERO, CONTAINS_ZERO, CONTAINS_ZERO,
      CONTAINS_ZERO, 0x3, 0x9 }},
  { "smul",
    ARM_SMUL_XY,
    kArmUndefinedAccessModeName,
    ARM_DP_RS,
    TRUE,
    "%M\t%r, %z, %y",
    ARM_WORD_LENGTH,
    NULLName,
    { CONTAINS_ZERO, 0x0, 0x16, CONTAINS_ZERO, 0x0, CONTAINS_ZERO,
      CONTAINS_ZERO, ANY, 0x8 }},
  { "smull",
    ARM_SMULL,
    kArmUndefinedAccessModeName,
    ARM_DP_RS,
    TRUE,
    "%C\t%x, %r, %z, %y",
    ARM_WORD_LENGTH,
    NULLName,
    { CONTAINS_ZERO, 0x0, 0xC, CONTAINS_ZERO, CONTAINS_ZERO, CONTAINS_ZERO,
      CONTAINS_ZERO, 0x0, 0x9 }},
  { "smull",
    ARM_SMULL,
    kArmUndefinedAccessModeName,
    ARM_DP_RS,
    TRUE,
    "%Cs\t%x, %r, %z, %y",
    ARM_WORD_LENGTH,
    NULLName,
    { CONTAINS_ZERO, 0x0, 0xD, CONTAINS_ZERO, CONTAINS_ZERO, CONTAINS_ZERO,
      CONTAINS_ZERO, 0x0, 0x9 }},
  { "smulw",
    ARM_SMULWB,
    kArmUndefinedAccessModeName,
    ARM_DP_RS,
    TRUE,
    "%T\t%r, %z, %y",
    ARM_WORD_LENGTH,
    NULLName,
    { CONTAINS_ZERO, 0x0, 0x12, CONTAINS_ZERO, 0x0, CONTAINS_ZERO,
      CONTAINS_ZERO, 0x1, 0x8 }},
  { "smulw",
    ARM_SMULWT,
    kArmUndefinedAccessModeName,
    ARM_DP_RS,
    TRUE,
    "%T\t%r, %z, %y",
    ARM_WORD_LENGTH,
    NULLName,
    { CONTAINS_ZERO, 0x0, 0x12, CONTAINS_ZERO, 0x0, CONTAINS_ZERO,
      CONTAINS_ZERO, 0x3, 0x8 }},
  { "umaal",
    ARM_UMAAL,
    kArmUndefinedAccessModeName,
    ARM_DP_RS,
    TRUE,
    "%Cxo\t%x, %r, %z, %y",
    ARM_WORD_LENGTH,
    NULLName,
    { CONTAINS_ZERO, 0x0, 0x4, CONTAINS_ZERO, CONTAINS_ZERO, CONTAINS_ZERO,
      CONTAINS_ZERO, 0x0, 0x9 }},
  { "umlal",
    ARM_UMLAL,
    kArmUndefinedAccessModeName,
    ARM_DP_RS,
    TRUE,
    "%C\t%x, %r, %z, %y",
    ARM_WORD_LENGTH,
    NULLName,
    { CONTAINS_ZERO, 0x0, 0xa, CONTAINS_ZERO, CONTAINS_ZERO, CONTAINS_ZERO,
      CONTAINS_ZERO, 0x0, 0x9 }},
  { "umlal",
    ARM_UMLAL,
    kArmUndefinedAccessModeName,
    ARM_DP_RS,
    TRUE,
    "%Cs\t%x, %r, %z, %y",
    ARM_WORD_LENGTH,
    NULLName,
    { CONTAINS_ZERO, 0x0, 0xb, CONTAINS_ZERO, CONTAINS_ZERO, CONTAINS_ZERO,
      CONTAINS_ZERO, 0x0, 0x9 }},
  { "umull",
    ARM_UMULL,
    kArmUndefinedAccessModeName,
    ARM_DP_RS,
    TRUE,
    "%C\t%x, %r, %z, %y",
    ARM_WORD_LENGTH,
    NULLName,
    { CONTAINS_ZERO, 0x0, 0x8, CONTAINS_ZERO, CONTAINS_ZERO, CONTAINS_ZERO,
      CONTAINS_ZERO, 0x0, 0x9 }},
  { "umull",
    ARM_UMULL,
    kArmUndefinedAccessModeName,
    ARM_DP_RS,
    TRUE,
    "%Cs\t%x, %r, %z, %y",
    ARM_WORD_LENGTH,
    NULLName,
    { CONTAINS_ZERO, 0x0, 0x9, CONTAINS_ZERO, CONTAINS_ZERO, CONTAINS_ZERO,
      CONTAINS_ZERO, 0x0, 0x9 }},
  { "qadd",
    ARM_QADD,
    kArmUndefinedAccessModeName,
    ARM_DP_RS,
    TRUE,
    "%C\t%x, %z, %r",
    ARM_WORD_LENGTH,
    NULLName,
    { CONTAINS_ZERO, 0x0, 0x10, ANY, ANY, ANY, ANY, 0x2, 0x1 }},
  { "qdadd",
    ARM_QDADD,
    kArmUndefinedAccessModeName,
    ARM_DP_RS,
    TRUE,
    "%C\t%x, %z, %r",
    ARM_WORD_LENGTH,
    NULLName,
    { CONTAINS_ZERO, 0x0, 0x14, ANY, ANY, ANY, ANY, 0x2, 0x1 }},
  { "qdsub",
    ARM_QDSUB,
    kArmUndefinedAccessModeName,
    ARM_DP_RS,
    TRUE,
    "%C\t%x, %z, %r",
    ARM_WORD_LENGTH,
    NULLName,
    { CONTAINS_ZERO, 0x0, 0x16, ANY, ANY, ANY, ANY, 0x2, 0x1 }},
  { "qsub",
    ARM_QSUB,
    kArmUndefinedAccessModeName,
    ARM_DP_RS,
    TRUE,
    "%C\t%x, %z, %r",
    ARM_WORD_LENGTH,
    NULLName,
    { CONTAINS_ZERO, 0x0, 0x12, ANY, ANY, ANY, ANY, 0x2, 0x1 }},
  END_OPINFO_LIST
};

void BuildArmMulopInstructions() {
  int i;
  for (i = 0; ; ++i) {
    const ModeledOpInfo* op = &(kMulOps[i]);
    if (op->inst_type == ARM_INST_TYPE_SIZE) break;
    AddInstruction(op);
  }
}
