// Copyright 2015 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Creates a DomDistiller, applies to to the content of the page, and returns
// a DomDistillerResults as a JavaScript object/dictionary.
(function(options) {
  try {
    // The generated domdistiller.js accesses the window object only explicitly
    // via the window name. This creates a new object with the normal window
    // object as its prototype and initialize the domdistiller.js with that new
    // context so that it does not change the real window object.
    function initialize(window) {
      (function () {var $gwt_version = "2.7.0";var $wnd = window;var $doc = $wnd.document;var $moduleName, $moduleBase;var $stats = $wnd.__gwtStatsEvent ? function(a) {$wnd.__gwtStatsEvent(a)} : null;var $strongName = '711A785476F58FEB32281E6B485BE87B';var aa=2147483647,ba={3:1,5:1},ca={3:1,7:1,5:1},da={3:1},ea={30:1},fa={17:1},ga={3:1,20:1},ha={3:1,15:1,11:1,18:1},_,ia,ka={};function ma(){}function na(a){function b(){}b.prototype=a||{};return new b}function h(){}function k(a,b,c){var d=ka[a],e=d instanceof Array?d[0]:null;d&&!e?_=d:(_=ka[a]=b?na(ka[b]):{},_.cM=c,_.constructor=_,!b&&(_.tM=ma));for(d=3;d<arguments.length;++d)arguments[d].prototype=_;e&&(_.cZ=e)}function oa(){}function ta(a,b){return wa(a)?a===b:xa(a)?a.eQ(b):(ya(a),a===b)}
function za(a){return wa(a)?m:xa(a)?a.cZ:ya(a)?a.cZ:Aa}function Ba(a){if(wa(a)){Ja();var b=":"+a,c=Ka[b];if(null!=c)a=c;else{c=La[b];if(null==c){var d,e,f;d=0;e=a.length;f=e-4;for(c=0;c<f;)d=a.charCodeAt(c+3)+31*(a.charCodeAt(c+2)+31*(a.charCodeAt(c+1)+31*(a.charCodeAt(c)+31*d))),d=~~d,c+=4;for(;c<e;)d*=31,f=c++,f=a.charCodeAt(f),d+=f;c=~~d}256==Ma&&(La=Ka,Ka={},Ma=0);++Ma;a=Ka[b]=c}}else a=xa(a)?a.hC():(ya(a),a.$H||(a.$H=++Na));return a}k(1,null,{},oa);_.eQ=function(a){return this===a};_.gC=function(){return this.cZ};
_.hC=function(){return this.$H||(this.$H=++Na)};_.tS=function(){var a=pb(za(this))+"@",b;b=(Ba(this)>>>0).toString(16);return a+b};_.toString=function(){return this.tS()};qb={3:1,171:1,15:1,2:1};!Array.isArray&&(Array.isArray=function(a){return"[object Array]"===Object.prototype.toString.call(a)});function xa(a){return!Array.isArray(a)&&a.tM===ma}function n(a,b){return null!=a&&(wa(a)&&!!qb[b]||a.cM&&!!a.cM[b])}function ya(a){return Array.isArray(a)&&a.tM===ma}
function wa(a){return"string"===typeof a}function q(a){return null==a?null:a}function rb(a){return~~Math.max(Math.min(a,aa),-2147483648)}var qb;function sb(a){if(null==a.n)if(a.B()){var b=a.c;b.C()?a.n="["+b.k:b.B()?a.n="["+b.w():a.n="[L"+b.w()+";";a.b=b.v()+"[]";a.j=b.A()+"[]"}else{var b=a.g,c=a.d,c=c.split("/");a.n=wb(".",[b,wb("$",c)]);a.b=wb(".",[b,wb(".",c)]);a.j=c[c.length-1]}}function pb(a){sb(a);return a.n}function Cb(a){sb(a);return a.j}
function Db(){this.i=Eb++;this.a=this.k=this.b=this.d=this.g=this.j=this.n=null}function Fb(a){var b;b=new Db;b.n="Class$"+(a?"S"+a:""+b.i);b.b=b.n;b.j=b.n;return b}function s(a){var b;b=Fb(a);Gb(a,b);return b}function Hb(a,b){var c;c=Fb(a);Gb(a,c);c.f=b?8:0;c.e=b;return c}function Ib(){var a;a=Fb(null);a.f=2;return a}function Jb(a,b){var c=a.a=a.a||[];return c[b]||(c[b]=a.u(b))}
function wb(a,b){for(var c=0;!b[c]||""==b[c];)c++;for(var d=b[c++];c<b.length;c++)b[c]&&""!=b[c]&&(d+=a+b[c]);return d}function Gb(a,b){if(a){b.k=a;var c=b.C()?null:ka[b.k];c?c.cZ=b:ka[a]=[b]}}k(54,1,{},Db);_.u=function(a){var b;b=new Db;b.f=4;1<a?b.c=Jb(this,a-1):b.c=this;return b};_.v=function(){sb(this);return this.b};_.w=function(){return pb(this)};_.A=function(){return Cb(this)};_.B=function(){return 0!=(this.f&4)};_.C=function(){return 0!=(this.f&1)};
_.tS=function(){return(0!=(this.f&2)?"interface ":0!=(this.f&1)?"":"class ")+(sb(this),this.n)};_.f=0;_.i=0;var Eb=1,Kb=s(1),Aa=s(0);s(54);k(5,1,ba);_.q=function(){return this.e};_.tS=function(){var a,b;a=pb(this.cZ);b=this.q();return null!=b?a+": "+b:a};s(5);function Lb(a){this.e=a;Mb(this,this.e)}k(7,5,ca,Lb);s(7);k(10,7,ca);s(10);k(78,10,ca);s(78);function Nb(){Nb=h;Ob=new oa}function Pb(a){Nb();this.e=null;this.a="";this.b=a;this.a=""}k(26,78,{26:1,3:1,7:1,5:1},Pb);
_.q=function(){var a;null==this.c&&(a=q(this.b)===q(Ob)?null:this.b,this.d=null==a?"null":null==a||wa(a)||a.tM===ma?wa(a)?"String":pb(za(a)):null==a?null:a.name,this.a=this.a+": "+(null==a||wa(a)||a.tM===ma?a+"":null==a?null:a.message),this.c="("+this.d+") "+this.a);return this.c};_.r=function(){return q(this.b)===q(Ob)?null:this.b};var Ob;s(26);k(147,1,{});s(147);function Qb(a){$wnd.setTimeout(function(){throw a;},0)}function Rb(){0!=ec&&(ec=0);fc=-1}var ec=0,Na=0,gc=0,fc=-1;
function hc(){hc=h;ic=new jc}function jc(){}function kc(a,b){var c,d,e;d=0;for(e=a.length;d<e;d++){c=a[d];try{if(c[1]){if(c[0].Eb()){var f=b;!f&&(f=[]);f[f.length]=c;b=f}}else c[0].Eb()}catch(g){if(g=lc(g),n(g,5))c=g,Qb(n(c,26)?c.r():c);else throw mc(g);}}return b}k(122,147,{},jc);var ic;s(122);function nc(){nc=h;var a,b;b=!(Error.stackTraceLimit||"stack"in Error());a=new oc;pc=b?new qc:a}function Mb(a,b){nc();pc.s(a,b)}var pc;k(159,1,{});s(159);function qc(){}k(84,159,{},qc);
_.s=function(a,b){var c={};a.fnStack=[];for(var d=arguments.callee.caller;d;){nc();var e;if(!(e=d.name)){e=d;var f=/function(?:\s+([\w$]+))?\s*\(/.exec(d.toString());e=e.name=f&&f[1]||"anonymous"}a.fnStack.push(e);e=":"+e;if(f=c[e]){var g,l;g=0;for(l=f.length;g<l;g++)if(f[g]===d)return}(f||(c[e]=[])).push(d);d=d.caller}};s(84);function rc(){rc=h;Error.stackTraceLimit=64}k(160,159,{});
_.s=function(a,b){function c(a){if(!("stack"in a))try{throw a;}catch(b){}return a}var d;"string"==typeof b?d=c(Error(b)):b instanceof Object&&"stack"in b?d=b:d=c(Error());a.__gwt$backingJsError=d};s(160);function oc(){rc()}k(85,160,{},oc);s(85);function u(a){if(!a)throw new sc;}function w(a,b){if(0>a||a>=b)throw new tc("Index: "+a+", Size: "+b);}function uc(a){if(null==a)throw new vc;}function wc(a,b){if(0>a||a>b)throw new tc("Index: "+a+", Size: "+b);}
function xc(a,b){return null==a[b]?null:String(a[b])}function x(a,b){return a.getAttribute(b)||""}function y(a){(a=a.parentNode)&&1==a.nodeType||(a=null);return a}function yc(a,b){var c;c=a.slice(0,b);z(za(a),a.cM,a.__elementTypeId$,a.__elementTypeCategory$,c);return c}function Cc(a,b){var c;c=Sc(0,b);z(za(a),a.cM,a.__elementTypeId$,a.__elementTypeCategory$,c);return c}function C(a,b,c,d){var e=da;c=Sc(d,c);z(Jb(a,1),e,b,d,c);return c}
function z(a,b,c,d,e){e.cZ=a;e.cM=b;e.tM=ma;e.__elementTypeId$=c;e.__elementTypeCategory$=d;return e}function Sc(a,b){var c=Array(b),d;switch(a){case 6:d={l:0,m:0,h:0};break;case 7:d=0;break;case 8:d=!1;break;default:return c}for(var e=0;e<b;++e)c[e]=d;return c}function mc(a){return n(a,26)&&q(a.b)!==q((Nb(),Ob))?q(a.b)===q(Ob)?null:a.b:a}function lc(a){var b;if(n(a,5))return a;b=a&&a.__gwt$exception;if(!b&&(b=new Pb(a),Mb(b,a),a&&"object"==typeof a))try{a.__gwt$exception=b}catch(c){}return b}
function Tc(){var a;a=navigator.userAgent.toLowerCase();var b=$doc.documentMode;a=-1!=a.indexOf("webkit")?"safari":-1!=a.indexOf("msie")&&10<=b&&11>b?"ie10":-1!=a.indexOf("msie")&&9<=b&&11>b?"ie9":-1!=a.indexOf("msie")&&8<=b&&11>b?"ie8":-1!=a.indexOf("gecko")||11<=b?"gecko1_8":"unknown";if("safari"!==a)throw new Uc(a);}k(42,5,ba);s(42);k(12,42,ba);s(12);
function Uc(a){this.e=""+("Possible problem with your *.gwt.xml module file.\nThe compile time user.agent value (safari) does not match the runtime user.agent value ("+a+").\nExpect more errors.");Mb(this,this.e)}k(77,12,ba,Uc);s(77);k(55,1,{});_.tS=function(){return this.a};s(55);function tc(a){Lb.call(this,a)}k(21,10,ca,tc);s(21);function Vc(){Mb(this,this.e)}k(137,21,ca,Vc);s(137);function Wc(){Wc=h;Xc=new Yc(!1);Zc=new Yc(!0)}function Yc(a){this.a=a}k(32,1,{3:1,32:1,15:1},Yc);
_.t=function(a){var b=this.a;return b==a.a?0:b?1:-1};_.eQ=function(a){return n(a,32)&&a.a==this.a};_.hC=function(){return this.a?1231:1237};_.tS=function(){return""+this.a};_.a=!1;var Xc,Zc;s(32);k(53,1,{3:1,53:1});s(53);k(11,1,{3:1,15:1,11:1});_.t=function(a){return this.b-a.b};_.eQ=function(a){return this===a};_.hC=function(){return this.$H||(this.$H=++Na)};_.tS=function(){return null!=this.a?this.a:""+this.b};_.b=0;s(11);function $c(a){Lb.call(this,a)}k(60,10,ca,$c);s(60);
function ad(){Mb(this,this.e)}k(134,10,ca,ad);s(134);function bd(a){this.a=a}function cd(a){var b,c;return-129<a&&128>a?(b=a+128,c=(dd(),ed)[b],!c&&(c=ed[b]=new bd(a)),c):new bd(a)}k(25,53,{3:1,15:1,25:1,53:1},bd);_.t=function(a){var b=this.a;a=a.a;return b<a?-1:b>a?1:0};_.eQ=function(a){return n(a,25)&&a.a==this.a};_.hC=function(){return this.a};_.tS=function(){return""+this.a};_.a=0;var fd=s(25);function dd(){dd=h;ed=C(fd,25,256,0)}var ed;function gd(a,b){return a<b?a:b}
function vc(){Mb(this,this.e)}function hd(a){Lb.call(this,a)}k(48,10,ca,vc,hd);s(48);function D(a,b){return null==b?!1:a==b?!0:a.length==b.length&&a.toLowerCase()==b.toLowerCase()}function id(a){var b=(160).toString(16),b="\\u"+"0000".substring(b.length)+b;return a.replace(RegExp(b,"g"),String.fromCharCode(32))}function jd(a){var b;b=kd("");return a.replace(RegExp("'","g"),b)}function ld(a,b){var c;c=kd("");return a.replace(RegExp(b),c)}
function md(a,b){for(var c=RegExp(b,"g"),d=[],e=0,f=a,g=null;;){var l=c.exec(f);if(null==l||""==f){d[e]=f;break}else d[e]=f.substring(0,l.index),f=f.substring(l.index+l[0].length,f.length),c.lastIndex=0,g==f&&(d[e]=f.substring(0,1),f=f.substring(1)),g=f,e++}if(0<a.length){for(c=d.length;0<c&&""==d[c-1];)--c;c<d.length&&d.splice(c,d.length-c)}c=C(m,2,d.length,4);for(e=0;e<d.length;++e)c[e]=d[e];return c}function nd(a,b){return a.substr(b,a.length-b)}
function od(a){return 0==a.length||" "<a[0]&&" "<a[a.length-1]?a:a.replace(/^[\u0000-\u0020]*|[\u0000-\u0020]*$/g,"")}function kd(a){var b;for(b=0;0<=(b=a.indexOf("\\",b));)36==a.charCodeAt(b+1)?a=a.substr(0,b)+"$"+nd(a,++b):a=a.substr(0,b)+nd(a,++b);return a}var m=s(2);function Ja(){Ja=h;La={};Ka={}}var La,Ma=0,Ka;function pd(){this.a=""}function qd(a){this.a=a}k(33,55,{171:1},pd,qd);s(33);function rd(a){Lb.call(this,a)}k(37,10,ca,rd);s(37);
function sd(a,b){var c,d,e;uc(b);c=!1;for(e=b.D();e.Q();)d=e.R(),c|=a.F(d);return c}function td(a){var b,c,d,e;e=new qd("[");b=!1;for(d=a.D();d.Q();)c=d.R(),b?e.a+=", ":b=!0,e.a+=c===a?"(this Collection)":""+c;e.a+="]";return e.a}k(162,1,{});_.F=function(){throw new rd("Add not supported on this collection");};_.G=function(a){return sd(this,a)};_.H=function(a){a:{var b,c;for(c=this.D();c.Q();)if(b=c.R(),q(a)===q(b)||null!=a&&ta(a,b)){a=!0;break a}a=!1}return a};_.I=function(){return 0==this.J()};
_.K=function(){return this.L(C(Kb,1,this.J(),3))};_.L=function(a){var b,c,d;d=this.J();a.length<d&&(a=Cc(a,d));c=this.D();for(b=0;b<d;++b)a[b]=c.R();a.length>d&&(a[d]=null);return a};_.tS=function(){return td(this)};s(162);function wd(a,b){var c,d,e;c=b.W();e=b.X();d=a.P(c);return!(q(e)===q(d)||null!=e&&ta(e,d))||null==d&&!a.N(c)?!1:!0}function yd(a,b){var c,d,e;for(d=a.O().D();d.Q();)if(c=d.R(),e=c.W(),q(b)===q(e)||null!=b&&ta(b,e))return c;return null}
function Gd(a,b){return b===a?"(this Map)":""+b}function Hd(a){return a?a.X():null}k(161,1,ea);_.M=function(a){return wd(this,a)};_.N=function(a){return!!yd(this,a)};_.eQ=function(a){var b;if(a===this)return!0;if(!n(a,30)||this.J()!=a.J())return!1;for(b=a.O().D();b.Q();)if(a=b.R(),!this.M(a))return!1;return!0};_.P=function(a){return Hd(yd(this,a))};_.hC=function(){return Yd(this.O())};_.J=function(){return this.O().J()};
_.tS=function(){var a,b,c,d;d=new qd("{");a=!1;for(c=this.O().D();c.Q();)b=c.R(),a?d.a+=", ":a=!0,d.a+=Gd(this,b.W()),d.a+="\x3d",b=Gd(this,b.X()),d.a+=b;d.a+="}";return d.a};s(161);function Zd(a,b){return wa(b)?F(a,b):!!xe(a.a,b)}function ye(a,b){return wa(b)?G(a,b):Hd(xe(a.a,b))}function G(a,b){return null==b?Hd(xe(a.a,null)):a.c.db(b)}function F(a,b){return null==b?!!xe(a.a,null):void 0!==a.c.db(b)}function ze(a,b,c){return wa(b)?H(a,b,c):Ae(a.a,b,c)}
function H(a,b,c){return null==b?Ae(a.a,null,c):a.c.gb(b,c)}function Be(a){Ce();a.a=De.ab();a.a.b=a;a.c=De.bb();a.c.b=a;a.b=0;Ee(a)}k(86,161,ea);_.N=function(a){return Zd(this,a)};_.O=function(){return new Fe(this)};_.P=function(a){return ye(this,a)};_.J=function(){return this.b};_.b=0;s(86);k(163,162,fa);_.eQ=function(a){if(a===this)a=!0;else if(n(a,17)&&a.J()==this.J())a:{var b;uc(a);for(b=a.D();b.Q();)if(a=b.R(),!this.H(a)){a=!1;break a}a=!0}else a=!1;return a};_.hC=function(){return Yd(this)};
s(163);function Fe(a){this.a=a}k(56,163,fa,Fe);_.H=function(a){return n(a,16)?wd(this.a,a):!1};_.D=function(){return new Ge(this.a)};_.J=function(){return this.a.b};s(56);function He(a){if(a.a.Q())return!0;if(a.a!=a.b)return!1;a.a=a.c.a.$();return a.a.Q()}function Ie(a){if(a._gwt_modCount!=a.c._gwt_modCount)throw new Je;return u(He(a)),a.a.R()}function Ge(a){this.c=a;this.a=this.b=this.c.c.$();this._gwt_modCount=a._gwt_modCount}k(57,1,{},Ge);_.Q=function(){return He(this)};_.R=function(){return Ie(this)};
s(57);k(164,162,{20:1});_.S=function(){throw new rd("Add not supported on this list");};_.F=function(a){this.S(this.J(),a);return!0};_.eQ=function(a){var b,c,d;if(a===this)return!0;if(!n(a,20)||this.J()!=a.J())return!1;d=a.D();for(b=this.D();b.Q();)if(a=b.R(),c=d.R(),!(q(a)===q(c)||null!=a&&ta(a,c)))return!1;return!0};_.hC=function(){var a,b,c;c=1;for(b=this.D();b.Q();)a=b.R(),c=31*c+(null!=a?Ba(a):0),c=~~c;return c};_.D=function(){return new I(this)};
_.U=function(){throw new rd("Remove not supported on this list");};s(164);function Ke(a){if(-1==a.c)throw new ad;a.d.U(a.c);a.b=a.c;a.c=-1}function I(a){this.d=a}k(4,1,{},I);_.Q=function(){return this.b<this.d.J()};_.R=function(){return u(this.b<this.d.J()),this.d.T(this.c=this.b++)};_.V=function(){Ke(this)};_.b=0;_.c=-1;s(4);function Le(a,b){this.d=this.a=a;wc(b,a.b.length);this.b=b}k(27,4,{},Le);s(27);function Me(a,b){w(b,a.b);return J(a.c,a.a+b)}
function Ne(a,b,c){var d=a.b.length;if(0>b)throw new tc("fromIndex: "+b+" \x3c 0");if(c>d)throw new tc("toIndex: "+c+" \x3e size "+d);if(b>c)throw new $c("fromIndex: "+b+" \x3e toIndex: "+c);this.c=a;this.a=b;this.b=c-b}k(47,164,{20:1},Ne);_.S=function(a,b){wc(a,this.b);Oe(this.c,this.a+a,b);++this.b};_.T=function(a){return Me(this,a)};_.U=function(a){w(a,this.b);a=this.c.U(this.a+a);--this.b;return a};_.J=function(){return this.b};_.a=0;_.b=0;s(47);
function Pe(a){a=new Ge((new Fe(a.a)).a);return new Qe(a)}function Re(a){this.a=a}k(45,163,fa,Re);_.H=function(a){return Zd(this.a,a)};_.D=function(){return Pe(this)};_.J=function(){return this.a.b};s(45);function Qe(a){this.a=a}k(87,1,{},Qe);_.Q=function(){return He(this.a)};_.R=function(){return Ie(this.a).W()};s(87);function Se(a,b){var c;c=a.d;a.d=b;return c}k(34,1,{34:1,16:1});_.eQ=function(a){return n(a,16)?Te(this.c,a.W())&&Te(this.d,a.X()):!1};_.W=function(){return this.c};_.X=function(){return this.d};
_.hC=function(){return Ue(this.c)^Ue(this.d)};_.Y=function(a){return Se(this,a)};_.tS=function(){return this.c+"\x3d"+this.d};s(34);function Ve(a,b){this.c=a;this.d=b}k(35,34,{34:1,35:1,16:1},Ve);s(35);k(167,1,{16:1});_.eQ=function(a){return n(a,16)?Te(this.W(),a.W())&&Te(this.X(),a.X()):!1};_.hC=function(){return Ue(this.W())^Ue(this.X())};_.tS=function(){return this.W()+"\x3d"+this.X()};s(167);function We(a,b){var c;c=Xe(a,b.W());return!!c&&Te(c.d,b.X())}k(170,161,ea);
_.M=function(a){return We(this,a)};_.N=function(a){return!!Xe(this,a)};_.O=function(){return new Ye(this)};_.P=function(a){return Hd(Xe(this,a))};s(170);function Ye(a){this.a=a}k(75,163,fa,Ye);_.H=function(a){return n(a,16)&&We(this.a,a)};_.D=function(){return new Ze(this.a)};_.J=function(){return this.a.b};s(75);function $e(a){a=new Ze((new af(a.a)).a);return new bf(a)}function cf(a){this.a=a}k(142,163,fa,cf);_.H=function(a){return!!Xe(this.a,a)};_.D=function(){return $e(this)};_.J=function(){return this.a.b};
s(142);function bf(a){this.a=a}k(143,1,{},bf);_.Q=function(){return this.a.a.Q()};_.R=function(){return this.a.a.R().W()};s(143);function df(a,b){var c;c=ef(a,b);try{return u(c.b!=c.d.c),c.c=c.b,c.b=c.b.a,++c.a,c.c.c}catch(d){d=lc(d);if(n(d,38))throw new tc("Can't get element "+b);throw mc(d);}}k(165,164,{20:1});_.S=function(a,b){var c;c=ef(this,a);ff(c.d,b,c.b.b,c.b);++c.a;c.c=null};_.T=function(a){return df(this,a)};_.D=function(){return ef(this,0)};
_.U=function(a){var b,c;b=ef(this,a);try{return c=(u(b.b!=b.d.c),b.c=b.b,b.b=b.b.a,++b.a,b.c.c),gf(b),c}catch(d){d=lc(d);if(n(d,38))throw new tc("Can't remove element "+a);throw mc(d);}};s(165);function Oe(a,b,c){wc(b,a.b.length);a.b.splice(b,0,c)}function K(a,b){a.b[a.b.length]=b;return!0}
function hf(a,b){var c;c=b.K();if(0==c.length)return!1;var d=c,e=a.b,f=a.b.length;c=c.length;var g=0;d===e&&(d=d.slice(g,g+c),g=0);for(var l=g,g=g+c;l<g;){var p=Math.min(l+1E4,g);c=p-l;Array.prototype.splice.apply(e,[f,0].concat(d.slice(l,p)));l=p;f+=c}return!0}function J(a,b){w(b,a.b.length);return a.b[b]}function jf(a,b){for(var c=0;c<a.b.length;++c)if(Te(b,a.b[c]))return c;return-1}function kf(a,b){var c;c=(w(b,a.b.length),a.b[b]);a.b.splice(b,1);return c}
function lf(a,b){var c,d;d=a.b.length;b.length<d&&(b=Cc(b,d));for(c=0;c<d;++c)b[c]=a.b[c];b.length>d&&(b[d]=null);return b}function L(){this.b=C(Kb,1,0,3)}k(6,164,ga,L);_.S=function(a,b){Oe(this,a,b)};_.F=function(a){return K(this,a)};_.G=function(a){return hf(this,a)};_.H=function(a){return-1!=jf(this,a)};_.T=function(a){return J(this,a)};_.I=function(){return 0==this.b.length};_.U=function(a){return kf(this,a)};_.J=function(){return this.b.length};_.K=function(){return yc(this.b,this.b.length)};
_.L=function(a){return lf(this,a)};s(6);function Yd(a){var b,c;c=0;for(b=a.D();b.Q();)a=b.R(),c+=null!=a?Ba(a):0,c=~~c;return c}function mf(){mf=h}function nf(a,b){uc(a);uc(b);return wa(a)?a==b?0:a<b?-1:1:a.t(b)}k(146,1,{},function(){});s(146);function Ee(a){a._gwt_modCount=(a._gwt_modCount|0)+1}function Je(){Mb(this,this.e)}k(144,10,ca,Je);s(144);function of(){Mb(this,this.e)}k(71,10,ca,of);s(71);function pf(a,b){return qf(a.a,b)?a.b[b.b]:null}function rf(a,b,c){sf(a.a,b);tf(a,b.b,c)}
function tf(a,b,c){var d;d=a.b[b];a.b[b]=c;return d}function uf(a){var b;this.a=(b=a.e&&a.e(),new vf(b,Cc(b,b.length)));this.b=C(Kb,1,this.a.a.length,3)}k(123,161,ea,uf);_.N=function(a){return qf(this.a,a)};_.O=function(){return new wf(this)};_.P=function(a){return pf(this,a)};_.J=function(){return this.a.c};s(123);function wf(a){this.a=a}k(67,163,fa,wf);_.H=function(a){return n(a,16)?wd(this.a,a):!1};_.D=function(){return new xf(this.a)};_.J=function(){return this.a.a.c};s(67);
function xf(a){this.c=a;this.a=new yf(this.c.a)}k(68,1,{},xf);_.Q=function(){return zf(this.a)};_.R=function(){return this.b=Af(this.a),new Bf(this.c,this.b)};s(68);function Bf(a,b){this.b=a;this.a=b}k(69,167,{16:1},Bf);_.W=function(){return this.a};_.X=function(){return this.b.b[this.a.b]};_.Y=function(a){return tf(this.b,this.a.b,a)};s(69);k(169,163,fa);s(169);function sf(a,b){var c;uc(b);c=b.b;return a.b[c]?!1:(a.b[c]=b,++a.c,!0)}function qf(a,b){return n(b,11)&&!!b&&a.b[b.b]==b}
function vf(a,b){this.a=a;this.b=b;this.c=0}k(135,169,fa,vf);_.F=function(a){return sf(this,a)};_.H=function(a){return qf(this,a)};_.D=function(){return new yf(this)};_.J=function(){return this.c};_.c=0;s(135);function Cf(a){var b;++a.a;for(b=a.c.a.length;a.a<b&&!a.c.b[a.a];++a.a);}function zf(a){return a.a<a.c.a.length}function Af(a){return u(a.a<a.c.a.length),a.b=a.a,Cf(a),a.c.b[a.b]}function yf(a){this.c=a;Cf(this)}k(70,1,{},yf);_.Q=function(){return zf(this)};_.R=function(){return Af(this)};
_.a=-1;_.b=-1;s(70);function Df(a,b){return q(a)===q(b)||null!=a&&ta(a,b)}function Ef(){Be(this)}k(13,86,{3:1,30:1},Ef);s(13);function M(a,b){return null==ze(a.a,b,a)}function N(a,b){return Zd(a.a,b)}function Ff(){this.a=new Ef}k(14,163,{3:1,17:1},Ff);_.F=function(a){return M(this,a)};_.H=function(a){return N(this,a)};_.I=function(){return 0==this.a.b};_.D=function(){return Pe(new Re(this.a))};_.J=function(){return this.a.b};_.tS=function(){return td(new Re(this.a))};s(14);
function xe(a,b){var c,d,e,f;c=null==b?"0":""+~~Ba(b);d=a.a[c]||[];e=0;for(f=d.length;e<f;++e)if(c=d[e],Df(b,c.W()))return c;return null}function Ae(a,b,c){var d,e,f,g;d=null==b?"0":""+~~Ba(b);e=a.a;d=e[d]||(e[d]=[]);f=0;for(g=d.length;f<g;++f)if(e=d[f],Df(b,e.W()))return e.Y(c);d[d.length]=new Ve(b,c);a=a.b;++a.b;Ee(a);return null}function Gf(){this.a=this.Z()}k(66,1,{},Gf);_.Z=function(){return Object.create(null)};_.$=function(){return new Hf(this)};s(66);
function Nf(a){if(a.c<a.a.length)return!0;if(a.b<a.d.length-1){var b=a.d[++a.b];a.a=a.f.a[b];a.c=0;return!0}return!1}function Hf(a){this.f=a;this.d=Object.getOwnPropertyNames(this.f.a);this.a=C(Pf,16,0,0)}k(121,1,{},Hf);_.Q=function(){return Nf(this)};_.R=function(){return u(Nf(this)),this.e=this.a[this.c++],this.e};_.b=-1;_.c=0;_.e=null;s(121);function zg(){Gf.call(this)}k(119,66,{},zg);_.Z=function(){return{}};
_.$=function(){var a=this._(),b=this.a,c;for(c in b)if(c==parseInt(c,10))for(var d=b[c],e=0,f=d.length;e<f;++e)a.F(d[e]);return a.D()};_._=function(){return new Ag(this)};s(119);function Ag(a){this.a=a;L.call(this)}k(120,6,ga,Ag);_.U=function(a){a=kf(this,a);a:{var b=this.a,c=a.W(),d,e,f,g;f=null==c?"0":""+~~Ba(c);d=b.a[f]||[];for(g=0;g<d.length;g++)if(e=d[g],Df(c,e.W())){1==d.length?delete b.a[f]:d.splice(g,1);b=b.b;--b.b;Ee(b);e.X();break a}}return a};s(120);function Bg(){}k(116,1,{},Bg);_.ab=function(){return new Gf};
_.bb=function(){return new Mg};s(116);function Ce(){Ce=h;var a,b;if(b=Object.create&&Object.getOwnPropertyNames)b=Object.create(null),void 0!==b.__proto__||0!=Object.getOwnPropertyNames(b).length?b=!1:(b.__proto__=42,b=42!==b.__proto__?!1:!0);De=b?(a=Object.create(null),a.__proto__=42,0==Object.getOwnPropertyNames(a).length)?new Ng:new Bg:new Og}var De;function Ng(){}k(118,116,{},Ng);_.bb=function(){return new Pg};s(118);function Og(){}k(117,116,{},Og);_.ab=function(){return new zg};_.bb=function(){return new Qg};
s(117);function Rg(a,b,c){var d;d=a.a[b];if(void 0===d){var e=a.b;++e.b;Ee(e)}a.a[b]=void 0===c?null:c;return d}function Sg(a,b){var c;c=a.a[b];if(void 0!==c){delete a.a[b];var d=a.b;--d.b;Ee(d)}return c}function Mg(){this.a=this.cb()}k(49,1,{},Mg);_.cb=function(){return Object.create(null)};_.$=function(){var a;a=this.eb();return new Tg(this,a)};_.db=function(a){return this.a[a]};_.eb=function(){return Object.getOwnPropertyNames(this.a)};_.fb=function(a){return new Ug(this,a)};
_.gb=function(a,b){return Rg(this,a,b)};_.hb=function(a){return Sg(this,a)};s(49);function Tg(a,b){this.b=a;this.c=b}k(102,1,{},Tg);_.Q=function(){return this.a<this.c.length};_.R=function(){return u(this.a<this.c.length),new Ug(this.b,this.c[this.a++])};_.a=0;s(102);function Ug(a,b){this.a=a;this.b=b}k(61,167,{16:1},Ug);_.W=function(){return this.b};_.X=function(){return this.a.db(this.b)};_.Y=function(a){return this.a.gb(this.b,a)};s(61);function Qg(){Mg.call(this)}k(99,49,{},Qg);_.cb=function(){return{}};
_.$=function(){var a=this.ib(),b;for(b in this.a)if(58==b.charCodeAt(0)){var c=this.fb(b.substring(1));a.F(c)}return a.D()};_.db=function(a){return this.a[":"+a]};_.ib=function(){return new Vg(this)};_.gb=function(a,b){return Rg(this,":"+a,b)};_.hb=function(a){return Sg(this,":"+a)};s(99);function Vg(a){this.a=a;L.call(this)}k(101,6,ga,Vg);_.U=function(a){var b;return b=kf(this,a),Sg(this.a,":"+b.W()),b};s(101);function Pg(){Mg.call(this)}k(100,49,{},Pg);
_.eb=function(){var a;a=Object.getOwnPropertyNames(this.a);void 0!==this.a.__proto__&&(a[a.length]="__proto__");return a};s(100);function Wg(a,b){ff(a,b,a.c.b,a.c);return!0}function ff(a,b,c,d){var e;e=new Xg;e.c=b;e.b=c;e.a=d;d.b=c.a=e;++a.b}function ef(a,b){var c,d;wc(b,a.b);if(b>=a.b>>1)for(d=a.c,c=a.b;c>b;--c)d=d.b;else for(d=a.a.a,c=0;c<b;++c)d=d.a;return new Yg(a,b,d)}function Zg(){this.a=new Xg;this.c=new Xg;this.a.a=this.c;this.c.b=this.a;this.a.b=this.c.a=null;this.b=0}k(58,165,ga,Zg);
_.F=function(a){return Wg(this,a)};_.J=function(){return this.b};_.b=0;s(58);function gf(a){var b;if(!a.c)throw new ad;b=a.c.a;var c=a.d,d=a.c;d.a.b=d.b;d.b.a=d.a;d.a=d.b=null;d.c=null;--c.b;a.b==a.c?a.b=b:--a.a;a.c=null}function Yg(a,b,c){this.d=a;this.b=c;this.a=b}k(88,1,{},Yg);_.Q=function(){return this.b!=this.d.c};_.R=function(){return u(this.b!=this.d.c),this.c=this.b,this.b=this.b.a,++this.a,this.c.c};_.V=function(){gf(this)};_.a=0;_.c=null;s(88);function Xg(){}k(46,1,{},Xg);s(46);var Pf=Ib();
function sc(){Mb(this,this.e)}k(38,10,{3:1,7:1,5:1,38:1},sc);s(38);function Te(a,b){return q(a)===q(b)||null!=a&&ta(a,b)}function Ue(a){return null!=a?Ba(a):0}function $g(a,b){if(0>a||a>=b)throw new Vc;}k(124,164,ga);_.S=function(a,b){$g(a,this.a.b.length+1);Oe(this.a,a,b)};_.F=function(a){return K(this.a,a)};_.G=function(a){return hf(this.a,a)};_.H=function(a){return-1!=jf(this.a,a)};_.T=function(a){return $g(a,this.a.b.length),J(this.a,a)};_.I=function(){return 0==this.a.b.length};_.D=function(){return new I(this.a)};
_.U=function(a){return $g(a,this.a.b.length),this.a.U(a)};_.J=function(){return this.a.b.length};_.K=function(){var a=this.a;return yc(a.b,a.b.length)};_.L=function(a){return lf(this.a,a)};_.tS=function(){return td(this.a)};s(124);function ah(){this.a=new L}k(125,124,ga,ah);s(125);function Xe(a,b){var c,d;for(d=a.a;d;){c=nf(b,d.c);if(0==c)return d;c=0>c?0:1;d=d.a[c]}return null}
function bh(a,b,c,d,e,f,g,l){var p;if(d){(p=d.a[0])&&bh(a,b,c,p,e,f,g,l);p=d.c;var t,v;c.jb()&&(t=nf(p,e),0>t||!f&&0==t)||c.kb()&&(v=nf(p,g),0<v||!l&&0==v)||b.F(d);(d=d.a[1])&&bh(a,b,c,d,e,f,g,l)}}function ch(a,b,c,d){var e,f;if(b){e=nf(c.c,b.c);if(0==e)return d.d=Se(b,c.d),d.b=!0,b;e=0>e?0:1;b.a[e]=ch(a,b.a[e],c,d);dh(b.a[e])&&(dh(b.a[1-e])?(b.b=!0,b.a[0].b=!1,b.a[1].b=!1):dh(b.a[e].a[e])?b=eh(b,1-e):dh(b.a[e].a[1-e])&&(b=(f=1-(1-e),b.a[f]=eh(b.a[f],f),eh(b,1-e))))}else return c;return b}
function dh(a){return!!a&&a.b}function eh(a,b){var c,d;c=1-b;d=a.a[c];a.a[c]=d.a[b];d.a[b]=a;a.b=!0;d.b=!1;return d}function fh(){this.a=null;mf()}k(74,170,{3:1,30:1},fh);_.O=function(){return new af(this)};_.J=function(){return this.b};_.b=0;s(74);function Ze(a){var b=(gh(),hh),c;c=new L;bh(a,c,b,a.a,null,!1,null,!1);this.a=new Le(c,0)}k(52,1,{},Ze);_.Q=function(){return this.a.Q()};_.R=function(){return this.a.R()};s(52);function af(a){this.a=a}k(76,75,fa,af);s(76);
function ih(a,b){Ve.call(this,a,b);this.a=C(jh,41,2,0);this.b=!0}k(41,35,{34:1,35:1,16:1,41:1},ih);_.b=!1;var jh=s(41);function kh(){}k(138,1,{},kh);_.tS=function(){return"State: mv\x3d"+this.c+" value\x3d"+this.d+" done\x3d"+this.a+" found\x3d"+this.b};_.a=!1;_.b=!1;_.c=!1;s(138);function gh(){gh=h;hh=new lh("All",0);mh=new nh;oh=new ph;qh=new rh}function lh(a,b){this.a=a;this.b=b}k(18,11,ha,lh);_.jb=function(){return!1};_.kb=function(){return!1};
var hh,mh,oh,qh,sh=Hb(18,function(){gh();return z(Jb(sh,1),da,18,0,[hh,mh,oh,qh])});function nh(){this.a="Head";this.b=1}k(139,18,ha,nh);_.kb=function(){return!0};Hb(139,null);function ph(){this.a="Range";this.b=2}k(140,18,ha,ph);_.jb=function(){return!0};_.kb=function(){return!0};Hb(140,null);function rh(){this.a="Tail";this.b=3}k(141,18,ha,rh);_.jb=function(){return!0};Hb(141,null);function th(a){this.a=new fh;sd(this,a)}k(72,163,{3:1,17:1},th);
_.F=function(a){var b=this.a,c=(Wc(),Xc);a=new ih(a,c);c=new kh;b.a=ch(b,b.a,a,c);c.b||++b.b;b.a.b=!1;return null==c.d};_.H=function(a){return!!Xe(this.a,a)};_.D=function(){return $e(new cf(this.a))};_.J=function(){return this.a.b};s(72);
function uh(a){var b;if(!(0<a.a.b)){b=vh(a.f);!b.length||Wg(a.a,b);b=a.a;var c;var d=$doc.title,e=$doc.documentElement,f;c=f="";m==m?f=c=d:e&&(d=e.getElementsByTagName("TITLE"),0<d.length&&(f=c=d[0].textContent));if(""==f)c="";else{if(/ [\|\-] /i.test(f))f=c.replace(RegExp("(.*)[\\|\\-] .*","gi"),"$1"),3>wh(f)&&(f=c.replace(RegExp("[^\\|\\-]*[\\|\\-](.*)","gi"),"$1"));else if(-1!=f.indexOf(": "))f=c.replace(RegExp(".*:(.*)","gi"),"$1"),3>wh(f)&&(f=c.replace(RegExp("[^:]*[:](.*)","gi"),"$1"));else if(e&&
(150<f.length||15>f.length)){f=e.getElementsByTagName("H1");e="";for(d=0;d<f.length&&!e.length;d++)e=f[d].innerText;f=e;!f.length&&(f=c)}f=f.trim();4>=wh(f)&&(f=c);c=f}Wg(b,c);m==m&&Wg(a.a,$doc.title)}}function xh(a){var b,c;this.b=a;this.a=new Zg;this.e=(b={},b[6]=[],b);this.d=(c={},c);this.c=new L;b=O();this.f=new yh(a,this.e);a=O()-b;if(void 0==a)throw new TypeError;this.e[1]=a;this.g=""}k(79,1,{},xh);s(79);function zh(){}k(80,1,{},zh);s(80);
function Ah(a){var b,c,d,e,f,g,l,p,t,v,V,Zi,If,ud,vd,$i,aj;l=O();f=(V={},V[10]=[],V);c=new xh($doc.documentElement);var bj=(uh(c),df(c.a,0));if(void 0==bj)throw new TypeError;f[1]=bj;var Jf;if(void 0!=a[2]){if(void 0===a[2])throw new TypeError;Jf=a[2]}else Jf=0;P=Jf;Q("DomDistiller debug level: "+P);b=(Zi={},Zi);var Kf;if(Kf=void 0!=a[1]){if(void 0===a[1])throw new TypeError;Kf=a[1]}var cj=Kf,Sb,zc,Lf,Ac,Tb,dj,Oa,Mf,Bc,ej;Tb=O();Sb=(Mf=new zh,Bc=new Bh,ej=new Ch(Bc),Dh(new Eh(ej),c.b),Mf.a=(Fh(Bc,
Bc.d),Bc.b),uh(c),Mf);var hj=O()-Tb;if(void 0==hj)throw new TypeError;c.e[2]=hj;Tb=O();var A;var pa=Sb.a,Dc,xd,ja,Of,Ub;Ub=new L;b:{var Ec;for(Ec=0;Ec<pa.a.b.length;Ec++)if(n(J(pa.a,Ec),24)){ja=Ec;break b}ja=pa.a.b.length}if(ja!=pa.a.b.length){Of=xd=J(pa.a,ja).d;Dc=new Gh(pa.a,ja);for(++ja;ja<pa.a.b.length;ja++)n(J(pa.a,ja),24)&&(xd=J(pa.a,ja).d,xd==Of?Hh(Dc,new Gh(pa.a,ja)):(Ub.b[Ub.b.length]=Dc,Of=xd,Dc=new Gh(pa.a,ja)));Ub.b[Ub.b.length]=Dc}A=new Ih(Ub);var Ul=c.a,E;Jh(A,!0,"Start");var Vl=(Kh(),
A),Qf,Pa;for(Pa=new I(Vl.a);Pa.b<Pa.d.J();){Qf=(u(Pa.b<Pa.d.J()),Pa.d.T(Pa.c=Pa.b++));var Rf;var Sf=Qf,zd=void 0;14<Sf.d?Rf=!1:(zd=Sf.g.trim(),Rf=8<=zd.length?Lh.test(zd):1==Sf.c?"Comment"===zd:!1);Rf&&M(Qf.b,"STRICTLY_NOT_CONTENT")}var Tf=new Mh(Ul),Ad,Qa,qa;if(Tf.a)for(Qa=new I(A.a);Qa.b<Qa.d.J();)Ad=(u(Qa.b<Qa.d.J()),Qa.d.T(Qa.c=Qa.b++)),qa=Ad.g,qa=id(qa),qa=jd(qa),qa=od(qa).toLowerCase(),N(Tf.a,qa)&&M(Ad.b,"de.l3s.boilerpipe/TITLE"),qa=od(qa.replace(Nh,"")),N(Tf.a,qa)&&M(Ad.b,"de.l3s.boilerpipe/TITLE");
var Fc,Bd,ra,Gc,Hc,ua,Ca;ua=A.a;if(0==ua.b.length)E=!1;else{Bd=!1;for(ra=0;ra<ua.b.length;ra++)Hc=0==ra?null:(w(ra-1,ua.b.length),ua.b[ra-1]),Fc=(w(ra,ua.b.length),ua.b[ra]),Gc=ra+1==ua.b.length?null:(w(ra+1,ua.b.length),ua.b[ra+1]),Bd|=(0.333333>=Fc.c?!Hc||0.555556>=Hc.c?16>=Fc.d?!Gc||15>=Gc.d?!Hc||4>=Hc.d?Ca=!1:Ca=!0:Ca=!0:Ca=!0:40>=Fc.d?!Gc||17>=Gc.d?Ca=!1:Ca=!0:Ca=!0:Ca=!1,Oh(Fc,Ca));E=Bd}Jh(A,E,"Classification Complete");var Wl=(Ph(),Qh),Uf,pj,Vf,Cd,qj,Dd,Ra;Uf=!1;Ra=new I(A.a);a:for(;Ra.b<Ra.d.J();)if(Dd=
(u(Ra.b<Ra.d.J()),Ra.d.T(Ra.c=Ra.b++)),Dd.a)for(Vf=Wl.a,Cd=0,qj=Vf.length;Cd<qj;++Cd)if(pj=Vf[Cd],N(Dd.b,pj)){Oh(Dd,!1);Uf=!0;continue a}E=Uf;Jh(A,E,"Ignore Strictly Not Content blocks");var Wf=Rh();Wf.e=0.5;Wf.d=10;E=Sh(Th(Wf),A);Jh(A,E,"SimilarSiblingContentExpansion: Cross headings");var Ed=Rh();Ed.c=!0;Ed.e=0;Ed.d=10;E=Sh(Th(Ed),A);Jh(A,E,"SimilarSiblingContentExpansion: Mixed tags");var Fd,Sa,uj,Ic,sa,Xf;Xf=A.a;if(2>Xf.b.length)E=!1;else{Fd=!1;Ic=new Le(Xf,0);for(Sa=Ic.R();Ic.Q();)if(sa=Sa,Sa=
Ic.R(),N(sa.b,"de.l3s.boilerpipe/HEADING")&&!(N(sa.b,"STRICTLY_NOT_CONTENT")||N(Sa.b,"STRICTLY_NOT_CONTENT")||N(sa.b,"de.l3s.boilerpipe/TITLE")||N(Sa.b,"de.l3s.boilerpipe/TITLE")))if(Sa.a){Fd=!0;uj=sa.a;Hh(sa,Sa);Sa=sa;Ic.V();var vj=sa;N(vj.b,"de.l3s.boilerpipe/HEADING")&&vj.b.a.c.hb("de.l3s.boilerpipe/HEADING");uj||M(sa.b,"BOILERPLATE_HEADING_FUSED")}else sa.a&&(Fd=!0,Oh(sa,!1));E=Fd}Jh(A,E,"HeadingFusion");E=Uh((Vh(),Wh),A);Jh(A,E,"BlockProximityFusion: Distance 1");var Xl=(Xh(),Yh),Yf,Da,Zf,Bj;
Bj=A.a;Yf=!1;for(Da=new I(Bj);Da.b<Da.d.J();)Zf=(u(Da.b<Da.d.J()),Da.d.T(Da.c=Da.b++)),Zf.a||null!=Xl.a&&N(Zf.b,"de.l3s.boilerpipe/TITLE")||(Ke(Da),Yf=!0);E=Yf;Jh(A,E,"BlockFilter");E=Uh(Zh,A);Jh(A,E,"BlockProximityFusion: Same level content-only");var Yl=($h(),ai),$f,Ta,Jc,ag,bg,va,Ua,Va,Vb;Vb=A.a;if(2>Vb.b.length)E=!1;else{ag=-1;Ta=null;$f=0;Jc=-1;for(Va=new I(Vb);Va.b<Va.d.J();)va=(u(Va.b<Va.d.J()),Va.d.T(Va.c=Va.b++)),va.a&&(bg=va.d,bg>ag&&(Ta=va,ag=bg,Jc=$f)),++$f;for(Ua=new I(Vb);Ua.b<Ua.d.J();)va=
(u(Ua.b<Ua.d.J()),Ua.d.T(Ua.c=Ua.b++)),va==Ta?(Oh(va,!0),M(va.b,"de.l3s.boilerpipe/VERY_LIKELY_CONTENT")):(Oh(va,!1),M(va.b,"de.l3s.boilerpipe/MIGHT_BE_CONTENT"));if(Yl.a&&-1!=Jc){var Zl=Jc,Wa,Fj,cg,dg;dg=y(bi(J(Ta.j,J(Ta.i,Ta.i.b.length-1).a)));for(cg=new Le(Vb,Zl+1);cg.Q();)Wa=cg.R(),Fj=y(ci(J(Wa.j,J(Wa.i,0).a))),y(dg)==y(Fj)&&(Oh(Wa,!0),M(Wa.b,"SIBLING_OF_MAIN_CONTENT"),dg=y(bi(J(Wa.j,J(Wa.i,Wa.i.b.length-1).a))));var $l=Jc,Xa,Gj,eg,Wb;eg=y(ci(J(Ta.j,J(Ta.i,0).a)));for(Wb=new Le(Vb,$l);0<Wb.b;)Xa=
(u(0<Wb.b),J(Wb.a,Wb.c=--Wb.b)),Gj=y(bi(J(Xa.j,J(Xa.i,Xa.i.b.length-1).a))),y(eg)==y(Gj)&&(Oh(Xa,!0),M(Xa.b,"SIBLING_OF_MAIN_CONTENT"),eg=y(ci(J(Xa.j,J(Xa.i,0).a))))}E=!0}Jh(A,E,"Keep Largest Block");var Id,tb,Jd,Xb,Ya,Za,Kc;Jd=0;tb=Kc=-1;for(Za=new I(A.a);Za.b<Za.d.J();)Xb=(u(Za.b<Za.d.J()),Za.d.T(Za.c=Za.b++)),-1==tb&&N(Xb.b,"de.l3s.boilerpipe/TITLE")&&(Kc=Jd,tb=-1),-1==tb&&Xb.a&&(tb=Jd),++Jd;if(tb<=Kc||-1==Kc)E=!1;else{Id=!1;for(Ya=new I(new Ne(A.a,Kc,tb));Ya.b<Ya.d.J();)Xb=(u(Ya.b<Ya.d.J()),Ya.d.T(Ya.c=
Ya.b++)),N(Xb.b,"de.l3s.boilerpipe/MIGHT_BE_CONTENT")&&(Id|=Oh(Xb,!0));E=Id}Jh(A,E,"Expand Title to Content");var fg,Kd,Ea,$a,ab;fg=!1;Kd=-1;for(ab=new I(A.a);ab.b<ab.d.J();)if(Ea=(u(ab.b<ab.d.J()),ab.d.T(ab.c=ab.b++)),Ea.a&&N(Ea.b,"de.l3s.boilerpipe/VERY_LIKELY_CONTENT")){Kd=Ea.f;break}if(-1==Kd)E=!1;else{for($a=new I(A.a);$a.b<$a.d.J();)Ea=(u($a.b<$a.d.J()),$a.d.T($a.c=$a.b++)),!Ea.a&&100<=Ea.d&&Ea.f==Kd&&(Oh(Ea,!0),fg=!0);E=fg}Jh(A,E,"Largest Block Same Tag Level -\x3e Content");var gg,Ld,Fa,bb;
gg=!1;Ld=aa;for(bb=new I(A.a);bb.b<bb.d.J();)Fa=(u(bb.b<bb.d.J()),bb.d.T(bb.c=bb.b++)),Fa.a&&N(Fa.b,"de.l3s.boilerpipe/VERY_LIKELY_CONTENT")?Ld=Fa.f:Fa.f>Ld&&N(Fa.b,"de.l3s.boilerpipe/MIGHT_BE_CONTENT")&&N(Fa.b,"de.l3s.boilerpipe/LI")&&0==Fa.c?(Oh(Fa,!0),gg=!0):Ld=aa;E=gg;Jh(A,E,"List at end filter");var am=c.d,hg,Md,ig,cb;Md=0;for(cb=new I(A.a);cb.b<cb.d.J();)ig=(u(cb.b<cb.d.J()),cb.d.T(cb.c=cb.b++)),ig.a&&(Md+=ig.d);hg=Md;if(void 0==hg)throw new TypeError;am[1]=hg;var bm,db;for(db=new I(A.a);db.b<
db.d.J();){var Nd=bm=(u(db.b<db.d.J()),db.d.T(db.c=db.b++)),Hj=void 0,eb=void 0,jg=void 0;if(Nd.a)for(eb=new I(Nd.i);eb.b<eb.d.J();)Hj=(u(eb.b<eb.d.J()),eb.d.T(eb.c=eb.b++)),jg=J(Nd.j,Hj.a),jg.p=!0,N(Nd.b,"de.l3s.boilerpipe/TITLE")&&M(jg.e,"de.l3s.boilerpipe/TITLE")}var Od,fb,Pd;Pd=!1;for(fb=new I(Sb.a.a);fb.b<fb.d.J();)Od=(u(fb.b<fb.d.J()),fb.d.T(fb.c=fb.b++)),Od.p?Pd=!0:n(Od,24)?Pd=!1:Pd&&(Od.p=!0);var cm=Sb.a,Qd,ub,gb,Yb;Qd=new L;Yb=null;for(gb=new I(cm.a);gb.b<gb.d.J();)if(ub=(u(gb.b<gb.d.J()),
gb.d.T(gb.c=gb.b++)),n(ub,36))if(ub.p)break;else K(Qd,ub);else!Yb&&n(ub,24)&&ub.p&&(Yb=ub);var Lc,kg,lg,Mc,Ij,Rd,hb,Zb;if(0!=Qd.b.length){lg=null;Yb&&(lg=J(Yb.a,Yb.c));Ij=(Zb=new L,K(Zb,new di),K(Zb,new ei),K(Zb,new fi(lg)),K(Zb,new gi),Zb);Lc=null;kg=0;for(hb=new I(Qd);hb.b<hb.d.J();){Rd=(u(hb.b<hb.d.J()),hb.d.T(hb.c=hb.b++));var Sd=void 0,Nj=void 0,ib=void 0,Nc=void 0;if(Rd){Nc=0;Sd=Rd.a;for(ib=new I(Ij);ib.b<ib.d.J();)Nj=(u(ib.b<ib.d.J()),ib.d.T(ib.c=ib.b++)),Nc+=Nj.Cb(Sd);2>P||(Sd?Q("FINAL SCORE: "+
Nc+" : "+x(Sd,"src")):Q("Null image attempting to be scored!"));Mc=Nc}else Mc=0;26<=Mc&&(!Lc||kg<Mc)&&(Lc=Rd,kg=Mc)}Lc&&(Lc.p=!0)}var dm=Sb.a,Td,jb,mg;mg=new L;for(jb=new I(dm.a);jb.b<jb.d.J();)Td=(u(jb.b<jb.d.J()),jb.d.T(jb.c=jb.b++)),n(Td,36)&&Td.p&&K(mg,Td);for(Oa=new I(mg);Oa.b<Oa.d.J();)dj=(u(Oa.b<Oa.d.J()),Oa.d.T(Oa.c=Oa.b++)),K(c.c,dj.b);var Oj=O()-Tb;if(void 0==Oj)throw new TypeError;c.e[3]=Oj;Tb=O();var ng,kb,$b;$b=new pd;for(kb=new I(Sb.a.a);kb.b<kb.d.J();)if(ng=(u(kb.b<kb.d.J()),kb.d.T(kb.c=
kb.b++)),ng.p){var em=ng.Ab(cj);$b.a+=em;cj&&($b.a+="\n")}Lf=$b.a;var Pj=O()-Tb;if(void 0==Pj)throw new TypeError;c.e[4]=Pj;if(4<=P){for(Ac=0;Ac<c.e[6].length;Ac++){var Qj=c.e;if(Ac>=Qj[6].length)throw new RangeError;zc=Qj[6][Ac];if(void 0===zc[1])throw new TypeError;var fm="Timing: "+zc[1]+" \x3d ";if(void 0===zc[2])throw new TypeError;Q(fm+zc[2])}var Rj=c.e;if(void 0===Rj[1])throw new TypeError;var gm="Timing: MarkupParsingTime \x3d "+Rj[1]+"\nTiming: DocumentConstructionTime \x3d ",Sj=c.e;if(void 0===
Sj[2])throw new TypeError;var hm=gm+Sj[2]+"\nTiming: ArticleProcessingTime \x3d ",Tj=c.e;if(void 0===Tj[3])throw new TypeError;var im=hm+Tj[3]+"\nTiming: FormattingTime \x3d ",Uj=c.e;if(void 0===Uj[4])throw new TypeError;Q(im+Uj[4])}if(void 0==Lf)throw new TypeError;b[1]=Lf;if(void 0==b)throw new TypeError;f[2]=b;var Vj=((null==c.g||!c.g.length)&&(c.g="auto"),c.g);if(void 0==Vj)throw new TypeError;f[9]=Vj;for(v=new I(c.c);v.b<v.d.J();){t=(u(v.b<v.d.J()),v.d.T(v.c=v.b++));var jm=(If={},f[10].push(If),
If);if(void 0==t)throw new TypeError;jm[1]=t}var og;if(void 0!=a[3]){if(void 0===a[3])throw new TypeError;og=a[3]}else og=$wnd.location.href;e=og;p=c.e;g=O();hi();ud={};var Xj=$doc.documentElement,vb,pg,qg,rg,Ga,sg,Oc,B,lb,Y,tg,r,mb,ac,Ud,Vd,ug,bc,cc,dc,Wd,Xd,Yj,Ha,vg,Zj,ak;3<=P&&Be(ii);Ga=e.replace(RegExp("\\/[^/]*$","gi"),"");Zj=e.replace(RegExp("\\/$","gi"),"");vb=Xj.getElementsByTagName("A");Xd=new Ff;var wg;var xg,yg;yg=Xj.getElementsByTagName("BASE");if(0==yg.length)wg=e;else{xg=ji(e);var km=
x(yg[0],"href");xg.setAttribute("href",km);wg=xg.href}qg=ji(wg);var lm=md(e,":\\/\\/")[0]+"://",ck,Pc=e,Pc=md(Pc,":\\/\\/")[1];ck=-1==Pc.indexOf("/")?Pc:md(Pc,"\\/")[0];pg=lm+ck+"/";var mm="^"+pg.replace(/[\-\[\]{}()*+?.,\\\^$|#\s]/g,"\\$\x26")+".*\\d";Yj=RegExp(mm,"i");for(Oc=0;Oc<vb.length;Oc++)if(B=vb[Oc],ak=x(B,"href"),qg.setAttribute("href",ak),Y=qg.href,Yj.test(Y))if(vg=(B.offsetWidth||0)|0,sg=(B.offsetHeight||0)|0,0==vg||0==sg)R(B,"ignored: sz\x3d"+vg+"x"+sg);else if(ki(B))if(Y=Y.replace(li,
""),R(B,"-\x3e "+Y),D(Y,Zj)||D(Y,Ga))R(B,"ignored: same as current or folder url "+Ga);else if(mb=B.innerText,mi.test(mb)||25<mb.length)R(B,"ignored: one of extra");else if(tg=Y,Y.substr(0,Ga.length)===Ga&&(tg=nd(Y,Ga.length)),ni.test(tg)){r=new oi(Oc,mb,Y);M(Xd,r);0!=Y.indexOf(Ga)&&(r.d-=25,R(B,"score\x3d"+r.d+": not part of folder url "+Ga));lb=mb+" "+(B.className||"")+" "+B.id;R(B,"txt+class+id\x3d"+lb);pi.test(lb)&&(r.d+=50,R(B,"score\x3d"+r.d+": has next"));qi.test(lb)&&(r.d+=25,R(B,"score\x3d"+
r.d+": has pag* word"));ri.test(lb)&&!pi.test(r.c)&&(r.d-=65,R(B,"score\x3d"+r.d+": has first|last but no next regex"));if(si.test(lb)||mi.test(lb))r.d-=50,R(B,"score\x3d"+r.d+": has neg or extra regex");ti.test(lb)&&(r.d-=200,R(B,"score\x3d"+r.d+": has opp of next regex"));Ud=Wd=!1;for(cc=y(B);cc&&(!Wd||!Ud);)dc=(cc.className||"")+" "+cc.id,!Wd&&qi.test(dc)&&(r.d+=25,Wd=!0,R(B,"score\x3d"+r.d+": posParent - "+dc)),Ud||!si.test(dc)||ui.test(dc)||(r.d-=25,Ud=!0,R(B,"score\x3d"+r.d+": negParent - "+
dc)),cc=y(cc);if(vi.test(Y)||qi.test(Y))r.d+=25,R(B,"score\x3d"+r.d+": has paging info");mi.test(Y)&&(r.d-=15,R(B,"score\x3d"+r.d+": has extra regex"));10<mb.length&&(r.d-=mb.length,R(B,"score\x3d"+r.d+": text too long"));ac=wi(mb);0<ac&&(1==ac?r.d-=10:r.d+=0>10-ac?0:10-ac,R(B,"score\x3d"+r.d+": linktxt is a num ("+ac+")"));for(var xb=e,yb=Y,kk=B,Ia=void 0,$d=void 0,ae=void 0,Ia=pg.length;Ia<gd(xb.length,yb.length)&&xb.charCodeAt(Ia)==yb.charCodeAt(Ia);Ia++);xb=xb.substr(Ia,xb.length-Ia);yb=yb.substr(Ia,
yb.length-Ia);R(kk,"remains: "+xb+", "+yb);$d=wi(yb);ae=wi(xb);R(kk,"remains: "+ae+", "+$d);(rg=0<ae&&0<$d?cd($d-ae):null)&&1==rg.a&&(r.d+=25,R(B,"score\x3d"+r.d+": diff \x3d "+rg))}else R(B,"ignored: no number beyond folder url "+Ga);else R(B,"ignored: invisible");else R(B,"ignored: not prefix + num");Ha=null;if(0!=Xd.a.b)for(ug=Pe(new Re(Xd.a));He(ug.a);)Vd=Ie(ug.a).W(),50<=Vd.d&&(!Ha||Ha.d<Vd.d)&&(Ha=Vd);bc=null;Ha&&(bc=Ha.a.replace(RegExp("\\/$","gi"),""),R(vb[Ha.b],"found: score\x3d"+Ha.d+", txt\x3d["+
Ha.c+"], "+bc));if(3<=P){var Qc,be,nb,Rc,ce;Q("numLinks\x3d"+vb.length+", found next: "+(null!=bc?bc:"null"));for(Qc=0;Qc<vb.length;Qc++){be=vb[Qc];nb=be.innerText;ce=md(nb,"\\s+");nb="";for(Rc=0;Rc<ce.length;Rc++)nb+=ce[Rc],Rc<ce.length-1&&(nb+=" ");Q(Qc+")"+be.href+", txt\x3d["+nb+"], dbg\x3d["+ye(ii,be)+"]")}}vd=bc;if(null!=vd){if(void 0==vd)throw new TypeError;ud[1]=vd}if(void 0==ud)throw new TypeError;f[3]=ud;xi(g,p,"Pagination");var T=c.f,zb,ob,de,ee,Ab,Bb,Cg,la,Dg,Eg,Fg;la=(Dg={},Dg[9]=[],
Dg);var fe,ge;ge=!1;for(fe=0;fe<T.a.b.length&&!ge;fe++)ge=J(T.a,fe).wb();if(!ge){var lk=vh(T);if(void 0==lk)throw new TypeError;la[1]=lk;var Gg,he,ie;ie="";for(he=0;he<T.a.b.length&&!ie.length;he++)ie=J(T.a,he).ub();Gg=ie;if(void 0==Gg)throw new TypeError;la[2]=Gg;var Hg,je,ke;ke="";for(je=0;je<T.a.b.length&&!ke.length;je++)ke=J(T.a,je).vb();Hg=ke;if(void 0==Hg)throw new TypeError;la[3]=Hg;var Ig,le,me;le="";for(me=0;me<T.a.b.length&&!le.length;me++)le=J(T.a,me).qb();Ig=le;if(void 0==Ig)throw new TypeError;
la[4]=Ig;var Jg,ne,oe;oe="";for(ne=0;ne<T.a.b.length&&!oe.length;ne++)oe=J(T.a,ne).sb();Jg=oe;if(void 0==Jg)throw new TypeError;la[5]=Jg;var Kg,pe,qe;pe="";for(qe=0;qe<T.a.b.length&&!pe.length;qe++)pe=J(T.a,qe).pb();Kg=pe;if(void 0==Kg)throw new TypeError;la[6]=Kg;var Lg,re,se;re="";for(se=0;se<T.a.b.length&&!re.length;se++)re=J(T.a,se).ob();Lg=re;if(void 0==Lg)throw new TypeError;la[7]=Lg;var te,ue;te=null;for(ue=0;ue<T.a.b.length&&!te;ue++)te=J(T.a,ue).nb();if(zb=te){ob=(Eg={},Eg[5]=[],Eg);var mk=
zb.d;if(void 0==mk)throw new TypeError;ob[1]=mk;var nk=zb.c;if(void 0==nk)throw new TypeError;ob[2]=nk;var ok=zb.b;if(void 0==ok)throw new TypeError;ob[3]=ok;var pk=zb.e;if(void 0==pk)throw new TypeError;ob[4]=pk;for(ee=0;ee<zb.a.length;ee++)ob[5].push(zb.a[ee]);if(void 0==ob)throw new TypeError;la[8]=ob}var ve,we;we=null;for(ve=0;ve<T.a.b.length&&!(we=J(T.a,ve).rb(),0<we.length);ve++);Cg=we;for(de=0;de<Cg.length;de++){Ab=Cg[de];Bb=(Fg={},la[9].push(Fg),Fg);var qk=Ab.e;if(void 0==qk)throw new TypeError;
Bb[1]=qk;var rk=Ab.c;if(void 0==rk)throw new TypeError;Bb[2]=rk;var sk=Ab.d;if(void 0==sk)throw new TypeError;Bb[3]=sk;var tk=Ab.a;if(void 0==tk)throw new TypeError;Bb[4]=tk;var uk=Ab.f;if(void 0==uk)throw new TypeError;Bb[5]=uk;var vk=Ab.b;if(void 0==vk)throw new TypeError;Bb[6]=vk}}if(void 0==la)throw new TypeError;f[5]=la;var wk=O()-l;if(void 0==wk)throw new TypeError;p[5]=wk;if(void 0==p)throw new TypeError;f[6]=p;var xk=c.d;if(void 0==xk)throw new TypeError;f[8]=xk;d=($i={},$i);var yk=(aj=yi,
yi="",aj);if(void 0==yk)throw new TypeError;d[1]=yk;if(void 0==d)throw new TypeError;f[7]=d;return f}k(158,1,{},function(){});s(158);function zi(a){var b;for(b=new L;a;)b.b[b.b.length]=a,a=a.parentNode;return b}function O(){return window.performance?window.performance.now():Date.now()}function Ai(a,b){var c,d;if(null==a)return!1;c=$doc.createElement("a");c.href=a;c=xc(c,"host");d=("."+b).length;return("."+c).substr(("."+c).length-d,d)==="."+b}
function ki(a){var b;b=getComputedStyle(a,null);a=parseFloat(b.opacity);return!("none"===b.display||"hidden"===b.visibility||0==a)}function Bi(a){var b,c,d;b=a.getElementsByTagName("A");for(c=0;c<b.length;c++)d=b[c],d.href.length&&(d.href=d.href);d=a.getElementsByTagName("VIDEO");for(b=0;b<d.length;b++)c=d[b],c.poster.length&&(c.poster=c.poster);Ci(a);b=a.querySelectorAll("IMG[SRCSET]");for(a=0;a<b.length;a++)b[a].removeAttribute("srcset")}
function Ci(a){a=a.querySelectorAll("img,source,track,video");for(var b in a)a[b].src&&(a[b].src=a[b].src)}function Di(a){var b,c,d,e;if(null==a||!a.length)return new Ef;e=new Ef;a=md(a,"\x26");for(c=0;c<a.length;c++);c=0;for(d=a.length;c<d;++c)if(b=a[c],b=md(b,"\x3d"),1<b.length){var f=e,g=b[0];if(null==b[1])throw new hd("encodedURL cannot be null");H(f,g,decodeURI(b[1]))}return e}
function Ei(a){var b;switch(a.nodeType){case 1:a.hasAttribute("id")&&a.removeAttribute("id");case 9:for(b=0;b<a.childNodes.length;b++)Ei(a.childNodes[b])}}function Fi(a){this.a=a}k(81,1,{},Fi);_.lb=function(){};_.mb=function(a){switch(a.nodeType){case 3:return K(this.a,a),!1;case 1:if(!ki(a))return!1;K(this.a,a);return!0;default:return!1}};s(81);
function Dh(a,b){var c,d;if(a.a.mb(b)){if(d=b.firstChild)for(;d!=b;){c=!1;if(a.a.mb(d)){if(c=d.firstChild){d=c;continue}c=!0}for(;d!=b;){c&&a.a.lb(d);if(c=d.nextSibling){d=c;break}d=d.parentNode;c=!0}}a.a.lb(b)}}function Eh(a){this.a=a}k(43,1,{},Eh);s(43);function Gi(a){var b;a.b="";(b=a.j.querySelector(".byline-name"))&&(a.b=b.textContent)}function Hi(a){this.j=a;this.a=a.getElementsByTagName("META")}k(96,1,{},Hi);
_.nb=function(){var a,b;a=new Ii;if(null==this.d){var c;this.d="";if(b=this.j.querySelector(".dateline"))this.d=b.textContent;else for(b=0;b<this.a.length;b++)if(c=this.a[b],D(c.name,"displaydate")){this.d=c.content;break}}a.d=this.d;b=(null==this.b&&Gi(this),this.b);a.a=b.length?z(Jb(m,1),da,2,4,[b]):C(m,2,0,4);return a};_.ob=function(){return null==this.b&&Gi(this),this.b};
_.pb=function(){if(null==this.c){var a,b;this.c="";for(a=0;a<this.a.length;a++)if(b=this.a[a],D(b.name,"copyright")){this.c=b.content;break}}return this.c};_.qb=function(){return""};
_.rb=function(){if(!this.f){var a,b,c,d,e;this.f=new L;a=this.j.getElementsByTagName("IMG");for(c=0;c<a.length;c++){e=a[c];var f=d=b=void 0,g=void 0;b=void 0;b=y(e);if(D("FIGURE",b.tagName)){if(d=b.getElementsByTagName("FIGCAPTION"),g=d.length,b="",0<g&&2>=g)for(f=0;f<g&&!b.length;f++)b=d[f].innerText}else b="";(d=null!=b&&b.length)||(d=d=void 0,d=e.width,400>d?d=!1:(d/=e.height,d=1.3<=d&&3>=d));d&&(d=new Ji,d.e=e.src,d.a=b,d.f=e.width,d.b=e.height,K(this.f,d))}}return lf(this.f,C(Ki,19,this.f.b.length,
0))};_.sb=function(){if(null==this.i){var a,b,c;this.i="";a=this.j.getElementsByTagName("*");for(c=0;c<a.length&&!this.i.length;c++)b=a[c],this.i=x(b,"publisher"),!this.i.length&&(this.i=x(b,"source_organization"))}return this.i};_.tb=function(){if(null==this.k){var a,b;this.k="";if(0!=this.a.length&&(a=this.j.getElementsByTagName("TITLE"),0!=a.length))for(a=0;a<this.a.length;a++)if(b=this.a[a],D(b.name,"title")){this.k=b.content;break}}return this.k};_.ub=function(){return""};_.vb=function(){return""};
_.wb=function(){if(!this.e){var a,b;this.e=!0;for(a=0;a<this.a.length;a++)if(b=this.a[a],D(b.name,"IE_RM_OFF")){this.g=D(b.content,"true");break}}return this.g};_.a=null;_.b=null;_.c=null;_.d=null;_.e=!1;_.f=null;_.g=!1;_.i=null;_.j=null;_.k=null;s(96);function wi(a){return parseInt(a,10)|0}function xi(a,b,c){var d;if(b){b=(d={},b[6].push(d),d);if(void 0==c)throw new TypeError;b[1]=c;a=O()-a;if(void 0==a)throw new TypeError;b[2]=a}}
function Q(a){null==a&&(a="");-1==a.indexOf("[0;")&&-1==a.indexOf("[1;")||(a+="\u001b[0m");Li||null==$wnd.console||"function"!=typeof $wnd.console.log&&"object"!=typeof $wnd.console.log||$wnd.console.log(a);yi+=a+"\n"}var P=0,yi="",Li=!1;function vh(a){var b,c;c="";for(b=0;b<a.a.b.length&&!c.length;b++)c=J(a.a,b).tb();return c}
function yh(a,b){var c,d;this.b=b;this.a=new L;d=O();var e=this.b;Mi();var f,g;try{g=O(),f=new Ni(a,e),xi(g,e,"OpenGraphProtocolParser.parse"),c=f}catch(l){if(l=lc(l),n(l,7))c=null;else throw mc(l);}c&&K(this.a,c);xi(d,this.b,"OpenGraphProtocolParser");d=O();K(this.a,new Oi(a,this.b));xi(d,this.b,"SchemaOrgParserAccessor");d=O();K(this.a,new Hi(a));xi(d,this.b,"IEReadingViewParser")}k(83,1,{},yh);s(83);function Ii(){}k(44,1,{},Ii);_.a=null;_.b="";_.c="";_.d="";_.e="";s(44);function Ji(){}
k(19,1,{19:1},Ji);_.a="";_.b=0;_.c="";_.d="";_.e="";_.f=0;var Ki=s(19);function Pi(a){this.b=new Qi(a);this.a=new L;this.d=new L}k(145,1,{},Pi);_.lb=function(){this.a.U(this.a.b.length-1);this.d.U(this.d.b.length-1)};
_.mb=function(a){if(!this.b.a)return!1;K(this.a,a);K(this.d,null);if(1==this.d.b.length){this.c=new Ri(a);var b=this.d,c=this.c;w(0,b.b.length);b.b[0]=c}if(Si(this.b,a))for(a=0;a<this.a.b.length;a++)if(null==J(this.d,a)){var b=this.d,c=a,d=new Ri(J(this.a,a));w(c,b.b.length);b.b[c]=d;b=J(this.d,a-1);c=J(this.d,a);Wg(b.a,c)}return!0};s(145);function Ti(a){var b,c;c=a.b.cloneNode(!1);for(a=ef(a.a,0);a.b!=a.d.c;)b=(u(a.b!=a.d.c),a.c=a.b,a.b=a.b.a,++a.a,a.c.c),b=Ti(b),c.appendChild(b);return c}
function Ui(a){var b,c;c=a.b.cloneNode(!1);1==a.b.nodeType&&(b=getComputedStyle(a.b,null).direction,!b.length&&(b="auto"),c.setAttribute("dir",b));for(a=ef(a.a,0);a.b!=a.d.c;)b=(u(a.b!=a.d.c),a.c=a.b,a.b=a.b.a,++a.a,a.c.c),b=Ui(b),c.appendChild(b);return c}function Ri(a){this.b=a;this.a=new Zg}k(51,1,{},Ri);s(51);function Mi(){Mi=h;Vi=RegExp("((\\w+):\\s+(http:\\/\\/ogp.me\\/ns(\\/\\w+)*#))\\s*","gi");Wi=/^xmlns:(\w+)/i;Xi=/^http:\/\/ogp.me\/ns(\/\w+)*#/i}
function Yi(a,b,c){null!=c&&c.length?(c=c.substr(1,c.length-1),"profile"===c?rf(a.c,(fj(),gj),b):"article"===c&&rf(a.c,(fj(),ij),b)):rf(a.c,(fj(),jj),b)}
function Ni(a,b){var c,d;this.b=new kj;this.d=new lj;this.a=new mj;this.e=z(Jb(nj,1),da,9,0,[new S("title",(fj(),jj),null),new S("type",jj,null),new S("url",jj,null),new S("description",jj,null),new S("site_name",jj,null),new S("image",jj,this.b),new S("image:",jj,this.b),new S("first_name",gj,this.d),new S("last_name",gj,this.d),new S("section",ij,this.a),new S("published_time",ij,this.a),new S("modified_time",ij,this.a),new S("expiration_time",ij,this.a),new S("author",ij,this.a)]);this.f=new Ef;
this.c=new uf(oj);this.g=b;d=O();var e,f,g;c="";D("HTML",a.tagName)&&(c=x(a,"prefix"));c.length||(g=a.getElementsByTagName("HEAD"),1==g.length&&(c=x(g[0],"prefix")));if(c.length)for(Vi.lastIndex=0;;){g=Vi.exec(c);if(!g)break;Yi(this,g[2],g[4])}else for(c=a.attributes,g=0;g<c.length;g++)if(f=c[g],e=f.nodeName.toLowerCase(),e=Wi.exec(e))f=f.nodeValue,(f=Xi.exec(f))&&Yi(this,e[1],f[1]);null==pf(this.c,(fj(),jj))&&rf(this.c,jj,"og");null==pf(this.c,gj)&&rf(this.c,gj,"profile");null==pf(this.c,ij)&&rf(this.c,
ij,"article");xi(d,this.g,"OpenGraphProtocolParser.findPrefixes");d=O();var l,p;e="";for(g=new xf((new wf(this.c)).a);zf(g.a);)c=(g.b=Af(g.a),new Bf(g.c,g.b)),e+='meta[property^\x3d"'+c.b.b[c.a.b]+'"],';e=e.substr(0,e.length-1-0);c=a.querySelectorAll(e);for(g=0;g<c.length;g++)for(f=c[g],p=x(f,"property").toLowerCase(),e=0;e<this.e.length;e++){l=pf(this.c,this.e[e].c)+":";var t=l+this.e[e].a;p.substr(0,t.length)===t&&(p=nd(p,l.length),l=!0,this.e[e].b&&(l=this.e[e].b.xb(p,f.content,this.f)),l&&H(this.f,
this.e[e].a,f.content))}xi(d,this.g,"OpenGraphProtocolParser.parseMetaTags");d=O();c=this.b;if(0!=c.a.b.length)for(g=c.a.b.length-1;0<=g;g--)e=J(c.a,g)[0],null!=e&&e.length||c.a.U(g);xi(d,this.g,"OpenGraphProtocolParser.imageParser.verify");d=O();c=pf(this.c,jj)+":";if(!(F(this.f,"title")?G(this.f,"title"):"").length)throw new Lb('Required "'+c+'title" property is missing.');if(!(F(this.f,"type")?G(this.f,"type"):"").length)throw new Lb('Required "'+c+'type" property is missing.');if(!(F(this.f,"url")?
G(this.f,"url"):"").length)throw new Lb('Required "'+c+'url" property is missing.');if(0==rj(this.b).length)throw new Lb('Required "'+c+'image" property is missing.');xi(d,this.g,"OpenGraphProtocolParser.checkRequired")}k(91,1,{},Ni);
_.nb=function(){var a;a=new Ii;a.d=F(this.f,"published_time")?G(this.f,"published_time"):"";a.c=F(this.f,"modified_time")?G(this.f,"modified_time"):"";a.b=F(this.f,"expiration_time")?G(this.f,"expiration_time"):"";a.e=F(this.f,"section")?G(this.f,"section"):"";var b;b=this.a;b=lf(b.a,C(m,2,b.a.b.length,4));a.a=b;return a.e.length||a.d.length||a.c.length||a.b.length||0!=a.a.length?a:null};
_.ob=function(){var a;var b=this.f;this.d.b?(a=b.c.db("first_name"),null==a&&(a=""),b=b.c.db("last_name"),null!=b&&a.length&&b.length&&(a+=" "),a+=b):a="";return a};_.pb=function(){return""};_.qb=function(){return F(this.f,"description")?G(this.f,"description"):""};_.rb=function(){return rj(this.b)};_.sb=function(){return F(this.f,"site_name")?G(this.f,"site_name"):""};_.tb=function(){return F(this.f,"title")?G(this.f,"title"):""};
_.ub=function(){var a;a=F(this.f,"type")?G(this.f,"type"):"";return D(a,"article")?"Article":""};_.vb=function(){return F(this.f,"url")?G(this.f,"url"):""};_.wb=function(){return!1};var Wi,Xi,Vi;s(91);function mj(){this.b=!1;this.a=new L}k(94,1,{},mj);_.xb=function(a,b,c){this.b||(c=c.c.db("type"),this.b=null!=c&&D(c,"article"));return this.b?"author"===a?(K(this.a,b),!1):!0:!1};_.b=!1;s(94);
function rj(a){var b,c,d,e;e=C(Ki,19,a.a.b.length,0);for(b=0;b<a.a.b.length;b++)c=J(a.a,b),d=new Ji,e[b]=d,d.e=null!=c[1]&&c[1].length?c[1]:c[0],null!=c[2]&&(d.c=c[2]),null!=c[3]&&(d.d=c[3]),null!=c[4]&&(d.f=wi(c[4])),null!=c[5]&&(d.b=wi(c[5]));return e}function kj(){this.b=z(Jb(m,1),da,2,4,"image image:url image:secure_url image:type image:width image:height".split(" "));this.a=new L}k(92,1,{},kj);
_.xb=function(a,b){var c,d;if("image"===a)d=C(m,2,this.b.length,4),d[0]=b,K(this.a,d);else for(0==this.a.b.length?(d=C(m,2,this.b.length,4),K(this.a,d)):d=J(this.a,this.a.b.length-1),c=1;c<this.b.length;c++)if(a===this.b[c]){d[c]=b;break}return!1};s(92);function fj(){fj=h;jj=new sj("OG",0);gj=new sj("PROFILE",1);ij=new sj("ARTICLE",2)}function sj(a,b){this.a=a;this.b=b}k(28,11,{3:1,15:1,11:1,28:1},sj);var ij,jj,gj,oj=Hb(28,function(){fj();return z(Jb(oj,1),da,28,0,[jj,gj,ij])});
function lj(){this.b=this.a=!1}k(93,1,{},lj);_.xb=function(a,b,c){this.a||(a=c.c.db("type"),this.b=null!=a&&D(a,"profile"),this.a=!0);return this.b};_.a=!1;_.b=!1;s(93);function S(a,b,c){this.a=a;this.c=b;this.b=c}k(9,1,{9:1},S);_.a=null;_.b=null;var nj=s(9);function Si(a,b){if(b!=a.a)return!1;a.a=a.b.Q()?a.b.R():null;return!0}function Qi(a){this.b=a.D();a.I()||(this.a=this.b.R())}k(73,1,{},Qi);s(73);
function hi(){hi=h;pi=RegExp("(next|weiter|continue|\x3e([^\\|]|$)|\u00bb([^\\|]|$))","i");ti=RegExp("(prev|early|old|new|\x3c|\u00ab)","i");ui=/article|body|content|entry|hentry|main|page|pagination|post|text|blog|story/i;si=RegExp("combx|comment|com-|contact|foot|footer|footnote|masthead|media|meta|outbrain|promo|related|shoutbox|sidebar|sponsor|shopping|tags|tool|widget","i");mi=/print|archive|comment|discuss|e[\-]?mail|share|reply|all|login|sign|single|as one|article/i;qi=/pag(e|ing|inat)/i;vi=
/p(a|g|ag)?(e|ing|ination)?(=|\/)[0-9]{1,2}$/i;ri=/(first|last)/i;li=/\/?(#.*)?$/;ni=/\d/;ii=new Ef}function R(a,b){var c;3>P||(c="",Zd(ii,a)&&(c=ye(ii,a)),!c.length||(c+="; "),ze(ii,a,c+b))}function ji(a){var b,c;c=$doc.implementation.createHTMLDocument();b=c.createElement("base");b.href=a;(c.head||c.getElementsByTagName("head")[0]).appendChild(b);a=c.createElement("a");c.body.appendChild(a);return a}var mi,ri,li,vi,si,pi,ni,qi,ui,ti,ii;function oi(a,b,c){this.b=a;this.d=0;this.c=b;this.a=c}
k(82,1,{},oi);_.b=-1;_.d=0;s(82);
function tj(){tj=h;wj=new Ef;H(wj,"http://schema.org/ImageObject",(U(),xj));H(wj,"http://schema.org/Article",yj);H(wj,"http://schema.org/BlogPosting",yj);H(wj,"http://schema.org/NewsArticle",yj);H(wj,"http://schema.org/ScholarlyArticle",yj);H(wj,"http://schema.org/TechArticle",yj);H(wj,"http://schema.org/Person",zj);H(wj,"http://schema.org/Organization",Aj);H(wj,"http://schema.org/Corporation",Aj);H(wj,"http://schema.org/EducationalOrganization",Aj);H(wj,"http://schema.org/GovernmentOrganization",Aj);
H(wj,"http://schema.org/NGO",Aj);W=new Ef;H(W,"IMG","SRC");H(W,"AUDIO","SRC");H(W,"EMBED","SRC");H(W,"IFRAME","SRC");H(W,"SOURCE","SRC");H(W,"TRACK","SRC");H(W,"VIDEO","SRC");H(W,"A","HREF");H(W,"LINK","HREF");H(W,"AREA","HREF");H(W,"META","CONTENT");H(W,"TIME","DATETIME");H(W,"OBJECT","DATA");H(W,"DATA","VALUE");H(W,"METER","VALUE")}function Cj(a){var b,c,d;b=new L;for(c=0;c<a.c.b.length;c++)d=J(a.c,c),d.c==(U(),yj)&&K(b,d);return b}
function Dj(a,b,c){var d,e,f,g,l;e=null;d=b.hasAttribute("ITEMSCOPE")&&b.hasAttribute("ITEMTYPE");if(c){var p;f=x(b,"ITEMPROP");f.length?(p=md(f,"\\s+"),f=0<p.length?p:z(Jb(m,1),da,2,4,[f])):f=C(m,2,0,4)}else f=C(m,2,0,4);if(d){a:{var t;switch((t=x(b,"ITEMTYPE"),F(wj,t)?G(wj,t):(U(),Ej)).b){case 0:e=new Jj;break;case 1:e=new Kj;break;case 2:e=new Lj;break;case 3:e=new Mj;break;case 4:e=new Wj;break;default:e=null;break a}}!e||e.c==(U(),Ej)||c&&c.c==(U(),Ej)&&0!=f.length||(K(a.c,e),ze(a.b,b,e))}if(0<
f.length&&c.c!=(U(),Ej)&&(!e||e.c!=(U(),Ej)))for(a=0;a<f.length;a++)e?F(c.a,f[a])&&H(c.a,f[a],e):(d=c,t=f[a],p=(g="",l=b.tagName,F(W,l)&&(g=x(b,G(W,l))),!g.length&&(g=b.textContent),g),F(d.b,t)&&!G(d.b,t).length&&H(d.b,t,p))}
function bk(a,b){tj();var c;this.c=new L;this.b=new Ef;this.d=b;c=O();var d,e,f,g,l;d=a.querySelectorAll("[ITEMPROP],[ITEMSCOPE]");Dj(this,a,null);for(f=0;f<d.length;f++){for(var p=e=d[f],t=void 0,v=void 0,v=null,t=e;t;){t=y(t);if(!t)break;if(t.hasAttribute("ITEMSCOPE")&&t.hasAttribute("ITEMTYPE")){Zd(this.b,t)&&(v=ye(this.b,t));break}}Dj(this,p,v)}d=a.querySelectorAll("A[rel\x3dauthor],LINK[rel\x3dauthor]");for(f=0;f<d.length;f++)e=d[f],!this.a.length&&(this.a=(g="",l=e.tagName,(D(l,"A")||D(l,"LINK"))&&
D(x(e,"REL"),"author")&&(g=e.textContent),g));xi(c,this.d,"SchemaOrgParser.parse")}function dk(a,b){tj();var c;c=a;a.length&&b.length&&(c+=" ");return c+b}k(103,1,{},bk);_.a="";var W,wj;s(103);function ek(a,b){return F(a.b,b)?G(a.b,b):""}function fk(a){this.c=a;this.b=new Ef;this.a=new Ef;H(this.b,"name","");H(this.b,"url","");H(this.b,"description","");H(this.b,"image","")}k(29,1,{});s(29);
function gk(a,b){var c,d,e,f;c=F(a.b,b)?G(a.b,b):"";if(c.length)return c;(d=F(a.a,b)?G(a.a,b):null)&&(d.c==(U(),zj)?c=(e=F(d.b,"name")?G(d.b,"name"):"",e.length?e:dk(F(d.b,"givenName")?G(d.b,"givenName"):"",F(d.b,"familyName")?G(d.b,"familyName"):"")):d.c==Aj&&(c=(f=F(d.b,"name")?G(d.b,"name"):"",f.length?f:F(d.b,"legalName")?G(d.b,"legalName"):"")));return c}
function Kj(){fk.call(this,(U(),yj));H(this.b,"headline","");H(this.b,"publisher","");H(this.b,"copyrightHolder","");H(this.b,"copyrightYear","");H(this.b,"dateModified","");H(this.b,"datePublished","");H(this.b,"author","");H(this.b,"creator","");H(this.b,"articleSection","");ze(this.a,"publisher",null);ze(this.a,"copyrightHolder",null);ze(this.a,"author",null);ze(this.a,"creator",null);ze(this.a,"associatedMedia",null);ze(this.a,"encoding",null)}k(105,29,{},Kj);s(105);
function Jj(){fk.call(this,(U(),xj));H(this.b,"contentUrl","");H(this.b,"encodingFormat","");H(this.b,"caption","");H(this.b,"representativeOfPage","");H(this.b,"width","");H(this.b,"height","")}k(104,29,{},Jj);s(104);function Mj(){fk.call(this,(U(),Aj));H(this.b,"legalName","")}k(107,29,{},Mj);s(107);function Lj(){fk.call(this,(U(),zj));H(this.b,"familyName","");H(this.b,"givenName","")}k(106,29,{},Lj);s(106);
function U(){U=h;xj=new hk("IMAGE",0);yj=new hk("ARTICLE",1);zj=new hk("PERSON",2);Aj=new hk("ORGANIZATION",3);Ej=new hk("UNSUPPORTED",4)}function hk(a,b){this.a=a;this.b=b}k(22,11,{3:1,15:1,11:1,22:1},hk);var yj,xj,Aj,zj,Ej,ik=Hb(22,function(){U();return z(Jb(ik,1),da,22,0,[xj,yj,zj,Aj,Ej])});function Wj(){fk.call(this,(U(),Ej))}k(108,29,{},Wj);s(108);function Oi(a,b){this.a=new bk(a,b)}k(95,1,{},Oi);
_.nb=function(){var a;a=Cj(this.a);if(0==a.b.length)a=null;else{a=(w(0,a.b.length),a.b[0]);var b,c;b=new Ii;b.d=F(a.b,"datePublished")?G(a.b,"datePublished"):"";b.c=F(a.b,"dateModified")?G(a.b,"dateModified"):"";b.e=F(a.b,"articleSection")?G(a.b,"articleSection"):"";c=gk(a,"author");!c.length&&(c=gk(a,"creator"));b.a=c.length?z(Jb(m,1),da,2,4,[c]):C(m,2,0,4);a=b}return a};
_.ob=function(){var a,b;b="";a=Cj(this.a);0!=a.b.length&&(a=(w(0,a.b.length),a.b[0]),b=gk(a,"author"),!b.length&&(b=gk(a,"creator")));return b.length?b:this.a.a};_.pb=function(){var a;a=Cj(this.a);0==a.b.length?a="":(a=(w(0,a.b.length),a.b[0]),a=dk(F(a.b,"copyrightYear")?G(a.b,"copyrightYear"):"",gk(a,"copyrightHolder")),a=a.length?"Copyright "+a:a);return a};_.qb=function(){var a;a=Cj(this.a);return 0==a.b.length?"":ek((w(0,a.b.length),a.b[0]),"description")};
_.rb=function(){var a,b,c,d,e,f,g,l;g=new L;b=Cj(this.a);c=null;for(d=0;d<b.b.length;d++){a=(w(d,b.b.length),b.b[d]);if(!c&&(c=(e=F(a.a,"associatedMedia")?G(a.a,"associatedMedia"):null,!e&&(e=F(a.a,"encoding")?G(a.a,"encoding"):null),e&&e.c==(U(),xj)?e:null)))continue;var p=f=void 0,p=F(a.b,"image")?G(a.b,"image"):"";p.length?(f=new Ji,f.e=p,a=f):a=null;a&&(g.b[g.b.length]=a)}d=this.a;b=new L;for(a=0;a<d.c.b.length;a++)e=J(d.c,a),e.c==(U(),xj)&&K(b,e);d=!1;for(e=0;e<b.b.length;e++)f=(w(e,b.b.length),
b.b[e]),a=(l=new Ji,l.e=F(f.b,"contentUrl")?G(f.b,"contentUrl"):"",!l.e.length&&(l.e=F(f.b,"url")?G(f.b,"url"):""),l.d=F(f.b,"encodingFormat")?G(f.b,"encodingFormat"):"",l.a=F(f.b,"caption")?G(f.b,"caption"):"",l.f=wi(F(f.b,"width")?G(f.b,"width"):""),l.b=wi(F(f.b,"height")?G(f.b,"height"):""),l),f==c||!d&&D(F(f.b,"representativeOfPage")?G(f.b,"representativeOfPage"):"","true")?(d=!0,wc(0,g.b.length),g.b.splice(0,0,a)):g.b[g.b.length]=a;return lf(g,C(Ki,19,g.b.length,0))};
_.sb=function(){var a,b;b="";a=Cj(this.a);0!=a.b.length&&(a=(w(0,a.b.length),a.b[0]),b=gk(a,"publisher"),!b.length&&(b=gk(a,"copyrightHolder")));return b};_.tb=function(){var a,b,c;c="";a=Cj(this.a);for(b=0;b<a.b.length&&!c.length;b++)c=ek((w(b,a.b.length),a.b[b]),"headline");for(b=0;b<a.b.length&&!c.length;b++)c=ek((w(b,a.b.length),a.b[b]),"name");return c};_.ub=function(){return 0==Cj(this.a).b.length?"":"Article"};
_.vb=function(){var a;a=Cj(this.a);return 0==a.b.length?"":ek((w(0,a.b.length),a.b[0]),"url")};_.wb=function(){return!1};s(95);function wh(a){return(a=a.match(/(\S*[\w\u00C0-\u1FFF\u2C00-\uD7FF]\S*)/g))?a.length:0}
function jk(){jk=h;zk=new Ef;H(zk,"COLGROUP",(Wc(),Xc));H(zk,"COL",Xc);H(zk,"TH",Zc);Ak=new Ef;H(Ak,"EMBED",Xc);H(Ak,"OBJECT",Xc);H(Ak,"APPLET",Xc);H(Ak,"IFRAME",Xc);Bk=new Ff;M(Bk,"grid");M(Bk,"treegrid");Ck=new Ff;M(Ck,"gridcell");M(Ck,"columnheader");M(Ck,"row");M(Ck,"rowgroup");M(Ck,"rowheader");Dk=new Ff;M(Dk,"application");M(Dk,"banner");M(Dk,"complementary");M(Dk,"contentinfo");M(Dk,"form");M(Dk,"main");M(Dk,"navigation");M(Dk,"search")}
function Ek(a,b){var c,d,e;for(d=new I(a);d.b<d.d.J();)if(c=(u(d.b<d.d.J()),d.d.T(d.c=d.b++)),e=c.tagName,null==e?xe(b.a,null):void 0!==b.c.db(e))return!(null==e?Hd(xe(b.a,null)):b.c.db(e)).a||Fk(c);return!1}function Fk(a){a=a.innerText;return!!a.length&&!!/\S/.test(a)}function X(a,b,c){2<=P&&Q(a+b+" -\x3e "+c);return c}
function Gk(a){jk();var b,c,d,e,f,g,l,p;Hk();for(f=y(a);f;){if(D("INPUT",f.tagName)||D(x(f,"contenteditable"),"true"))return X(Ik,"",(Z(),Jk));f=y(f)}f=x(a,"role").toLowerCase();if("presentation"===f)return X(Kk,"_"+f,(Z(),Jk));if(N(Bk,f)||N(Dk,f))return X(Kk,"_"+f,(Z(),Lk));f=new L;g=a.getElementsByTagName("*");if(0<a.getElementsByTagName("TABLE").length)for(e=0;e<g.length;e++)for(c=g[e],d=y(c);d;){if(D("TABLE",d.tagName)){d==a&&(f.b[f.b.length]=c);break}d=y(d)}else for(e=0;e<g.length;e++)K(f,g[e]);
for(g=new I(f);g.b<g.d.J();)if(b=(u(g.b<g.d.J()),g.d.T(g.c=g.b++)),c=x(b,"role").toLowerCase(),N(Ck,c)||N(Dk,c))return X(Mk,"_"+c,(Z(),Lk));if("0"===x(a,"datatable"))return X(Nk,"",(Z(),Jk));if(0<a.getElementsByTagName("TABLE").length)return X(Ok,"",(Z(),Jk));g=a.rows;if(1>=g.length)return X(Pk,"",(Z(),Jk));c=null;for(d=b=0;d<g.length;d++)e=g[d].cells,e.length>b&&(b=e.length,c=e);d=c;if(!d||1>=d.length)return X(Qk,"",(Z(),Jk));if((c=a.caption)&&Fk(c)||a.tHead||a.tFoot||Ek(f,zk))return X(Rk,"",(Z(),
Lk));c=new L;for(e=new I(f);e.b<e.d.J();)b=(u(e.b<e.d.J()),e.d.T(e.c=e.b++)),D("TD",b.tagName)&&(c.b[c.b.length]=b);for(e=new I(c);e.b<e.d.J();){b=(u(e.b<e.d.J()),e.d.T(e.c=e.b++));if(b.hasAttribute("abbr")||b.hasAttribute("headers")||b.hasAttribute("scope"))return X(Sk,"",(Z(),Lk));b=b.getElementsByTagName("*");if(1==b.length&&D("ABBR",b[0].tagName))return X(Tk,"",(Z(),Lk))}e=a.ownerDocument.documentElement;b=(e.offsetWidth||0)|0;if(0<b&&((a.offsetWidth||0)|0)>0.95*b){p=!1;b=e.getElementsByTagName("META");
for(l=0;l<b.length&&!p;l++)p=b[l],p=D(p.name,"viewport");if(!p)return X(Uk,"",(Z(),Jk))}if(a.hasAttribute("summary"))return X(Vk,"",(Z(),Lk));if(5<=d.length)return X(Wk,"",(Z(),Lk));for(d=new I(c);d.b<d.d.J();)if(b=(u(d.b<d.d.J()),d.d.T(d.c=d.b++)),b=getComputedStyle(b,null).borderStyle,b.length&&"none"!==b&&"hidden"!==b)return X(Xk,"_"+b,(Z(),Lk));l=null;for(b=0;b<g.length;b++)if(d=getComputedStyle(g[b],null).backgroundColor,null==l)l=d;else if(!D(l,d))return X(Yk,"",(Z(),Lk));if(20<=g.length)return X(Zk,
"",(Z(),Lk));if(10>=c.b.length)return X($k,"",(Z(),Jk));if(Ek(f,Ak))return X(al,"",(Z(),Jk));f=(e.offsetHeight||0)|0;return 0<f&&((a.offsetHeight||0)|0)>0.9*f?X(bl,"",(Z(),Jk)):X(cl,"",(Z(),Lk))}var Dk,Ck,Bk,zk,Ak;
function Hk(){Hk=h;Ik=new $("INSIDE_EDITABLE_AREA",0);Kk=new $("ROLE_TABLE",1);Mk=new $("ROLE_DESCENDANT",2);Nk=new $("DATATABLE_0",3);Rk=new $("CAPTION_THEAD_TFOOT_COLGROUP_COL_TH",4);Sk=new $("ABBR_HEADERS_SCOPE",5);Tk=new $("ONLY_HAS_ABBR",6);Uk=new $("MORE_95_PERCENT_DOC_WIDTH",7);Vk=new $("SUMMARY",8);Ok=new $("NESTED_TABLE",9);Pk=new $("LESS_EQ_1_ROW",10);Qk=new $("LESS_EQ_1_COL",11);Wk=new $("MORE_EQ_5_COLS",12);Xk=new $("CELLS_HAVE_BORDER",13);Yk=new $("DIFFERENTLY_COLORED_ROWS",14);Zk=new $("MORE_EQ_20_ROWS",
15);$k=new $("LESS_EQ_10_CELLS",16);al=new $("EMBED_OBJECT_APPLET_IFRAME",17);bl=new $("MORE_90_PERCENT_DOC_HEIGHT",18);cl=new $("DEFAULT",19);dl=new $("UNKNOWN",20)}function $(a,b){this.a=a;this.b=b}k(8,11,{3:1,15:1,11:1,8:1},$);var Sk,Rk,Xk,Nk,cl,Yk,al,Ik,$k,Qk,Pk,bl,Uk,Zk,Wk,Ok,Tk,Mk,Kk,Vk,dl,el=Hb(8,function(){Hk();return z(Jb(el,1),da,8,0,[Ik,Kk,Mk,Nk,Rk,Sk,Tk,Uk,Vk,Ok,Pk,Qk,Wk,Xk,Yk,Zk,$k,al,bl,cl,dl])});function Z(){Z=h;Lk=new fl("DATA",0);Jk=new fl("LAYOUT",1)}
function fl(a,b){this.a=a;this.b=b}k(39,11,{3:1,15:1,11:1,39:1},fl);var Lk,Jk,gl=Hb(39,function(){Z();return z(Jb(gl,1),da,39,0,[Lk,Jk])});function hl(a,b){var c;c=il(b);a.appendChild(c);return c}function il(a){var b;b=a.cloneNode(!1);1==a.nodeType&&(a=getComputedStyle(a,null).direction,!a.length&&(a="auto"),b.setAttribute("dir",a));return b}function jl(a,b){var c;c=a.parentNode;c||(c=il(b),c.appendChild(a));return c}function kl(a){return ci(J(a.j,J(a.i,0).a))}function ll(a,b){return N(a.b,b)}
function Hh(a,b){a.g+="\n";a.g+=b.g;a.d+=b.d;a.e+=b.e;a.c=0==a.d?0:a.e/a.d;a.a|=b.a;hf(a.i,b.i);a.b.G(b.b);a.f=gd(a.f,b.f)}function Oh(a,b){if(b==a.a)return!1;a.a=b;return!0}function ml(a){var b;b="["+(J(a.j,J(a.i,0).a).j+"-"+J(a.j,J(a.i,a.i.b.length-1).a).j+";");b+="tl\x3d"+a.f+";";b+="nw\x3d"+a.d+";";b+="ld\x3d"+a.c+";";b=b+"]\t"+((a.a?"\u001b[0;32mCONTENT":"\u001b[0;35mboilerplate")+"\u001b[0m,");b+="\u001b[1;30m"+td(new th(a.b))+"\u001b[0m";return b+="\n"+a.g}
function Gh(a,b){var c,d;this.j=a;this.i=new L;K(this.i,cd(b));c=J(this.j,b);this.b=(d=c.e,c.e=new Ff,d);this.d=c.i;this.e=c.g;this.f=c.n;this.g=c.o;this.c=0==this.d?0:this.e/this.d}k(50,1,{},Gh);_.tS=function(){return ml(this)};_.a=!1;_.c=0;_.d=0;_.e=0;_.f=0;s(50);function Ih(a){this.a=a}k(59,1,{},Ih);s(59);function nl(){nl=h;ol=new Ff;M(ol,"IMG")}function pl(){nl()}k(109,1,{},pl);_.yb=function(a){var b;N(ol,a.tagName)?(b="","IMG"===a.tagName&&(b=a.src),a=new ql(a,b)):a=null;return a};_.zb=function(){return ol};
var ol;s(109);function rl(){rl=h;sl=new Ff;M(sl,"BLOCKQUOTE");M(sl,"IFRAME")}function tl(a){var b;if(-1==(a.className||"").indexOf("twitter-tweet"))return null;b=a.getElementsByTagName("a");if(0==b.length)return null;b=b[b.length-1];if(!Ai(b.href,"twitter.com"))return null;a:{var c;c=md(xc(b,"pathname"),"/");for(b=c.length-1;0<=b;b--)if(0<c[b].length){b=c[b];break a}b=null}return null==b?null:new ul(a,"twitter",b,null)}
function vl(a){var b;if("IFRAME"!==a.tagName||a.src.length)return null;b=a.contentWindow.document;if(!b)return null;b=b.getElementsByTagName("blockquote");if(1>b.length)return null;b=x(b[0],"data-tweet-id");return b.length?new ul(a,"twitter",b,null):null}function wl(){rl()}k(110,1,{},wl);_.yb=function(a){var b;a&&N(sl,a.tagName)?(b=null,"BLOCKQUOTE"===a.tagName?b=tl(a):"IFRAME"===a.tagName&&(b=vl(a)),b&&2<=P&&(Q("Twitter embed extracted:"),Q("    ID: "+b.b)),a=b):a=null;return a};_.zb=function(){return sl};
var sl;s(110);function xl(){xl=h;yl=new Ff;M(yl,"IFRAME")}function zl(a){var b,c;if(!a||!N(yl,a.tagName))return null;c=a.src;if(!Ai(c,"player.vimeo.com"))return null;b=$doc.createElement("a");b.href=c;c=xc(b,"pathname");b=Di(nd(xc(b,"search"),1));a:{var d;d=md(c,"/");for(c=d.length-1;0<=c&&"video"!==d[c];c--)if(0<d[c].length){c=d[c];break a}c=null}if(null==c)return null;2<=P&&(Q("Vimeo embed extracted:"),Q("    ID:    "+c));return new ul(a,"vimeo",c,b)}function Al(){xl()}k(111,1,{},Al);_.yb=function(a){return zl(a)};
_.zb=function(){return yl};var yl;s(111);function Bl(){Bl=h;Cl=new Ff;M(Cl,"IFRAME")}function Dl(a){var b,c;if(!a||!N(Cl,a.tagName))return null;c=a.src;if(!Ai(c,"youtube.com"))return null;b=$doc.createElement("a");b.href=c;c=xc(b,"pathname");b=Di(nd(xc(b,"search"),1));a:{var d;d=md(c,"/");for(c=d.length-1;0<=c&&"embed"!==d[c];c--)if(0<d[c].length){c=d[c];break a}c=null}if(null==c)return null;2<=P&&(Q("YouTube embed extracted:"),Q("    ID:    "+c));return new ul(a,"youtube",c,b)}
function El(){Bl()}k(112,1,{},El);_.yb=function(a){return Dl(a)};_.zb=function(){return Cl};var Cl;s(112);function Jh(a,b,c){if(!(1>P))if(b){Q("\u001b[0;34m\x3c\x3c\x3c\x3c\x3c "+c+" \x3e\x3e\x3e\x3e\x3e");if(!(1>P)){b="";for(c=new I(a.a);c.b<c.d.J();)a=(u(c.b<c.d.J()),c.d.T(c.c=c.b++)),b+=ml(a)+"\n";Q(b)}Q("\u001b[0;34m\x3c\x3c\x3c\x3c\x3c                \x3e\x3e\x3e\x3e\x3e")}else Q("\u001b[0;31m~~~~~ No Changes: "+c+" ~~~~~")}
function Kh(){Kh=h;Lh=RegExp("(^(comments|\u00a9 reuters|please rate this|post a comment|\\d+\\s+(comments|users responded in))|what you think\\.\\.\\.|add your comment|add comment|reader views|have your say|reader comments|r\u00e4tta artikeln|^thanks for your comments - this feedback is now closed$)","i")}var Lh;function Vh(){Vh=h;Wh=new Fl(!1);Zh=new Fl(!0)}
function Uh(a,b){var c,d,e,f,g;c=b.a;if(2>c.b.length)return!1;d=!1;g=(w(0,c.b.length),c.b[0]);for(f=new Le(c,1);f.b<f.d.J();)c=(u(f.b<f.d.J()),f.d.T(f.c=f.b++)),c.a&&g.a?(e=J(c.j,J(c.i,0).a).j-J(g.j,J(g.i,g.i.b.length-1).a).j-1,1>=e?(e=!0,a.a?g.f!=c.f&&(e=!1):N(c.b,"BOILERPLATE_HEADING_FUSED")&&(e=!1),N(g.b,"STRICTLY_NOT_CONTENT")!=N(c.b,"STRICTLY_NOT_CONTENT")&&(e=!1),N(g.b,"de.l3s.boilerpipe/TITLE")!=N(c.b,"de.l3s.boilerpipe/TITLE")&&(e=!1),!g.a&&N(g.b,"de.l3s.boilerpipe/LI")&&!N(c.b,"de.l3s.boilerpipe/LI")&&
(e=!1),e?(Hh(g,c),Ke(f),d=!0):g=c):g=c):g=c;return d}function Fl(a){this.a=a}k(63,1,{},Fl);_.tS=function(){return sb(Gl),Gl.n+": postFiltering\x3d"+this.a};_.a=!1;var Zh,Wh,Gl=s(63);function Hl(){Hl=h;Nh=RegExp("[\\?\\!\\.\\-\\:]+","g")}function Il(a,b,c){var d,e;e=md(b,c);if(1!=e.length)for(b=0;b<e.length;b++)d=e[b],-1==d.indexOf(".com")&&(c=wh(d),4<=c&&M(a,d))}
function Jl(a,b){var c,d,e,f,g,l;l=md(a,b);if(1==l.length)return null;d=0;e="";for(c=0;c<l.length;c++)if(g=l[c],-1==g.indexOf(".com")&&(f=wh(g),f>d||g.length>e.length))d=f,e=g;return 0==e.length?null:od(e)}
function Mh(a){Hl();var b;if(a)for(this.a=new Ff,a=ef(a,0);a.b!=a.d.c;){b=(u(a.b!=a.d.c),a.c=a.b,a.b=a.b.a,++a.a,a.c.c);var c=void 0;b=id(b);b=jd(b);b=od(b).toLowerCase();0!=b.length&&M(this.a,b)&&(c=Jl(b,"[ ]*[\\|\u00bb|-][ ]*"),null!=c&&M(this.a,c),c=Jl(b,"[ ]*[\\|\u00bb|:][ ]*"),null!=c&&M(this.a,c),c=Jl(b,"[ ]*[\\|\u00bb|:\\(\\)][ ]*"),null!=c&&M(this.a,c),c=Jl(b,"[ ]*[\\|\u00bb|:\\(\\)\\-][ ]*"),null!=c&&M(this.a,c),c=Jl(b,"[ ]*[\\|\u00bb|,|:\\(\\)\\-][ ]*"),null!=c&&M(this.a,c),c=Jl(b,"[ ]*[\\|\u00bb|,|:\\(\\)\\-\u00a0][ ]*"),
null!=c&&M(this.a,c),Il(this.a,b,"[ ]+[\\|][ ]+"),Il(this.a,b,"[ ]+[\\-][ ]+"),M(this.a,ld(b," - [^\\-]+$")),M(this.a,ld(b,"^[^\\-]+ - ")))}else this.a=null}k(113,1,{},Mh);var Nh;s(113);function $h(){$h=h;ai=new Kl(!0)}function Kl(a){this.a=a}k(65,1,{},Kl);_.a=!1;var ai;s(65);function Ll(a,b,c){b=J(a.d,b);c=J(a.d,c);return a.c||(b.nodeType!=c.nodeType?0:1!=b.nodeType||b.nodeName===c.nodeName)?b.parentNode==c.parentNode:!1}
function Sh(a,b){var c,d,e,f,g,l,p,t,v,V;a.g=b.a;if(2>a.g.b.length)return!1;d=a.g;e=$doc.documentElement;l=new L;for(f=0;f<d.b.length;++f){g=f+1==d.b.length?e:kl((w(f+1,d.b.length),d.b[f+1]));0==f?p=e:(p=(w(f-1,d.b.length),d.b[f-1]),p=bi(J(p.j,J(p.i,p.i.b.length-1).a)));v=p;p=kl((w(f,d.b.length),d.b[f]));for(t=p.parentNode;!t.contains(v)&&!t.contains(g);)p=t,t=t.parentNode;l.b[l.b.length]=p}a.d=l;l=C(Ml,0,a.g.b.length,7);t=p=0;d=C(Ml,0,a.g.b.length,7);f=e=0;g=!1;for(v=0;v<a.g.b.length;v++)if(!a.b&&
ll(J(a.g,v),"de.l3s.boilerpipe/TITLE")||!a.a&&ll(J(a.g,v),"de.l3s.boilerpipe/HEADING"))p=t,e=f;else if(J(a.g,v).a&&!ll(J(a.g,v),"STRICTLY_NOT_CONTENT")&&!ll(J(a.g,v),"de.l3s.boilerpipe/TITLE"))for(l[t++]=v,V=e;V<f;V++)c=d[V],v-c>a.e?V==e&&++e:Ll(a,v,c)&&(g=!0,Oh(J(a.g,c),!0),d[V]=d[e++]);else if(J(a.g,v).c<=a.f&&!J(a.g,v).a&&!ll(J(a.g,v),"STRICTLY_NOT_CONTENT")&&!ll(J(a.g,v),"de.l3s.boilerpipe/TITLE")){for(V=p;V<t;V++)if(c=l[V],v-c>a.e)V==p&&++p;else if(Ll(a,v,c)){g=!0;Oh(J(a.g,v),!0);l[V]=l[p++];
break}V==t?d[f++]=v:l[t++]=v}return g}function Nl(a,b,c,d,e){this.b=a;this.a=b;this.c=c;this.f=d;this.e=e}k(115,1,{},Nl);_.a=!1;_.b=!1;_.c=!1;_.e=0;_.f=0;s(115);function Rh(){var a=new Ol;a.a=!0;return a}function Th(a){return new Nl(a.b,a.a,a.c,a.e,a.d)}function Ol(){this.c=this.a=this.b=!1;this.d=this.e=0}k(62,1,{},Ol);_.a=!1;_.b=!1;_.c=!1;_.d=0;_.e=0;s(62);function Xh(){Xh=h;Yh=new Pl("de.l3s.boilerpipe/TITLE")}function Pl(a){this.a=a}k(64,1,{},Pl);var Yh;s(64);
function Ph(){Ph=h;Qh=new Ql(z(Jb(m,1),da,2,4,["STRICTLY_NOT_CONTENT"]))}function Ql(a){this.a=a}k(114,1,{},Ql);var Qh;s(114);
function Rl(a,b){var c,d;d=ki(b);2>P||(c=getComputedStyle(b,null),Q((d?"KEEP ":"SKIP ")+b.tagName+": id\x3d"+b.id+", dsp\x3d"+c.display+", vis\x3d"+c.visibility+", opaq\x3d"+c.opacity));if(!d)return M(a.d,b),!1;if(N(a.b,b.tagName))for(d=new I(a.c);d.b<d.d.J();)if(c=(u(d.b<d.d.J()),d.d.T(d.c=d.b++)),c=c.yb(b))return Sl(a.a,c),!1;switch(b.tagName){case "BR":return Sl(a.a,new Tl),!1;case "TABLE":d=Gk(b);2>P||(c=y(b),Q("TABLE: "+d+", id\x3d"+b.id+", class\x3d"+(b.className||"")+", parent\x3d["+c.tagName+
", id\x3d"+c.id+", class\x3d"+(c.className||"")+"]"));if(d==(Z(),Lk))return d=a.a,Fh(d,d.d),K(d.b.a,new nm(b)),!1;break;case "VIDEO":return Sl(a.a,new om(b)),!1;case "OPTION":case "OBJECT":case "EMBED":case "APPLET":return a.a.c=!0,!1;case "HEAD":case "STYLE":case "SCRIPT":case "LINK":case "NOSCRIPT":return!1}d=a.a;pm();var e,f,g;g=getComputedStyle(b,null);c=new qm;switch(g.display){case "inline":break;case "inline-block":case "inline-flex":c.a=!0;break;default:c.b=!0,c.a=!0}g=b.tagName;if("BODY"!==
g){e=x(b,"class");f=x(b,"id");if(rm.test(e)||rm.test(f))e=c.d,e[e.length]="STRICTLY_NOT_CONTENT";switch(g){case "ASIDE":case "NAV":g=c.d;g[g.length]="STRICTLY_NOT_CONTENT";break;case "LI":g=c.d;g[g.length]="de.l3s.boilerpipe/LI";break;case "H1":g=c.d;g[g.length]="de.l3s.boilerpipe/H1";g=c.d;g[g.length]="de.l3s.boilerpipe/HEADING";break;case "H2":g=c.d;g[g.length]="de.l3s.boilerpipe/H2";g=c.d;g[g.length]="de.l3s.boilerpipe/HEADING";break;case "H3":g=c.d;g[g.length]="de.l3s.boilerpipe/H3";g=c.d;g[g.length]=
"de.l3s.boilerpipe/HEADING";break;case "A":c.a=!0,b.hasAttribute("href")&&(c.c=!0)}}K(d.a.a,c);c.a&&++d.f;c.c&&(g=d.g,g.e=!0,g.j+=" ");d.c|=c.b;return!0}function Ch(a){var b;this.d=new Ff;this.a=a;this.c=new L;K(this.c,new pl);K(this.c,new wl);K(this.c,new Al);K(this.c,new El);this.b=new Ff;for(b=new I(this.c);b.b<b.d.J();)a=(u(b.b<b.d.J()),b.d.T(b.c=b.b++)),sd(this.b,a.zb())}k(98,1,{},Ch);
_.lb=function(){var a=this.a,b;b=a.a;var c;c=b.a.b.length;if(0<c)b=($g(c-1,b.a.b.length),J(b.a,c-1));else throw new of;b.a&&--a.f;if(a.c||b.b)Fh(a,a.d),++a.d;b.c&&(b=a.g,b.e=!1,b.j+=" ");a=a.a;b=a.a.b.length;if(0<b)$g(b-1,a.a.b.length),a.a.U(b-1);else throw new of;};
_.mb=function(a){switch(a.nodeType){case 3:var b=this.a;b.c&&(Fh(b,b.d),++b.d,b.c=!1);var c=b.g,b=b.f,d;d=a.data;d.length&&(c.j+=d,K(c.a,a),/\S/.test(d)&&(a=wh(d),c.i+=a,c.e&&(c.g+=a),c.f=c.a.b.length-1,c.d<c.c&&(c.d=c.f),-1==c.b&&(c.b=b)));return!1;case 1:return Rl(this,a);default:return!1}};s(98);function pm(){pm=h;rm=/\bcomments?\b/}function qm(){this.d=[]}k(133,1,{},qm);_.a=!1;_.b=!1;_.c=!1;var rm;s(133);k(166,1,{});_.p=!1;s(166);function Tl(){}k(131,166,{},Tl);
_.Ab=function(a){return a?"\n":"\x3cbr/\x3e"};s(131);function sm(){this.a=new L}k(89,1,{},sm);s(89);function Sl(a,b){Fh(a,a.d);K(a.b.a,b)}function Fh(a,b){var c;c=a.g;var d=a.e;c.c==c.a.b.length?c=null:c.d<c.c?(tm(c),c=null):(d=new um(c.j,c.a,c.c,c.a.b.length,c.d,c.f,c.i,c.g,c.b,d),tm(c),c=d);if(c){c.d=b;++a.e;var e,f;for(e=new I(a.a.a);e.b<e.d.J();)for(d=(u(e.b<e.d.J()),e.d.T(e.c=e.b++)),f=0;f<d.d.length;f++)M(c.e,d.d[f]);K(a.b.a,c)}}
function Bh(){this.b=new sm;this.a=new ah;this.g=new vm;this.d=0}k(97,1,{},Bh);_.c=!1;_.d=0;_.e=0;_.f=0;s(97);function ul(a,b,c,d){this.a=new L;this.b=c;K(this.a,a);this.c=b;!d&&new Ef}k(40,166,{},ul);_.Ab=function(a){var b;if(a)return"";a=$doc.createElement("div");b=$doc.createElement("div");b.className="embed-placeholder";b.setAttribute("data-type",this.c);b.setAttribute("data-id",this.b);a.appendChild(b);return a.innerHTML};s(40);function ql(a,b){this.a=a;this.b=b;null==this.b&&(this.b="")}
k(36,166,{36:1},ql);_.Ab=function(a){var b;if(a)return"";a=$doc.createElement("div");b=this.a.cloneNode(!1);b.src=b.src;a.appendChild(b);return a.innerHTML};s(36);function nm(a){this.a=a}k(136,166,{},nm);
_.Ab=function(a){var b=this.a,c;b=(c=new L,Dh(new Eh(new Fi(c)),b),c);if(0==b.b.length)a="";else{c=new Pi(b);var d=(w(0,b.b.length),b.b[0]),e;for(e=d.parentNode;e&&9!=e.nodeType;d=e,e=e.parentNode);Dh(new Eh(c),d);c=c.c;for(b=(w(0,b.b.length),b.b[0]);1==c.a.b&&c.b!=b&&3!=df(c.a,0).b.nodeType;)c=df(c.a,0);b=Ui(c);1!=b.nodeType?a="":(Ei(b),Bi(b),a?($doc.body.appendChild(b),a=b.innerText,$doc.body.removeChild(b)):a=b.outerHTML)}return a};s(136);function ci(a){return J(a.a,a.c)}
function bi(a){return J(a.a,a.f)}function um(a,b,c,d,e,f,g,l,p,t){this.o=a;this.a=b;this.k=c;this.b=d;this.c=e;this.f=f;this.i=g;this.g=l;this.e=new Ff;this.n=p;this.j=t}k(24,166,{24:1},um);
_.Ab=function(a){var b,c;if(N(this.e,"de.l3s.boilerpipe/TITLE"))return"";var d=new Ne(this.a,this.k,this.b),e;if(1==d.b)b=Ti(new Ri((w(0,d.b),J(d.c,d.a))));else{c=(w(0,d.b),J(d.c,d.a));b=c.cloneNode(!1);for(d=new Qi(d);d.a;)if(Si(d,c)){if(!d.a)break;for(;;){for(e=c.nextSibling;e&&!e.contains(d.a);)e=e.nextSibling;if(e){b=jl(b,c.parentNode);b=hl(b,e);c=e;break}c=c.parentNode;b=jl(b,c)}}else{for(c=c.firstChild;!c.contains(d.a);)c=c.nextSibling;b=hl(b,c)}for(;b.parentNode;)b=b.parentNode}1!=b.nodeType&&
(c=y(Me(new Ne(this.a,this.k,this.b),0)).cloneNode(!1),c.appendChild(b),b=c);Bi(b);Ei(b);return a?b.textContent:b.outerHTML};_.b=0;_.c=0;_.d=0;_.f=0;_.g=0;_.i=0;_.j=0;_.k=0;_.n=0;s(24);function tm(a){a.j="";a.i=0;a.g=0;a.c=a.a.b.length;a.b=-1}function vm(){this.a=new L}k(126,1,{},vm);_.b=-1;_.c=0;_.d=-1;_.e=!1;_.f=0;_.g=0;_.i=0;_.j="";s(126);function om(a){this.a=a}k(132,166,{},om);
_.Ab=function(a){var b,c,d;if(a)return"";a=$doc.createElement("div");d=this.a.cloneNode(!1);for(c=0;c<this.a.childNodes.length;c++)b=this.a.childNodes[c],1!=b.nodeType||"SOURCE"!==b.tagName&&"TRACK"!==b.tagName||(b=b.cloneNode(!1),d.appendChild(b));d.poster.length&&(d.poster=d.poster);Ci(d);Ei(d);a.appendChild(d);return a.innerHTML};s(132);k(168,1,{});_.Cb=function(a){var b;b=0;a&&(b=this.Bb(a));2<=P&&Q(Cb(this.cZ)+": "+b+"/"+this.Db());return gd(b,this.Db())};s(168);
function di(){this.b=25;this.c=75E3;this.a=2E5}k(127,168,{},di);_.Bb=function(a){a=((a.offsetWidth||0)|0)*((a.offsetHeight||0)|0);if(a<this.c)return 0;a=rb((a-this.c)/(this.a-this.c)*this.b);return gd(a,this.b)};_.Db=function(){return this.b};_.a=0;_.b=0;_.c=0;s(127);function ei(){this.a=25}k(128,168,{},ei);
_.Bb=function(a){var b,c;b=(a.offsetHeight||0)|0;if(0>=b)return 0;c=(a.offsetWidth||0)|0;a=0;b=c/b;1.4500000476837158<b&&1.7999999523162842>b?a=1:1.2999999523162842<b&&2.200000047683716>b&&(a=0.4000000059604645);return rb(this.a*a)};_.Db=function(){return this.a};_.a=0;s(128);function fi(a){this.b=25;this.a=a}k(129,168,{},fi);
_.Bb=function(a){var b;if(!this.a)return 0;b=zi(this.a).b.length-1;var c;for(c=this.a;c&&!c.contains(a);)c=c.parentNode;a=b-(zi(c).b.length-1);b=0;4>a?b=1:6>a?b=0.6000000238418579:8>a&&(b=0.20000000298023224);return rb(this.b*b)};_.Db=function(){return this.b};_.b=0;s(129);function gi(){this.a=15}k(130,168,{},gi);_.Bb=function(a){var b;a=zi(a);for(b=new I(a);b.b<b.d.J();)if(a=(u(b.b<b.d.J()),b.d.T(b.c=b.b++)),1==a.nodeType&&"FIGURE"===a.tagName)return this.a;return 0};_.Db=function(){return this.a};
_.a=0;s(130);var Ml,wm;wm=Fb("I");wm.k="I";wm.f=1;Ml=wm;s(149);s(151);s(null);s(154);Pf=Ib();_=function(a){var b=this;if("$wnd"==a)return $wnd;if(""===a)return b;"$wnd."==a.substring(0,5)&&(b=$wnd,a=a.substring(5));a=a.split(".");a[0]in b||!b.execScript||b.execScript("var "+a[0]);for(var c;a.length&&(c=a.shift());)b[c]?b=b[c]:b=b[c]={};return b}("org.chromium.distiller.DomDistiller");_.apply=function(){var a;return Ah((a={},a))};_.applyWithOptions=Ah;
function xm(a){return function(){var b;a:{var c=arguments,d;0!=ec&&(d=Date.now?Date.now():(new Date).getTime(),2E3<d-gc&&(gc=d,fc=$wnd.setTimeout(Rb,10)));if(0==ec++){d=(hc(),ic);var e,f;if(d.a){f=null;do e=d.a,d.a=null,f=kc(e,f);while(d.a);d.a=f}d=!0}else d=!1;try{b=a.apply(this,c);break a}finally{if(c=d)if(d=(hc(),ic),d.b){f=null;do e=d.b,d.b=null,f=kc(e,f);while(d.b);d.b=f}--ec;c&&-1!=fc&&($wnd.clearTimeout(fc),fc=-1)}b=void 0}return b}}
var gwtOnLoad=gwtOnLoad=function(a,b,c){function d(){for(var a=0;a<e.length;a++)e[a]()}null==ia&&(ia=[]);var e=ia;$moduleName=b;$moduleBase=c;if(a)try{xm(d)()}catch(f){a(b,f)}else xm(d)()};(function(){null==ia&&(ia=[]);for(var a=ia,b=0;b<arguments.length;b++)a.push(arguments[b])})(function(){$wnd.setTimeout(xm(Tc));var a,b,c;b=$doc.compatMode;a=z(Jb(m,1),da,2,4,["CSS1Compat"]);for(c=0;c<a.length&&a[c]!==b;c++);});var ym=[[["locale","default"],["user.agent","safari"]]];
"object"===typeof window&&"object"===typeof window.$gwt&&(window.$gwt.permProps=ym);window.gwtOnLoad=gwtOnLoad;gwtOnLoad(undefined, "domdistiller", "", 0);})();
    }
    var context = Object.create(window);
    context.setTimeout = function() {};
    context.clearTimeout = function() {};
    initialize(context);

    var distiller = context.org.chromium.distiller.DomDistiller;
    var res = distiller.applyWithOptions(options);
    return res;
  } catch (e) {
    window.console.error("Error during distillation: " + e);
    if (e.stack != undefined) window.console.error(e.stack);
  }
  return undefined;
// The OPTIONS placeholder will be replaced with the DomDistillerOptions at
// runtime.
})($$OPTIONS)
