// Copyright 2015 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Creates a DomDistiller, applies to to the content of the page, and returns
// a DomDistillerResults as a JavaScript object/dictionary.
(function(options) {
  try {
    // The generated domdistiller.js accesses the window object only explicitly
    // via the window name. This creates a new object with the normal window
    // object as its prototype and initialize the domdistiller.js with that new
    // context so that it does not change the real window object.
    function initialize(window) {
      (function () {var $gwt_version = "2.7.0";var $wnd = window;var $doc = $wnd.document;var $moduleName, $moduleBase;var $stats = $wnd.__gwtStatsEvent ? function(a) {$wnd.__gwtStatsEvent(a)} : null;var $strongName = '1D6233AC8908597C7647DBF9FD87A5B8';var aa=2147483647,ba={3:1,5:1},ca={3:1,7:1,5:1},da={3:1},fa={30:1},ga={17:1},ha={3:1,20:1},ia={3:1,15:1,12:1,18:1},_,ja,ka={};function ma(){}function na(a){function b(){}b.prototype=a||{};return new b}function h(){}function k(a,b,c){var d=ka[a],e=d instanceof Array?d[0]:null;d&&!e?_=d:(_=ka[a]=b?na(ka[b]):{},_.cM=c,_.constructor=_,!b&&(_.tM=ma));for(d=3;d<arguments.length;++d)arguments[d].prototype=_;e&&(_.cZ=e)}function oa(){}function sa(a,b){return va(a)?a===b:wa(a)?a.eQ(b):(xa(a),a===b)}
function ya(a){return va(a)?m:wa(a)?a.cZ:xa(a)?a.cZ:za}function Aa(a){if(va(a)){Ia();var b=":"+a,c=Ja[b];if(null!=c)a=c;else{c=Ka[b];if(null==c){var d,e,f;d=0;e=a.length;f=e-4;for(c=0;c<f;)d=a.charCodeAt(c+3)+31*(a.charCodeAt(c+2)+31*(a.charCodeAt(c+1)+31*(a.charCodeAt(c)+31*d))),d=~~d,c+=4;for(;c<e;)d*=31,f=c++,f=a.charCodeAt(f),d+=f;c=~~d}256==La&&(Ka=Ja,Ja={},La=0);++La;a=Ja[b]=c}}else a=wa(a)?a.hC():(xa(a),a.$H||(a.$H=++Ma));return a}k(1,null,{},oa);_.eQ=function(a){return this===a};_.gC=function(){return this.cZ};
_.hC=function(){return this.$H||(this.$H=++Ma)};_.tS=function(){var a=kb(ya(this))+"@",b;b=(Aa(this)>>>0).toString(16);return a+b};_.toString=function(){return this.tS()};lb={3:1,172:1,15:1,2:1};!Array.isArray&&(Array.isArray=function(a){return"[object Array]"===Object.prototype.toString.call(a)});function wa(a){return!Array.isArray(a)&&a.tM===ma}function n(a,b){return null!=a&&(va(a)&&!!lb[b]||a.cM&&!!a.cM[b])}function xa(a){return Array.isArray(a)&&a.tM===ma}
function va(a){return"string"===typeof a}function q(a){return null==a?null:a}function mb(a){return~~Math.max(Math.min(a,aa),-2147483648)}var lb;function pb(a){if(null==a.n)if(a.A()){var b=a.c;b.B()?a.n="["+b.k:b.A()?a.n="["+b.v():a.n="[L"+b.v()+";";a.b=b.u()+"[]";a.j=b.w()+"[]"}else{var b=a.g,c=a.d,c=c.split("/");a.n=vb(".",[b,vb("$",c)]);a.b=vb(".",[b,vb(".",c)]);a.j=c[c.length-1]}}function kb(a){pb(a);return a.n}function wb(a){pb(a);return a.j}
function xb(){this.i=yb++;this.a=this.k=this.b=this.d=this.g=this.j=this.n=null}function zb(a){var b;b=new xb;b.n="Class$"+(a?"S"+a:""+b.i);b.b=b.n;b.j=b.n;return b}function s(a){var b;b=zb(a);Ab(a,b);return b}function Bb(a,b){var c;c=zb(a);Ab(a,c);c.f=b?8:0;c.e=b;return c}function Cb(){var a;a=zb(null);a.f=2;return a}function Db(a,b){var c=a.a=a.a||[];return c[b]||(c[b]=a.t(b))}
function vb(a,b){for(var c=0;!b[c]||""==b[c];)c++;for(var d=b[c++];c<b.length;c++)b[c]&&""!=b[c]&&(d+=a+b[c]);return d}function Ab(a,b){if(a){b.k=a;var c=b.B()?null:ka[b.k];c?c.cZ=b:ka[a]=[b]}}k(51,1,{},xb);_.t=function(a){var b;b=new xb;b.f=4;1<a?b.c=Db(this,a-1):b.c=this;return b};_.u=function(){pb(this);return this.b};_.v=function(){return kb(this)};_.w=function(){return wb(this)};_.A=function(){return 0!=(this.f&4)};_.B=function(){return 0!=(this.f&1)};
_.tS=function(){return(0!=(this.f&2)?"interface ":0!=(this.f&1)?"":"class ")+(pb(this),this.n)};_.f=0;_.i=0;var yb=1,Eb=s(1),za=s(0);s(51);k(5,1,ba);_.p=function(){return this.e};_.tS=function(){var a,b;a=kb(this.cZ);b=this.p();return null!=b?a+": "+b:a};s(5);function Fb(a){this.e=a;Gb(this,this.e)}k(7,5,ca,Fb);s(7);k(11,7,ca);s(11);k(76,11,ca);s(76);function Hb(){Hb=h;Ib=new oa}function Jb(a){Hb();this.e=null;this.a="";this.b=a;this.a=""}k(25,76,{25:1,3:1,7:1,5:1},Jb);
_.p=function(){var a;null==this.c&&(a=q(this.b)===q(Ib)?null:this.b,this.d=null==a?"null":null==a||va(a)||a.tM===ma?va(a)?"String":kb(ya(a)):null==a?null:a.name,this.a=this.a+": "+(null==a||va(a)||a.tM===ma?a+"":null==a?null:a.message),this.c="("+this.d+") "+this.a);return this.c};_.q=function(){return q(this.b)===q(Ib)?null:this.b};var Ib;s(25);k(148,1,{});s(148);function Kb(a){$wnd.setTimeout(function(){throw a;},0)}function Lb(){0!=Nb&&(Nb=0);Zb=-1}var Nb=0,Ma=0,$b=0,Zb=-1;
function ac(){ac=h;bc=new cc}function cc(){}function dc(a,b){var c,d,e;d=0;for(e=a.length;d<e;d++){c=a[d];try{if(c[1]){if(c[0].Cb()){var f=b;!f&&(f=[]);f[f.length]=c;b=f}}else c[0].Cb()}catch(g){if(g=ec(g),n(g,5))c=g,Kb(n(c,25)?c.q():c);else throw fc(g);}}return b}k(127,148,{},cc);var bc;s(127);function gc(){gc=h;var a,b;b=!(Error.stackTraceLimit||"stack"in Error());a=new hc;ic=b?new jc:a}function Gb(a,b){gc();ic.r(a,b)}var ic;k(160,1,{});s(160);function jc(){}k(81,160,{},jc);
_.r=function(a,b){var c={};a.fnStack=[];for(var d=arguments.callee.caller;d;){gc();var e;if(!(e=d.name)){e=d;var f=/function(?:\s+([\w$]+))?\s*\(/.exec(d.toString());e=e.name=f&&f[1]||"anonymous"}a.fnStack.push(e);e=":"+e;if(f=c[e]){var g,l;g=0;for(l=f.length;g<l;g++)if(f[g]===d)return}(f||(c[e]=[])).push(d);d=d.caller}};s(81);function kc(){kc=h;Error.stackTraceLimit=64}k(161,160,{});
_.r=function(a,b){function c(a){if(!("stack"in a))try{throw a;}catch(b){}return a}var d;"string"==typeof b?d=c(Error(b)):b instanceof Object&&"stack"in b?d=b:d=c(Error());a.__gwt$backingJsError=d};s(161);function hc(){kc()}k(82,161,{},hc);s(82);function t(a){if(!a)throw new lc;}function u(a,b){if(0>a||a>=b)throw new mc("Index: "+a+", Size: "+b);}function nc(a){if(null==a)throw new oc;}function pc(a,b){if(0>a||a>b)throw new mc("Index: "+a+", Size: "+b);}
function qc(a,b){return null==a[b]?null:String(a[b])}function v(a,b){return a.getAttribute(b)||""}function w(a){(a=a.parentNode)&&1==a.nodeType||(a=null);return a}function rc(a,b){var c;c=a.slice(0,b);x(ya(a),a.cM,a.__elementTypeId$,a.__elementTypeCategory$,c);return c}function sc(a,b){var c;c=tc(0,b);x(ya(a),a.cM,a.__elementTypeId$,a.__elementTypeCategory$,c);return c}function B(a,b,c,d){var e=da;c=tc(d,c);x(Db(a,1),e,b,d,c);return c}
function x(a,b,c,d,e){e.cZ=a;e.cM=b;e.tM=ma;e.__elementTypeId$=c;e.__elementTypeCategory$=d;return e}function tc(a,b){var c=Array(b),d;switch(a){case 6:d={l:0,m:0,h:0};break;case 7:d=0;break;case 8:d=!1;break;default:return c}for(var e=0;e<b;++e)c[e]=d;return c}function fc(a){return n(a,25)&&q(a.b)!==q((Hb(),Ib))?q(a.b)===q(Ib)?null:a.b:a}function ec(a){var b;if(n(a,5))return a;b=a&&a.__gwt$exception;if(!b&&(b=new Jb(a),Gb(b,a),a&&"object"==typeof a))try{a.__gwt$exception=b}catch(c){}return b}
function xc(){var a;a=navigator.userAgent.toLowerCase();var b=$doc.documentMode;a=-1!=a.indexOf("webkit")?"safari":-1!=a.indexOf("msie")&&10<=b&&11>b?"ie10":-1!=a.indexOf("msie")&&9<=b&&11>b?"ie9":-1!=a.indexOf("msie")&&8<=b&&11>b?"ie8":-1!=a.indexOf("gecko")||11<=b?"gecko1_8":"unknown";if("safari"!==a)throw new Lc(a);}k(41,5,ba);s(41);k(13,41,ba);s(13);
function Lc(a){this.e=""+("Possible problem with your *.gwt.xml module file.\nThe compile time user.agent value (safari) does not match the runtime user.agent value ("+a+").\nExpect more errors.");Gb(this,this.e)}k(75,13,ba,Lc);s(75);k(52,1,{});_.tS=function(){return this.a};s(52);function mc(a){Fb.call(this,a)}k(21,11,ca,mc);s(21);function Mc(){Gb(this,this.e)}k(139,21,ca,Mc);s(139);function Nc(){Nc=h;Oc=new Pc(!1);Qc=new Pc(!0)}function Pc(a){this.a=a}k(32,1,{3:1,32:1,15:1},Pc);
_.s=function(a){var b=this.a;return b==a.a?0:b?1:-1};_.eQ=function(a){return n(a,32)&&a.a==this.a};_.hC=function(){return this.a?1231:1237};_.tS=function(){return""+this.a};_.a=!1;var Oc,Qc;s(32);k(50,1,{3:1,50:1});s(50);k(12,1,{3:1,15:1,12:1});_.s=function(a){return this.b-a.b};_.eQ=function(a){return this===a};_.hC=function(){return this.$H||(this.$H=++Ma)};_.tS=function(){return null!=this.a?this.a:""+this.b};_.b=0;s(12);function Rc(a){Fb.call(this,a)}k(58,11,ca,Rc);s(58);
function Sc(){Gb(this,this.e)}k(137,11,ca,Sc);s(137);function Tc(a){this.a=a}function Uc(a){var b,c;return-129<a&&128>a?(b=a+128,c=(Vc(),Wc)[b],!c&&(c=Wc[b]=new Tc(a)),c):new Tc(a)}k(24,50,{3:1,15:1,24:1,50:1},Tc);_.s=function(a){var b=this.a;a=a.a;return b<a?-1:b>a?1:0};_.eQ=function(a){return n(a,24)&&a.a==this.a};_.hC=function(){return this.a};_.tS=function(){return""+this.a};_.a=0;var Xc=s(24);function Vc(){Vc=h;Wc=B(Xc,24,256,0)}var Wc;function Yc(a,b){return a<b?a:b}
function oc(){Gb(this,this.e)}function Zc(a){Fb.call(this,a)}k(47,11,ca,oc,Zc);s(47);function D(a,b){return null==b?!1:a==b?!0:a.length==b.length&&a.toLowerCase()==b.toLowerCase()}function $c(a){var b=(160).toString(16),b="\\u"+"0000".substring(b.length)+b;return a.replace(RegExp(b,"g"),String.fromCharCode(32))}function ad(a){var b;b=bd("");return a.replace(RegExp("'","g"),b)}function cd(a,b){var c;c=bd("");return a.replace(RegExp(b),c)}
function dd(a,b){for(var c=RegExp(b,"g"),d=[],e=0,f=a,g=null;;){var l=c.exec(f);if(null==l||""==f){d[e]=f;break}else d[e]=f.substring(0,l.index),f=f.substring(l.index+l[0].length,f.length),c.lastIndex=0,g==f&&(d[e]=f.substring(0,1),f=f.substring(1)),g=f,e++}if(0<a.length){for(c=d.length;0<c&&""==d[c-1];)--c;c<d.length&&d.splice(c,d.length-c)}c=B(m,2,d.length,4);for(e=0;e<d.length;++e)c[e]=d[e];return c}function ed(a,b){return a.substr(b,a.length-b)}
function fd(a){return 0==a.length||" "<a[0]&&" "<a[a.length-1]?a:a.replace(/^[\u0000-\u0020]*|[\u0000-\u0020]*$/g,"")}function bd(a){var b;for(b=0;0<=(b=a.indexOf("\\",b));)36==a.charCodeAt(b+1)?a=a.substr(0,b)+"$"+ed(a,++b):a=a.substr(0,b)+ed(a,++b);return a}var m=s(2);function Ia(){Ia=h;Ka={};Ja={}}var Ka,La=0,Ja;function gd(a){this.a=a}k(42,52,{172:1},gd);s(42);function hd(a){Fb.call(this,a)}k(36,11,ca,hd);s(36);
function id(a,b){var c,d,e;nc(b);c=!1;for(e=b.C();e.O();)d=e.P(),c|=a.D(d);return c}function jd(a){var b,c,d,e;e=new gd("[");b=!1;for(d=a.C();d.O();)c=d.P(),b?e.a+=", ":b=!0,e.a+=c===a?"(this Collection)":""+c;e.a+="]";return e.a}k(163,1,{});_.D=function(){throw new hd("Add not supported on this collection");};_.F=function(a){return id(this,a)};_.G=function(a){a:{var b,c;for(c=this.C();c.O();)if(b=c.P(),q(a)===q(b)||null!=a&&sa(a,b)){a=!0;break a}a=!1}return a};
_.I=function(){return this.J(B(Eb,1,this.H(),3))};_.J=function(a){var b,c,d;d=this.H();a.length<d&&(a=sc(a,d));c=this.C();for(b=0;b<d;++b)a[b]=c.P();a.length>d&&(a[d]=null);return a};_.tS=function(){return jd(this)};s(163);function kd(a,b){var c,d,e;c=b.U();e=b.V();d=a.N(c);return!(q(e)===q(d)||null!=e&&sa(e,d))||null==d&&!a.L(c)?!1:!0}function ld(a,b){var c,d,e;for(d=a.M().C();d.O();)if(c=d.P(),e=c.U(),q(b)===q(e)||null!=b&&sa(b,e))return c;return null}
function md(a,b){return b===a?"(this Map)":""+b}function nd(a){return a?a.V():null}k(162,1,fa);_.K=function(a){return kd(this,a)};_.L=function(a){return!!ld(this,a)};_.eQ=function(a){var b;if(a===this)return!0;if(!n(a,30)||this.H()!=a.H())return!1;for(b=a.M().C();b.O();)if(a=b.P(),!this.K(a))return!1;return!0};_.N=function(a){return nd(ld(this,a))};_.hC=function(){return Bd(this.M())};_.H=function(){return this.M().H()};
_.tS=function(){var a,b,c,d;d=new gd("{");a=!1;for(c=this.M().C();c.O();)b=c.P(),a?d.a+=", ":a=!0,d.a+=md(this,b.U()),d.a+="\x3d",d.a+=md(this,b.V());d.a+="}";return d.a};s(162);function Cd(a,b){return va(b)?F(a,b):!!Wd(a.a,b)}function Xd(a,b){return va(b)?G(a,b):nd(Wd(a.a,b))}function G(a,b){return null==b?nd(Wd(a.a,null)):a.c.bb(b)}function F(a,b){return null==b?!!Wd(a.a,null):void 0!==a.c.bb(b)}function ve(a,b,c){return va(b)?H(a,b,c):we(a.a,b,c)}
function H(a,b,c){return null==b?we(a.a,null,c):a.c.eb(b,c)}function xe(a){ye();a.a=ze.$();a.a.b=a;a.c=ze._();a.c.b=a;a.b=0;Ae(a)}k(83,162,fa);_.L=function(a){return Cd(this,a)};_.M=function(){return new Be(this)};_.N=function(a){return Xd(this,a)};_.H=function(){return this.b};_.b=0;s(83);k(164,163,ga);_.eQ=function(a){if(a===this)a=!0;else if(n(a,17)&&a.H()==this.H())a:{var b;nc(a);for(b=a.C();b.O();)if(a=b.P(),!this.G(a)){a=!1;break a}a=!0}else a=!1;return a};_.hC=function(){return Bd(this)};s(164);
function Be(a){this.a=a}k(53,164,ga,Be);_.G=function(a){return n(a,16)?kd(this.a,a):!1};_.C=function(){return new Ce(this.a)};_.H=function(){return this.a.b};s(53);function De(a){if(a.a.O())return!0;if(a.a!=a.b)return!1;a.a=a.c.a.Y();return a.a.O()}function Ee(a){if(a._gwt_modCount!=a.c._gwt_modCount)throw new Fe;return t(De(a)),a.a.P()}function Ce(a){this.c=a;this.a=this.b=this.c.c.Y();this._gwt_modCount=a._gwt_modCount}k(54,1,{},Ce);_.O=function(){return De(this)};_.P=function(){return Ee(this)};
s(54);k(165,163,{20:1});_.Q=function(){throw new hd("Add not supported on this list");};_.D=function(a){this.Q(this.H(),a);return!0};_.eQ=function(a){var b,c,d;if(a===this)return!0;if(!n(a,20)||this.H()!=a.H())return!1;d=a.C();for(b=this.C();b.O();)if(a=b.P(),c=d.P(),!(q(a)===q(c)||null!=a&&sa(a,c)))return!1;return!0};_.hC=function(){var a,b,c;c=1;for(b=this.C();b.O();)a=b.P(),c=31*c+(null!=a?Aa(a):0),c=~~c;return c};_.C=function(){return new I(this)};
_.S=function(){throw new hd("Remove not supported on this list");};s(165);function Ge(a){t(a.b<a.d.H());return a.d.R(a.c=a.b++)}function He(a){if(-1==a.c)throw new Sc;a.d.S(a.c);a.b=a.c;a.c=-1}function I(a){this.d=a}k(4,1,{},I);_.O=function(){return this.b<this.d.H()};_.P=function(){return Ge(this)};_.T=function(){He(this)};_.b=0;_.c=-1;s(4);function Ie(a,b){this.d=this.a=a;pc(b,a.b.length);this.b=b}k(26,4,{},Ie);s(26);
function Je(a,b,c){var d=a.b.length;if(0>b)throw new mc("fromIndex: "+b+" \x3c 0");if(c>d)throw new mc("toIndex: "+c+" \x3e size "+d);if(b>c)throw new Rc("fromIndex: "+b+" \x3e toIndex: "+c);this.c=a;this.a=b;this.b=c-b}k(56,165,{20:1},Je);_.Q=function(a,b){pc(a,this.b);Ke(this.c,this.a+a,b);++this.b};_.R=function(a){u(a,this.b);return J(this.c,this.a+a)};_.S=function(a){u(a,this.b);a=this.c.S(this.a+a);--this.b;return a};_.H=function(){return this.b};_.a=0;_.b=0;s(56);
function Le(a){a=new Ce((new Be(a.a)).a);return new Me(a)}function Ne(a){this.a=a}k(44,164,ga,Ne);_.G=function(a){return Cd(this.a,a)};_.C=function(){return Le(this)};_.H=function(){return this.a.b};s(44);function Me(a){this.a=a}k(84,1,{},Me);_.O=function(){return De(this.a)};_.P=function(){return Ee(this.a).U()};s(84);function Oe(a,b){var c;c=a.d;a.d=b;return c}k(33,1,{33:1,16:1});_.eQ=function(a){return n(a,16)?Pe(this.c,a.U())&&Pe(this.d,a.V()):!1};_.U=function(){return this.c};_.V=function(){return this.d};
_.hC=function(){return Qe(this.c)^Qe(this.d)};_.W=function(a){return Oe(this,a)};_.tS=function(){return this.c+"\x3d"+this.d};s(33);function Re(a,b){this.c=a;this.d=b}k(34,33,{33:1,34:1,16:1},Re);s(34);k(168,1,{16:1});_.eQ=function(a){return n(a,16)?Pe(this.U(),a.U())&&Pe(this.V(),a.V()):!1};_.hC=function(){return Qe(this.U())^Qe(this.V())};_.tS=function(){return this.U()+"\x3d"+this.V()};s(168);function Se(a,b){var c;c=Te(a,b.U());return!!c&&Pe(c.d,b.V())}k(171,162,fa);
_.K=function(a){return Se(this,a)};_.L=function(a){return!!Te(this,a)};_.M=function(){return new Ue(this)};_.N=function(a){return nd(Te(this,a))};s(171);function Ue(a){this.a=a}k(73,164,ga,Ue);_.G=function(a){return n(a,16)&&Se(this.a,a)};_.C=function(){return new Ve(this.a)};_.H=function(){return this.a.b};s(73);function We(a){a=new Ve((new Xe(a.a)).a);return new Ye(a)}function Ze(a){this.a=a}k(144,164,ga,Ze);_.G=function(a){return!!Te(this.a,a)};_.C=function(){return We(this)};_.H=function(){return this.a.b};
s(144);function Ye(a){this.a=a}k(145,1,{},Ye);_.O=function(){return this.a.a.O()};_.P=function(){return this.a.a.P().U()};s(145);function $e(a,b){var c;c=af(a,b);try{return t(c.b!=c.d.c),c.c=c.b,c.b=c.b.a,++c.a,c.c.c}catch(d){d=ec(d);if(n(d,37))throw new mc("Can't get element "+b);throw fc(d);}}k(166,165,{20:1});_.Q=function(a,b){var c;c=af(this,a);bf(c.d,b,c.b.b,c.b);++c.a;c.c=null};_.R=function(a){return $e(this,a)};_.C=function(){return af(this,0)};
_.S=function(a){var b,c;b=af(this,a);try{return c=(t(b.b!=b.d.c),b.c=b.b,b.b=b.b.a,++b.a,b.c.c),cf(b),c}catch(d){d=ec(d);if(n(d,37))throw new mc("Can't remove element "+a);throw fc(d);}};s(166);function Ke(a,b,c){pc(b,a.b.length);a.b.splice(b,0,c)}function K(a,b){a.b[a.b.length]=b;return!0}
function df(a,b){var c;c=b.I();if(0==c.length)return!1;var d=c,e=a.b,f=a.b.length;c=c.length;var g=0;d===e&&(d=d.slice(g,g+c),g=0);for(var l=g,g=g+c;l<g;){var p=Math.min(l+1E4,g);c=p-l;Array.prototype.splice.apply(e,[f,0].concat(d.slice(l,p)));l=p;f+=c}return!0}function J(a,b){u(b,a.b.length);return a.b[b]}function ef(a,b){for(var c=0;c<a.b.length;++c)if(Pe(b,a.b[c]))return c;return-1}function ff(a,b){var c;c=(u(b,a.b.length),a.b[b]);a.b.splice(b,1);return c}
function gf(a,b){var c,d;d=a.b.length;b.length<d&&(b=sc(b,d));for(c=0;c<d;++c)b[c]=a.b[c];b.length>d&&(b[d]=null);return b}function L(){this.b=B(Eb,1,0,3)}k(6,165,ha,L);_.Q=function(a,b){Ke(this,a,b)};_.D=function(a){return K(this,a)};_.F=function(a){return df(this,a)};_.G=function(a){return-1!=ef(this,a)};_.R=function(a){return J(this,a)};_.S=function(a){return ff(this,a)};_.H=function(){return this.b.length};_.I=function(){return rc(this.b,this.b.length)};_.J=function(a){return gf(this,a)};s(6);
function Bd(a){var b,c;c=0;for(b=a.C();b.O();)a=b.P(),c+=null!=a?Aa(a):0,c=~~c;return c}function hf(){hf=h}function jf(a,b){nc(a);nc(b);return va(a)?a==b?0:a<b?-1:1:a.s(b)}k(147,1,{},function(){});s(147);function Ae(a){a._gwt_modCount=(a._gwt_modCount|0)+1}function Fe(){Gb(this,this.e)}k(146,11,ca,Fe);s(146);function kf(){Gb(this,this.e)}k(70,11,ca,kf);s(70);function lf(a,b){return mf(a.a,b)?a.b[b.b]:null}function nf(a,b,c){of(a.a,b);pf(a,b.b,c)}
function pf(a,b,c){var d;d=a.b[b];a.b[b]=c;return d}function qf(a){var b;this.a=(b=a.e&&a.e(),new rf(b,sc(b,b.length)));this.b=B(Eb,1,this.a.a.length,3)}k(128,162,fa,qf);_.L=function(a){return mf(this.a,a)};_.M=function(){return new sf(this)};_.N=function(a){return lf(this,a)};_.H=function(){return this.a.c};s(128);function sf(a){this.a=a}k(66,164,ga,sf);_.G=function(a){return n(a,16)?kd(this.a,a):!1};_.C=function(){return new tf(this.a)};_.H=function(){return this.a.a.c};s(66);
function tf(a){this.c=a;this.a=new uf(this.c.a)}k(67,1,{},tf);_.O=function(){return vf(this.a)};_.P=function(){return this.b=wf(this.a),new xf(this.c,this.b)};s(67);function xf(a,b){this.b=a;this.a=b}k(68,168,{16:1},xf);_.U=function(){return this.a};_.V=function(){return this.b.b[this.a.b]};_.W=function(a){return pf(this.b,this.a.b,a)};s(68);k(170,164,ga);s(170);function of(a,b){var c;nc(b);c=b.b;return a.b[c]?!1:(a.b[c]=b,++a.c,!0)}function mf(a,b){return n(b,12)&&!!b&&a.b[b.b]==b}
function rf(a,b){this.a=a;this.b=b;this.c=0}k(138,170,ga,rf);_.D=function(a){return of(this,a)};_.G=function(a){return mf(this,a)};_.C=function(){return new uf(this)};_.H=function(){return this.c};_.c=0;s(138);function yf(a){var b;++a.a;for(b=a.c.a.length;a.a<b&&!a.c.b[a.a];++a.a);}function vf(a){return a.a<a.c.a.length}function wf(a){return t(a.a<a.c.a.length),a.b=a.a,yf(a),a.c.b[a.b]}function uf(a){this.c=a;yf(this)}k(69,1,{},uf);_.O=function(){return vf(this)};_.P=function(){return wf(this)};
_.a=-1;_.b=-1;s(69);function zf(a,b){return q(a)===q(b)||null!=a&&sa(a,b)}function M(){xe(this)}k(9,83,{3:1,30:1},M);s(9);function N(a,b){return null==ve(a.a,b,a)}function O(a,b){return Cd(a.a,b)}function Af(){this.a=new M}k(14,164,{3:1,17:1},Af);_.D=function(a){return N(this,a)};_.G=function(a){return O(this,a)};_.C=function(){return Le(new Ne(this.a))};_.H=function(){return this.a.b};_.tS=function(){return jd(new Ne(this.a))};s(14);
function Wd(a,b){var c,d,e,f;c=null==b?"0":""+~~Aa(b);d=a.a[c]||[];e=0;for(f=d.length;e<f;++e)if(c=d[e],zf(b,c.U()))return c;return null}function we(a,b,c){var d,e,f,g;d=null==b?"0":""+~~Aa(b);e=a.a;d=e[d]||(e[d]=[]);f=0;for(g=d.length;f<g;++f)if(e=d[f],zf(b,e.U()))return e.W(c);d[d.length]=new Re(b,c);a=a.b;++a.b;Ae(a);return null}function Bf(){this.a=this.X()}k(65,1,{},Bf);_.X=function(){return Object.create(null)};_.Y=function(){return new Cf(this)};s(65);
function Df(a){if(a.c<a.a.length)return!0;if(a.b<a.d.length-1){var b=a.d[++a.b];a.a=a.f.a[b];a.c=0;return!0}return!1}function Cf(a){this.f=a;this.d=Object.getOwnPropertyNames(this.f.a);this.a=B(Jf,16,0,0)}k(126,1,{},Cf);_.O=function(){return Df(this)};_.P=function(){return t(Df(this)),this.e=this.a[this.c++],this.e};_.b=-1;_.c=0;_.e=null;s(126);function ig(){Bf.call(this)}k(124,65,{},ig);_.X=function(){return{}};
_.Y=function(){var a=this.Z(),b=this.a,c;for(c in b)if(c==parseInt(c,10))for(var d=b[c],e=0,f=d.length;e<f;++e)a.D(d[e]);return a.C()};_.Z=function(){return new Dg(this)};s(124);function Dg(a){this.a=a;L.call(this)}k(125,6,ha,Dg);_.S=function(a){a=ff(this,a);a:{var b=this.a,c=a.U(),d,e,f,g;f=null==c?"0":""+~~Aa(c);d=b.a[f]||[];for(g=0;g<d.length;g++)if(e=d[g],zf(c,e.U())){1==d.length?delete b.a[f]:d.splice(g,1);b=b.b;--b.b;Ae(b);break a}}return a};s(125);function Eg(){}k(121,1,{},Eg);_.$=function(){return new Bf};
_._=function(){return new Fg};s(121);function ye(){ye=h;var a,b;if(b=Object.create&&Object.getOwnPropertyNames)b=Object.create(null),void 0!==b.__proto__||0!=Object.getOwnPropertyNames(b).length?b=!1:(b.__proto__=42,b=42!==b.__proto__?!1:!0);ze=b?(a=Object.create(null),a.__proto__=42,0==Object.getOwnPropertyNames(a).length)?new Qg:new Eg:new Rg}var ze;function Qg(){}k(123,121,{},Qg);_._=function(){return new Sg};s(123);function Rg(){}k(122,121,{},Rg);_.$=function(){return new ig};_._=function(){return new Tg};
s(122);function Ug(a,b,c){var d;d=a.a[b];if(void 0===d){var e=a.b;++e.b;Ae(e)}a.a[b]=void 0===c?null:c;return d}function Vg(a,b){var c;c=a.a[b];if(void 0!==c){delete a.a[b];var d=a.b;--d.b;Ae(d)}return c}function Fg(){this.a=this.ab()}k(48,1,{},Fg);_.ab=function(){return Object.create(null)};_.Y=function(){var a;a=this.cb();return new Wg(this,a)};_.bb=function(a){return this.a[a]};_.cb=function(){return Object.getOwnPropertyNames(this.a)};_.db=function(a){return new Xg(this,a)};
_.eb=function(a,b){return Ug(this,a,b)};_.fb=function(a){return Vg(this,a)};s(48);function Wg(a,b){this.b=a;this.c=b}k(106,1,{},Wg);_.O=function(){return this.a<this.c.length};_.P=function(){return t(this.a<this.c.length),new Xg(this.b,this.c[this.a++])};_.a=0;s(106);function Xg(a,b){this.a=a;this.b=b}k(59,168,{16:1},Xg);_.U=function(){return this.b};_.V=function(){return this.a.bb(this.b)};_.W=function(a){return this.a.eb(this.b,a)};s(59);function Tg(){Fg.call(this)}k(103,48,{},Tg);_.ab=function(){return{}};
_.Y=function(){var a=this.gb(),b;for(b in this.a)if(58==b.charCodeAt(0)){var c=this.db(b.substring(1));a.D(c)}return a.C()};_.bb=function(a){return this.a[":"+a]};_.gb=function(){return new Yg(this)};_.eb=function(a,b){return Ug(this,":"+a,b)};_.fb=function(a){return Vg(this,":"+a)};s(103);function Yg(a){this.a=a;L.call(this)}k(105,6,ha,Yg);_.S=function(a){var b;return b=ff(this,a),Vg(this.a,":"+b.U()),b};s(105);function Sg(){Fg.call(this)}k(104,48,{},Sg);
_.cb=function(){var a;a=Object.getOwnPropertyNames(this.a);void 0!==this.a.__proto__&&(a[a.length]="__proto__");return a};s(104);function Zg(a,b){bf(a,b,a.c.b,a.c);return!0}function bf(a,b,c,d){var e;e=new $g;e.c=b;e.b=c;e.a=d;d.b=c.a=e;++a.b}function af(a,b){var c,d;pc(b,a.b);if(b>=a.b>>1)for(d=a.c,c=a.b;c>b;--c)d=d.b;else for(d=a.a.a,c=0;c<b;++c)d=d.a;return new ah(a,b,d)}function bh(){this.a=new $g;this.c=new $g;this.a.a=this.c;this.c.b=this.a;this.a.b=this.c.a=null;this.b=0}k(55,166,ha,bh);
_.D=function(a){return Zg(this,a)};_.H=function(){return this.b};_.b=0;s(55);function cf(a){var b;if(!a.c)throw new Sc;b=a.c.a;var c=a.d,d=a.c;d.a.b=d.b;d.b.a=d.a;d.a=d.b=null;d.c=null;--c.b;a.b==a.c?a.b=b:--a.a;a.c=null}function ah(a,b,c){this.d=a;this.b=c;this.a=b}k(85,1,{},ah);_.O=function(){return this.b!=this.d.c};_.P=function(){return t(this.b!=this.d.c),this.c=this.b,this.b=this.b.a,++this.a,this.c.c};_.T=function(){cf(this)};_.a=0;_.c=null;s(85);function $g(){}k(45,1,{},$g);s(45);var Jf=Cb();
function lc(){Gb(this,this.e)}k(37,11,{3:1,7:1,5:1,37:1},lc);s(37);function Pe(a,b){return q(a)===q(b)||null!=a&&sa(a,b)}function Qe(a){return null!=a?Aa(a):0}function ch(a,b){if(0>a||a>=b)throw new Mc;}k(129,165,ha);_.Q=function(a,b){ch(a,this.a.b.length+1);Ke(this.a,a,b)};_.D=function(a){return K(this.a,a)};_.F=function(a){return df(this.a,a)};_.G=function(a){return-1!=ef(this.a,a)};_.R=function(a){return ch(a,this.a.b.length),J(this.a,a)};_.C=function(){return new I(this.a)};
_.S=function(a){return ch(a,this.a.b.length),this.a.S(a)};_.H=function(){return this.a.b.length};_.I=function(){var a=this.a;return rc(a.b,a.b.length)};_.J=function(a){return gf(this.a,a)};_.tS=function(){return jd(this.a)};s(129);function dh(){this.a=new L}k(130,129,ha,dh);s(130);function Te(a,b){var c,d;for(d=a.a;d;){c=jf(b,d.c);if(0==c)return d;c=0>c?0:1;d=d.a[c]}return null}
function eh(a,b,c,d,e,f,g,l){var p;if(d){(p=d.a[0])&&eh(a,b,c,p,e,f,g,l);p=d.c;var z,y;c.hb()&&(z=jf(p,e),0>z||!f&&0==z)||c.ib()&&(y=jf(p,g),0<y||!l&&0==y)||b.D(d);(d=d.a[1])&&eh(a,b,c,d,e,f,g,l)}}function fh(a,b,c,d){var e,f;if(b){e=jf(c.c,b.c);if(0==e)return d.d=Oe(b,c.d),d.b=!0,b;e=0>e?0:1;b.a[e]=fh(a,b.a[e],c,d);gh(b.a[e])&&(gh(b.a[1-e])?(b.b=!0,b.a[0].b=!1,b.a[1].b=!1):gh(b.a[e].a[e])?b=hh(b,1-e):gh(b.a[e].a[1-e])&&(b=(f=1-(1-e),b.a[f]=hh(b.a[f],f),hh(b,1-e))))}else return c;return b}
function gh(a){return!!a&&a.b}function hh(a,b){var c,d;c=1-b;d=a.a[c];a.a[c]=d.a[b];d.a[b]=a;a.b=!0;d.b=!1;return d}function ih(){this.a=null;hf()}k(72,171,{3:1,30:1},ih);_.M=function(){return new Xe(this)};_.H=function(){return this.b};_.b=0;s(72);function Ve(a){var b=(jh(),kh),c;c=new L;eh(a,c,b,a.a,null,!1,null,!1);this.a=new Ie(c,0)}k(49,1,{},Ve);_.O=function(){return this.a.O()};_.P=function(){return this.a.P()};s(49);function Xe(a){this.a=a}k(74,73,ga,Xe);s(74);
function lh(a,b){Re.call(this,a,b);this.a=B(mh,40,2,0);this.b=!0}k(40,34,{33:1,34:1,16:1,40:1},lh);_.b=!1;var mh=s(40);function nh(){}k(140,1,{},nh);_.tS=function(){return"State: mv\x3d"+this.c+" value\x3d"+this.d+" done\x3d"+this.a+" found\x3d"+this.b};_.a=!1;_.b=!1;_.c=!1;s(140);function jh(){jh=h;kh=new oh("All",0);ph=new qh;rh=new sh;th=new uh}function oh(a,b){this.a=a;this.b=b}k(18,12,ia,oh);_.hb=function(){return!1};_.ib=function(){return!1};
var kh,ph,rh,th,vh=Bb(18,function(){jh();return x(Db(vh,1),da,18,0,[kh,ph,rh,th])});function qh(){this.a="Head";this.b=1}k(141,18,ia,qh);_.ib=function(){return!0};Bb(141,null);function sh(){this.a="Range";this.b=2}k(142,18,ia,sh);_.hb=function(){return!0};_.ib=function(){return!0};Bb(142,null);function uh(){this.a="Tail";this.b=3}k(143,18,ia,uh);_.hb=function(){return!0};Bb(143,null);function wh(a){this.a=new ih;id(this,a)}k(71,164,{3:1,17:1},wh);
_.D=function(a){var b=this.a,c=(Nc(),Oc);a=new lh(a,c);c=new nh;b.a=fh(b,b.a,a,c);c.b||++b.b;b.a.b=!1;return null==c.d};_.G=function(a){return!!Te(this.a,a)};_.C=function(){return We(new Ze(this.a))};_.H=function(){return this.a.b};s(71);
function xh(a){var b;if(!(0<a.a.b)){b=yh(a.f);!b.length||Zg(a.a,b);b=a.a;var c;var d=$doc.title,e=$doc.documentElement,f;c=f="";m==m?f=c=d:e&&(d=e.getElementsByTagName("TITLE"),0<d.length&&(f=c=d[0].textContent));if(""==f)c="";else{if(/ [\|\-] /i.test(f))f=c.replace(RegExp("(.*)[\\|\\-] .*","gi"),"$1"),3>zh(f)&&(f=c.replace(RegExp("[^\\|\\-]*[\\|\\-](.*)","gi"),"$1"));else if(-1!=f.indexOf(": "))f=c.replace(RegExp(".*:(.*)","gi"),"$1"),3>zh(f)&&(f=c.replace(RegExp("[^:]*[:](.*)","gi"),"$1"));else if(e&&
(150<f.length||15>f.length)){f=e.getElementsByTagName("H1");e="";for(d=0;d<f.length&&!e.length;d++)e=f[d].innerText;f=e;!f.length&&(f=c)}f=f.trim();4>=zh(f)&&(f=c);c=f}Zg(b,c);m==m&&Zg(a.a,$doc.title)}}function Ah(a){var b,c;this.b=a;this.a=new bh;this.e=(b={},b[6]=[],b);this.d=(c={},c);this.c=new L;b=P();this.f=new Bh(a,this.e);a=P()-b;if(void 0==a)throw new TypeError;this.e[1]=a;this.g=""}
function Ch(a){var b;switch(a.nodeType){case 1:a.hasAttribute("id")&&a.setAttribute("id","");case 9:for(b=0;b<a.childNodes.length;b++)Ch(a.childNodes[b])}}k(77,1,{},Ah);s(77);function Dh(){}k(78,1,{},Dh);s(78);
function Eh(a){var b,c,d,e,f,g,l,p,z,y,W,cj,Ef,od,pd,dj,ej;l=P();f=(W={},W[10]=[],W);c=new Ah($doc.documentElement);var fj=(xh(c),$e(c.a,0));if(void 0==fj)throw new TypeError;f[1]=fj;var Ff;if(void 0!=a[2]){if(void 0===a[2])throw new TypeError;Ff=a[2]}else Ff=0;Q=Ff;R("DomDistiller debug level: "+Q);b=(cj={},cj);var Gf;if(Gf=void 0!=a[1]){if(void 0===a[1])throw new TypeError;Gf=a[1]}var qd;var Vl=Gf,rd,uc,vc,Hf,wc,Mb,sd,td,If;Mb=P();uc=(sd=new Dh,td=new Fh,If=new Gh(td),Hh(new Ih(If),c.b),sd.a=(Jh(td),
td.b),xh(c),sd.b=If.d,sd);var ij=P()-Mb;if(void 0==ij)throw new TypeError;c.e[2]=ij;Mb=P();var A,Kf=uc.a,jj,yc,Lf;Lf=new L;for(yc=0;yc<Kf.a.b.length;yc++)jj=J(Kf.a,yc),n(jj,35)&&K(Lf,new Kh(Kf.a,yc));A=new Lh(Lf);var Wl=c.a,E;Mh(A,!0,"Start");var Xl=(Nh(),A),Mf,Na;for(Na=new I(Xl.a);Na.b<Na.d.H();){Mf=(t(Na.b<Na.d.H()),Na.d.R(Na.c=Na.b++));var Nf;var Of=Mf,ud=void 0;14<Of.d?Nf=!1:(ud=Of.g.trim(),Nf=8<=ud.length?Oh.test(ud):1==Of.c?"Comment"===ud:!1);Nf&&N(Mf.b,"STRICTLY_NOT_CONTENT")}var Pf=new Ph(Wl),
vd,Oa,pa;if(Pf.a)for(Oa=new I(A.a);Oa.b<Oa.d.H();)vd=(t(Oa.b<Oa.d.H()),Oa.d.R(Oa.c=Oa.b++)),pa=vd.g,pa=$c(pa),pa=ad(pa),pa=fd(pa).toLowerCase(),O(Pf.a,pa)&&N(vd.b,"de.l3s.boilerpipe/TITLE"),pa=fd(pa.replace(Qh,"")),O(Pf.a,pa)&&N(vd.b,"de.l3s.boilerpipe/TITLE");var zc,wd,qa,Ac,Bc,ta,Ba;ta=A.a;if(0==ta.b.length)E=!1;else{wd=!1;for(qa=0;qa<ta.b.length;qa++)Bc=0==qa?null:(u(qa-1,ta.b.length),ta.b[qa-1]),zc=(u(qa,ta.b.length),ta.b[qa]),Ac=qa+1==ta.b.length?null:(u(qa+1,ta.b.length),ta.b[qa+1]),wd|=(0.333333>=
zc.c?!Bc||0.555556>=Bc.c?16>=zc.d?!Ac||15>=Ac.d?!Bc||4>=Bc.d?Ba=!1:Ba=!0:Ba=!0:Ba=!0:40>=zc.d?!Ac||17>=Ac.d?Ba=!1:Ba=!0:Ba=!0:Ba=!1,Rh(zc,Ba));E=wd}Mh(A,E,"Classification Complete");var Yl=(Sh(),Th),Qf,sj,Rf,xd,tj,yd,Pa;Qf=!1;Pa=new I(A.a);b:for(;Pa.b<Pa.d.H();)if(yd=(t(Pa.b<Pa.d.H()),Pa.d.R(Pa.c=Pa.b++)),yd.a)for(Rf=Yl.a,xd=0,tj=Rf.length;xd<tj;++xd)if(sj=Rf[xd],O(yd.b,sj)){Rh(yd,!1);Qf=!0;continue b}E=Qf;Mh(A,E,"Ignore Strictly Not Content blocks");var Sf=Uh();Sf.e=0.5;Sf.d=10;E=Vh(Wh(Sf),A);Mh(A,
E,"SimilarSiblingContentExpansion: Cross headings");var zd=Uh();zd.c=!0;zd.e=0;zd.d=10;E=Vh(Wh(zd),A);Mh(A,E,"SimilarSiblingContentExpansion: Mixed tags");var Ad,Qa,xj,Cc,ra,Tf;Tf=A.a;if(2>Tf.b.length)E=!1;else{Ad=!1;Cc=new Ie(Tf,0);for(Qa=Cc.P();Cc.O();)if(ra=Qa,Qa=Cc.P(),O(ra.b,"de.l3s.boilerpipe/HEADING")&&!(O(ra.b,"STRICTLY_NOT_CONTENT")||O(Qa.b,"STRICTLY_NOT_CONTENT")||O(ra.b,"de.l3s.boilerpipe/TITLE")||O(Qa.b,"de.l3s.boilerpipe/TITLE")))if(Qa.a){Ad=!0;xj=ra.a;Xh(ra,Qa);Qa=ra;Cc.T();var zj=ra;
O(zj.b,"de.l3s.boilerpipe/HEADING")&&zj.b.a.c.fb("de.l3s.boilerpipe/HEADING");xj||N(ra.b,"BOILERPLATE_HEADING_FUSED")}else ra.a&&(Ad=!0,Rh(ra,!1));E=Ad}Mh(A,E,"HeadingFusion");E=Yh((Zh(),$h),A);Mh(A,E,"BlockProximityFusion: Distance 1");var Zl=(ai(),bi),Uf,Ca,Vf,Fj;Fj=A.a;Uf=!1;for(Ca=new I(Fj);Ca.b<Ca.d.H();)Vf=(t(Ca.b<Ca.d.H()),Ca.d.R(Ca.c=Ca.b++)),Vf.a||null!=Zl.a&&O(Vf.b,"de.l3s.boilerpipe/TITLE")||(He(Ca),Uf=!0);E=Uf;Mh(A,E,"BlockFilter");E=Yh(ci,A);Mh(A,E,"BlockProximityFusion: Same level content-only");
var $l=(di(),ei),Wf,Ra,Dc,Xf,Yf,ua,Sa,Ta,Ob;Ob=A.a;if(2>Ob.b.length)E=!1;else{Xf=-1;Ra=null;Wf=0;Dc=-1;for(Ta=new I(Ob);Ta.b<Ta.d.H();)ua=(t(Ta.b<Ta.d.H()),Ta.d.R(Ta.c=Ta.b++)),ua.a&&(Yf=ua.d,Yf>Xf&&(Ra=ua,Xf=Yf,Dc=Wf)),++Wf;for(Sa=new I(Ob);Sa.b<Sa.d.H();)ua=(t(Sa.b<Sa.d.H()),Sa.d.R(Sa.c=Sa.b++)),ua==Ra?(Rh(ua,!0),N(ua.b,"de.l3s.boilerpipe/VERY_LIKELY_CONTENT")):(Rh(ua,!1),N(ua.b,"de.l3s.boilerpipe/MIGHT_BE_CONTENT"));if($l.a&&-1!=Dc){var am=Dc,Ua,Jj,Zf,$f;$f=w(fi(J(Ra.j,J(Ra.i,Ra.i.b.length-1).a)));
for(Zf=new Ie(Ob,am+1);Zf.O();)Ua=Zf.P(),Jj=w(gi(J(Ua.j,J(Ua.i,0).a))),w($f)==w(Jj)&&(Rh(Ua,!0),N(Ua.b,"SIBLING_OF_MAIN_CONTENT"),$f=w(fi(J(Ua.j,J(Ua.i,Ua.i.b.length-1).a))));var bm=Dc,Va,Kj,ag,Pb;ag=w(gi(J(Ra.j,J(Ra.i,0).a)));for(Pb=new Ie(Ob,bm);0<Pb.b;)Va=(t(0<Pb.b),J(Pb.a,Pb.c=--Pb.b)),Kj=w(fi(J(Va.j,J(Va.i,Va.i.b.length-1).a))),w(ag)==w(Kj)&&(Rh(Va,!0),N(Va.b,"SIBLING_OF_MAIN_CONTENT"),ag=w(gi(J(Va.j,J(Va.i,0).a))))}E=!0}Mh(A,E,"Keep Largest Block");var Dd,nb,Ed,Qb,Wa,Xa,Ec;Ed=0;nb=Ec=-1;for(Xa=
new I(A.a);Xa.b<Xa.d.H();)Qb=(t(Xa.b<Xa.d.H()),Xa.d.R(Xa.c=Xa.b++)),-1==nb&&O(Qb.b,"de.l3s.boilerpipe/TITLE")&&(Ec=Ed,nb=-1),-1==nb&&Qb.a&&(nb=Ed),++Ed;if(nb<=Ec||-1==Ec)E=!1;else{Dd=!1;for(Wa=new I(new Je(A.a,Ec,nb));Wa.b<Wa.d.H();)Qb=(t(Wa.b<Wa.d.H()),Wa.d.R(Wa.c=Wa.b++)),O(Qb.b,"de.l3s.boilerpipe/MIGHT_BE_CONTENT")&&(Dd|=Rh(Qb,!0));E=Dd}Mh(A,E,"Expand Title to Content");var bg,Fd,Da,Ya,Za;bg=!1;Fd=-1;for(Za=new I(A.a);Za.b<Za.d.H();)if(Da=(t(Za.b<Za.d.H()),Za.d.R(Za.c=Za.b++)),Da.a&&O(Da.b,"de.l3s.boilerpipe/VERY_LIKELY_CONTENT")){Fd=
Da.f;break}if(-1==Fd)E=!1;else{for(Ya=new I(A.a);Ya.b<Ya.d.H();)Da=(t(Ya.b<Ya.d.H()),Ya.d.R(Ya.c=Ya.b++)),!Da.a&&100<=Da.d&&Da.f==Fd&&(Rh(Da,!0),bg=!0);E=bg}Mh(A,E,"Largest Block Same Tag Level -\x3e Content");var cg,Gd,Ea,$a;cg=!1;Gd=aa;for($a=new I(A.a);$a.b<$a.d.H();)Ea=(t($a.b<$a.d.H()),$a.d.R($a.c=$a.b++)),Ea.a&&O(Ea.b,"de.l3s.boilerpipe/VERY_LIKELY_CONTENT")?Gd=Ea.f:Ea.f>Gd&&O(Ea.b,"de.l3s.boilerpipe/MIGHT_BE_CONTENT")&&O(Ea.b,"de.l3s.boilerpipe/LI")&&0==Ea.c?(Rh(Ea,!0),cg=!0):Gd=aa;E=cg;Mh(A,
E,"List at end filter");var cm=c.d,dg,Hd,eg,ab;Hd=0;for(ab=new I(A.a);ab.b<ab.d.H();)eg=(t(ab.b<ab.d.H()),ab.d.R(ab.c=ab.b++)),eg.a&&(Hd+=eg.d);dg=Hd;if(void 0==dg)throw new TypeError;cm[1]=dg;var dm,bb;for(bb=new I(A.a);bb.b<bb.d.H();){var Id=dm=(t(bb.b<bb.d.H()),bb.d.R(bb.c=bb.b++)),Lj=void 0,cb=void 0,fg=void 0;if(Id.a)for(cb=new I(Id.i);cb.b<cb.d.H();)Lj=(t(cb.b<cb.d.H()),cb.d.R(cb.c=cb.b++)),fg=J(Id.j,Lj.a),fg.o=!0,O(Id.b,"de.l3s.boilerpipe/TITLE")&&N(fg.d,"de.l3s.boilerpipe/TITLE")}var Fc,db,
Jd;Jd=!1;for(db=new I(uc.a.a);db.b<db.d.H();)Fc=(t(db.b<db.d.H()),db.d.R(db.c=db.b++)),Fc.o?Jd=!0:n(Fc,35)?Jd=!1:n(Fc,46)&&Jd&&(Fc.o=!0);var em=uc.a,gg,eb,hg;hg=new L;for(eb=new I(em.a);eb.b<eb.d.H();)gg=(t(eb.b<eb.d.H()),eb.d.R(eb.c=eb.b++)),gg.o&&gg.Bb(hg,!1);var fm=rd=hg,gm=uc.b,hm=$doc.documentElement;hi();var Rb,Kd,fb,Sb;Rb=new ii(fm,gm);Hh(new Ih(new ji(Rb)),hm);Sb=null;for(fb=new I(Rb.c);fb.b<fb.d.H();)if(Kd=(t(fb.b<fb.d.H()),fb.d.R(fb.c=fb.b++)),!Sb||Kd.b>Sb.b){if(Sb){var Oj=Rb.a,jg=void 0,
jg=ef(Oj,Sb.a);-1!=jg&&Oj.S(jg)}Sb=Kd}else{var Pj=Rb.a,kg=void 0,kg=ef(Pj,Kd.a);-1!=kg&&Pj.S(kg)}rd=Rb.a;var Qj=P()-Mb;if(void 0==Qj)throw new TypeError;c.e[3]=Qj;if(0==rd.b.length)qd="";else{Mb=P();var Gc=rd,lg,ea,Ld,mg,ng,Rj;ng=new ki(Gc);var og=(u(0,Gc.b.length),Gc.b[0]),Tb;for(Tb=og.parentNode;Tb&&9!=Tb.nodeType;og=Tb,Tb=Tb.parentNode);Hh(new Ih(ng),og);for(var Ub=ng.c,im=(u(0,Gc.b.length),Gc.b[0]);1==Ub.a.b&&Ub.b!=im&&3!=$e(Ub.a,0).b.nodeType;)Ub=$e(Ub.a,0);ea=li(Ub);if(1!=ea.nodeType)Hf="";
else{c.g=v(ea,"dir");var pg,Md,Nd,Od,Pd,qg;pg=ea.getElementsByTagName("A");for(Nd=0;Nd<pg.length;Nd++)Od=pg[Nd],Od.href.length&&(Od.href=Od.href);qg=ea.getElementsByTagName("VIDEO");for(Md=0;Md<qg.length;Md++)Pd=qg[Md],Pd.poster.length&&(Pd.poster=Pd.poster);if(ea.querySelectorAll){var Qd=ea.querySelectorAll("img,source,track,video"),Rd;for(Rd in Qd)Qd[Rd].src&&(Qd[Rd].src=Qd[Rd].src)}if(1==ea.nodeType)for(lg=ea.getElementsByTagName("IMG"),Ld=0;Ld<lg.length;Ld++)mg=v(lg[Ld],"src"),!mg.length||K(c.c,
mg);var rg;Vl?(Ch(ea),$doc.body.appendChild(ea),Rj=ea.innerText,$doc.body.removeChild(ea),rg=Rj):rg=ea.innerHTML;Hf=rg}var Uj=P()-Mb;if(void 0==Uj)throw new TypeError;c.e[4]=Uj;if(4<=Q){for(wc=0;wc<c.e[6].length;wc++){var Vj=c.e;if(wc>=Vj[6].length)throw new RangeError;vc=Vj[6][wc];if(void 0===vc[1])throw new TypeError;var jm="Timing: "+vc[1]+" \x3d ";if(void 0===vc[2])throw new TypeError;R(jm+vc[2])}var Wj=c.e;if(void 0===Wj[1])throw new TypeError;var km="Timing: MarkupParsingTime \x3d "+Wj[1]+"\nTiming: DocumentConstructionTime \x3d ",
Xj=c.e;if(void 0===Xj[2])throw new TypeError;var lm=km+Xj[2]+"\nTiming: ArticleProcessingTime \x3d ",Yj=c.e;if(void 0===Yj[3])throw new TypeError;var mm=lm+Yj[3]+"\nTiming: FormattingTime \x3d ",Zj=c.e;if(void 0===Zj[4])throw new TypeError;R(mm+Zj[4])}qd=Hf}if(void 0==qd)throw new TypeError;b[1]=qd;if(void 0==b)throw new TypeError;f[2]=b;var ak=((null==c.g||!c.g.length)&&(c.g="auto"),c.g);if(void 0==ak)throw new TypeError;f[9]=ak;for(y=new I(c.c);y.b<y.d.H();){z=(t(y.b<y.d.H()),y.d.R(y.c=y.b++));
var nm=(Ef={},f[10].push(Ef),Ef);if(void 0==z)throw new TypeError;nm[1]=z}var sg;if(void 0!=a[3]){if(void 0===a[3])throw new TypeError;sg=a[3]}else sg=$wnd.location.href;e=sg;p=c.e;g=P();mi();od={};var ck=$doc.documentElement,ob,tg,ug,vg,Fa,wg,Hc,C,gb,Y,xg,r,hb,Vb,Sd,Td,yg,Wb,Xb,Yb,Ud,Vd,dk,Ga,zg,ek,fk;3<=Q&&xe(ni);Fa=e.replace(RegExp("\\/[^/]*$","gi"),"");ek=e.replace(RegExp("\\/$","gi"),"");ob=ck.getElementsByTagName("A");Vd=new Af;var Ag;var Bg,Cg;Cg=ck.getElementsByTagName("BASE");if(0==Cg.length)Ag=
e;else{Bg=oi(e);var om=v(Cg[0],"href");Bg.setAttribute("href",om);Ag=Bg.href}ug=oi(Ag);var pm=dd(e,":\\/\\/")[0]+"://",hk,Ic=e,Ic=dd(Ic,":\\/\\/")[1];hk=-1==Ic.indexOf("/")?Ic:dd(Ic,"\\/")[0];tg=pm+hk+"/";var qm="^"+tg.replace(/[\-\[\]{}()*+?.,\\\^$|#\s]/g,"\\$\x26")+".*\\d";dk=RegExp(qm,"i");for(Hc=0;Hc<ob.length;Hc++)if(C=ob[Hc],fk=v(C,"href"),ug.setAttribute("href",fk),Y=ug.href,dk.test(Y))if(zg=(C.offsetWidth||0)|0,wg=(C.offsetHeight||0)|0,0==zg||0==wg)S(C,"ignored: sz\x3d"+zg+"x"+wg);else if(pi(C))if(Y=
Y.replace(qi,""),S(C,"-\x3e "+Y),D(Y,ek)||D(Y,Fa))S(C,"ignored: same as current or folder url "+Fa);else if(hb=C.innerText,ri.test(hb)||25<hb.length)S(C,"ignored: one of extra");else if(xg=Y,Y.substr(0,Fa.length)===Fa&&(xg=ed(Y,Fa.length)),si.test(xg)){r=new ti(Hc,hb,Y);N(Vd,r);0!=Y.indexOf(Fa)&&(r.d-=25,S(C,"score\x3d"+r.d+": not part of folder url "+Fa));gb=hb+" "+(C.className||"")+" "+C.id;S(C,"txt+class+id\x3d"+gb);ui.test(gb)&&(r.d+=50,S(C,"score\x3d"+r.d+": has next"));vi.test(gb)&&(r.d+=25,
S(C,"score\x3d"+r.d+": has pag* word"));wi.test(gb)&&!ui.test(r.c)&&(r.d-=65,S(C,"score\x3d"+r.d+": has first|last but no next regex"));if(xi.test(gb)||ri.test(gb))r.d-=50,S(C,"score\x3d"+r.d+": has neg or extra regex");yi.test(gb)&&(r.d-=200,S(C,"score\x3d"+r.d+": has opp of next regex"));Sd=Ud=!1;for(Xb=w(C);Xb&&(!Ud||!Sd);)Yb=(Xb.className||"")+" "+Xb.id,!Ud&&vi.test(Yb)&&(r.d+=25,Ud=!0,S(C,"score\x3d"+r.d+": posParent - "+Yb)),Sd||!xi.test(Yb)||zi.test(Yb)||(r.d-=25,Sd=!0,S(C,"score\x3d"+r.d+
": negParent - "+Yb)),Xb=w(Xb);if(Ai.test(Y)||vi.test(Y))r.d+=25,S(C,"score\x3d"+r.d+": has paging info");ri.test(Y)&&(r.d-=15,S(C,"score\x3d"+r.d+": has extra regex"));10<hb.length&&(r.d-=hb.length,S(C,"score\x3d"+r.d+": text too long"));Vb=Bi(hb);0<Vb&&(1==Vb?r.d-=10:r.d+=0>10-Vb?0:10-Vb,S(C,"score\x3d"+r.d+": linktxt is a num ("+Vb+")"));for(var qb=e,rb=Y,pk=C,Ha=void 0,Yd=void 0,Zd=void 0,Ha=tg.length;Ha<Yc(qb.length,rb.length)&&qb.charCodeAt(Ha)==rb.charCodeAt(Ha);Ha++);qb=qb.substr(Ha,qb.length-
Ha);rb=rb.substr(Ha,rb.length-Ha);S(pk,"remains: "+qb+", "+rb);Yd=Bi(rb);Zd=Bi(qb);S(pk,"remains: "+Zd+", "+Yd);(vg=0<Zd&&0<Yd?Uc(Yd-Zd):null)&&1==vg.a&&(r.d+=25,S(C,"score\x3d"+r.d+": diff \x3d "+vg))}else S(C,"ignored: no number beyond folder url "+Fa);else S(C,"ignored: invisible");else S(C,"ignored: not prefix + num");Ga=null;if(0!=Vd.a.b)for(yg=Le(new Ne(Vd.a));De(yg.a);)Td=Ee(yg.a).U(),50<=Td.d&&(!Ga||Ga.d<Td.d)&&(Ga=Td);Wb=null;Ga&&(Wb=Ga.a.replace(RegExp("\\/$","gi"),""),S(ob[Ga.b],"found: score\x3d"+
Ga.d+", txt\x3d["+Ga.c+"], "+Wb));if(3<=Q){var Jc,$d,ib,Kc,ae;R("numLinks\x3d"+ob.length+", found next: "+(null!=Wb?Wb:"null"));for(Jc=0;Jc<ob.length;Jc++){$d=ob[Jc];ib=$d.innerText;ae=dd(ib,"\\s+");ib="";for(Kc=0;Kc<ae.length;Kc++)ib+=ae[Kc],Kc<ae.length-1&&(ib+=" ");R(Jc+")"+$d.href+", txt\x3d["+ib+"], dbg\x3d["+Xd(ni,$d)+"]")}}pd=Wb;if(null!=pd){if(void 0==pd)throw new TypeError;od[1]=pd}if(void 0==od)throw new TypeError;f[3]=od;Ci(g,p,"Pagination");var T=c.f,sb,jb,be,ce,tb,ub,Gg,la,Hg,Ig,Jg;la=
(Hg={},Hg[9]=[],Hg);var de,ee;ee=!1;for(de=0;de<T.a.b.length&&!ee;de++)ee=J(T.a,de).ub();if(!ee){var qk=yh(T);if(void 0==qk)throw new TypeError;la[1]=qk;var Kg,fe,ge;ge="";for(fe=0;fe<T.a.b.length&&!ge.length;fe++)ge=J(T.a,fe).sb();Kg=ge;if(void 0==Kg)throw new TypeError;la[2]=Kg;var Lg,he,ie;ie="";for(he=0;he<T.a.b.length&&!ie.length;he++)ie=J(T.a,he).tb();Lg=ie;if(void 0==Lg)throw new TypeError;la[3]=Lg;var Mg,je,ke;je="";for(ke=0;ke<T.a.b.length&&!je.length;ke++)je=J(T.a,ke).ob();Mg=je;if(void 0==
Mg)throw new TypeError;la[4]=Mg;var Ng,le,me;me="";for(le=0;le<T.a.b.length&&!me.length;le++)me=J(T.a,le).qb();Ng=me;if(void 0==Ng)throw new TypeError;la[5]=Ng;var Og,ne,oe;ne="";for(oe=0;oe<T.a.b.length&&!ne.length;oe++)ne=J(T.a,oe).nb();Og=ne;if(void 0==Og)throw new TypeError;la[6]=Og;var Pg,pe,qe;pe="";for(qe=0;qe<T.a.b.length&&!pe.length;qe++)pe=J(T.a,qe).mb();Pg=pe;if(void 0==Pg)throw new TypeError;la[7]=Pg;var re,se;re=null;for(se=0;se<T.a.b.length&&!re;se++)re=J(T.a,se).lb();if(sb=re){jb=(Ig=
{},Ig[5]=[],Ig);var rk=sb.d;if(void 0==rk)throw new TypeError;jb[1]=rk;var sk=sb.c;if(void 0==sk)throw new TypeError;jb[2]=sk;var tk=sb.b;if(void 0==tk)throw new TypeError;jb[3]=tk;var uk=sb.e;if(void 0==uk)throw new TypeError;jb[4]=uk;for(ce=0;ce<sb.a.length;ce++)jb[5].push(sb.a[ce]);if(void 0==jb)throw new TypeError;la[8]=jb}var te,ue;ue=null;for(te=0;te<T.a.b.length&&!(ue=J(T.a,te).pb(),0<ue.length);te++);Gg=ue;for(be=0;be<Gg.length;be++){tb=Gg[be];ub=(Jg={},la[9].push(Jg),Jg);var vk=tb.e;if(void 0==
vk)throw new TypeError;ub[1]=vk;var wk=tb.c;if(void 0==wk)throw new TypeError;ub[2]=wk;var xk=tb.d;if(void 0==xk)throw new TypeError;ub[3]=xk;var yk=tb.a;if(void 0==yk)throw new TypeError;ub[4]=yk;var zk=tb.f;if(void 0==zk)throw new TypeError;ub[5]=zk;var Ak=tb.b;if(void 0==Ak)throw new TypeError;ub[6]=Ak}}if(void 0==la)throw new TypeError;f[5]=la;var Bk=P()-l;if(void 0==Bk)throw new TypeError;p[5]=Bk;if(void 0==p)throw new TypeError;f[6]=p;var Ck=c.d;if(void 0==Ck)throw new TypeError;f[8]=Ck;d=(dj=
{},dj);var Dk=(ej=Di,Di="",ej);if(void 0==Dk)throw new TypeError;d[1]=Dk;if(void 0==d)throw new TypeError;f[7]=d;return f}k(159,1,{},function(){});s(159);function Ei(a){var b;for(b=new L;a;)b.b[b.b.length]=a,a=a.parentNode;return b}function P(){return window.performance?window.performance.now():Date.now()}function Fi(a,b){var c,d;if(null==a)return!1;c=$doc.createElement("a");c.href=a;c=qc(c,"host");d=("."+b).length;return("."+c).substr(("."+c).length-d,d)==="."+b}
function pi(a){var b;b=getComputedStyle(a,null);a=parseFloat(b.opacity);return!("none"===b.display||"hidden"===b.visibility||0==a)}function Gi(a){var b,c,d,e;if(null==a||!a.length)return new M;e=new M;a=dd(a,"\x26");for(c=0;c<a.length;c++);c=0;for(d=a.length;c<d;++c)if(b=a[c],b=dd(b,"\x3d"),1<b.length){var f=e,g=b[0];if(null==b[1])throw new Zc("encodedURL cannot be null");H(f,g,decodeURI(b[1]))}return e}
function Hh(a,b){var c,d;if(a.a.kb(b)){if(d=b.firstChild)for(;d!=b;){c=!1;if(a.a.kb(d)){if(c=d.firstChild){d=c;continue}c=!0}for(;d!=b;){c&&a.a.jb(d);if(c=d.nextSibling){d=c;break}d=d.parentNode;c=!0}}a.a.jb(b)}}function Ih(a){this.a=a}k(27,1,{},Ih);s(27);function Hi(a){this.a=new L;K(this.a,new Ii);K(this.a,new Ji);K(this.a,new Ki(a));K(this.a,new Li)}k(120,1,{},Hi);s(120);function Mi(a){var b;a.b="";(b=a.j.querySelector(".byline-name"))&&(a.b=b.textContent)}
function Ni(a){this.j=a;this.a=a.getElementsByTagName("META")}k(97,1,{},Ni);_.lb=function(){var a,b;a=new Oi;if(null==this.d){var c;this.d="";if(b=this.j.querySelector(".dateline"))this.d=b.textContent;else for(b=0;b<this.a.length;b++)if(c=this.a[b],D(c.name,"displaydate")){this.d=c.content;break}}a.d=this.d;b=(null==this.b&&Mi(this),this.b);a.a=b.length?x(Db(m,1),da,2,4,[b]):B(m,2,0,4);return a};_.mb=function(){return null==this.b&&Mi(this),this.b};
_.nb=function(){if(null==this.c){var a,b;this.c="";for(a=0;a<this.a.length;a++)if(b=this.a[a],D(b.name,"copyright")){this.c=b.content;break}}return this.c};_.ob=function(){return""};
_.pb=function(){if(!this.f){var a,b,c,d,e;this.f=new L;a=this.j.getElementsByTagName("IMG");for(c=0;c<a.length;c++){e=a[c];var f=d=b=void 0,g=void 0;b=void 0;b=w(e);if(D("FIGURE",b.tagName)){if(d=b.getElementsByTagName("FIGCAPTION"),g=d.length,b="",0<g&&2>=g)for(f=0;f<g&&!b.length;f++)b=d[f].innerText}else b="";(d=null!=b&&b.length)||(d=d=void 0,d=e.width,400>d?d=!1:(d/=e.height,d=1.3<=d&&3>=d));d&&(d=new Pi,d.e=e.src,d.a=b,d.f=e.width,d.b=e.height,K(this.f,d))}}return gf(this.f,B(Qi,19,this.f.b.length,
0))};_.qb=function(){if(null==this.i){var a,b,c;this.i="";a=this.j.getElementsByTagName("*");for(c=0;c<a.length&&!this.i.length;c++)b=a[c],this.i=v(b,"publisher"),!this.i.length&&(this.i=v(b,"source_organization"))}return this.i};_.rb=function(){if(null==this.k){var a,b;this.k="";if(0!=this.a.length&&(a=this.j.getElementsByTagName("TITLE"),0!=a.length))for(a=0;a<this.a.length;a++)if(b=this.a[a],D(b.name,"title")){this.k=b.content;break}}return this.k};_.sb=function(){return""};_.tb=function(){return""};
_.ub=function(){if(!this.e){var a,b;this.e=!0;for(a=0;a<this.a.length;a++)if(b=this.a[a],D(b.name,"IE_RM_OFF")){this.g=D(b.content,"true");break}}return this.g};_.a=null;_.b=null;_.c=null;_.d=null;_.e=!1;_.f=null;_.g=!1;_.i=null;_.j=null;_.k=null;s(97);function Bi(a){return parseInt(a,10)|0}function Ci(a,b,c){var d;if(b){b=(d={},b[6].push(d),d);if(void 0==c)throw new TypeError;b[1]=c;a=P()-a;if(void 0==a)throw new TypeError;b[2]=a}}
function R(a){null==a&&(a="");-1==a.indexOf("[0;")&&-1==a.indexOf("[1;")||(a+="\u001b[0m");Ri||null==$wnd.console||"function"!=typeof $wnd.console.log&&"object"!=typeof $wnd.console.log||$wnd.console.log(a);Di+=a+"\n"}var Q=0,Di="",Ri=!1;function yh(a){var b,c;c="";for(b=0;b<a.a.b.length&&!c.length;b++)c=J(a.a,b).rb();return c}
function Bh(a,b){var c,d;this.b=b;this.a=new L;d=P();var e=this.b;Si();var f,g;try{g=P(),f=new Ti(a,e),Ci(g,e,"OpenGraphProtocolParser.parse"),c=f}catch(l){if(l=ec(l),n(l,7))c=null;else throw fc(l);}c&&K(this.a,c);Ci(d,this.b,"OpenGraphProtocolParser");d=P();K(this.a,new Ui(a,this.b));Ci(d,this.b,"SchemaOrgParserAccessor");d=P();K(this.a,new Ni(a));Ci(d,this.b,"IEReadingViewParser")}k(80,1,{},Bh);s(80);function Oi(){}k(43,1,{},Oi);_.a=null;_.b="";_.c="";_.d="";_.e="";s(43);function Pi(){}
k(19,1,{19:1},Pi);_.a="";_.b=0;_.c="";_.d="";_.e="";_.f=0;var Qi=s(19);function ki(a){this.b=new Vi(a);this.a=new L;this.d=new L}k(102,1,{},ki);_.jb=function(){this.a.S(this.a.b.length-1);this.d.S(this.d.b.length-1)};
_.kb=function(a){if(!this.b.a)return!1;K(this.a,a);K(this.d,null);if(1==this.d.b.length){this.c=new Wi(a);var b=this.d,c=this.c;u(0,b.b.length);b.b[0]=c}if(Xi(this.b,a))for(a=0;a<this.a.b.length;a++)if(null==J(this.d,a)){var b=this.d,c=a,d=new Wi(J(this.a,a));u(c,b.b.length);b.b[c]=d;b=J(this.d,a-1);c=J(this.d,a);Zg(b.a,c)}return!0};s(102);
function li(a){var b,c;c=a.b.cloneNode(!1);1==a.b.nodeType&&(b=getComputedStyle(a.b,null).direction,c.setAttribute("dir",b));for(a=af(a.a,0);a.b!=a.d.c;)b=(t(a.b!=a.d.c),a.c=a.b,a.b=a.b.a,++a.a,a.c.c),b=li(b),c.appendChild(b);return c}function Wi(a){this.b=a;this.a=new bh}k(57,1,{},Wi);s(57);function Si(){Si=h;Yi=RegExp("((\\w+):\\s+(http:\\/\\/ogp.me\\/ns(\\/\\w+)*#))\\s*","gi");Zi=/^xmlns:(\w+)/i;$i=/^http:\/\/ogp.me\/ns(\/\w+)*#/i}
function aj(a,b,c){null!=c&&c.length?(c=c.substr(1,c.length-1),"profile"===c?nf(a.c,(bj(),gj),b):"article"===c&&nf(a.c,(bj(),hj),b)):nf(a.c,(bj(),kj),b)}
function Ti(a,b){var c,d;this.b=new lj;this.d=new mj;this.a=new nj;this.e=x(Db(oj,1),da,10,0,[new pj("title",(bj(),kj),null),new pj("type",kj,null),new pj("url",kj,null),new pj("description",kj,null),new pj("site_name",kj,null),new pj("image",kj,this.b),new pj("image:",kj,this.b),new pj("first_name",gj,this.d),new pj("last_name",gj,this.d),new pj("section",hj,this.a),new pj("published_time",hj,this.a),new pj("modified_time",hj,this.a),new pj("expiration_time",hj,this.a),new pj("author",hj,this.a)]);
this.f=new M;this.c=new qf(qj);this.g=b;d=P();var e,f,g;c="";D("HTML",a.tagName)&&(c=v(a,"prefix"));c.length||(g=a.getElementsByTagName("HEAD"),1==g.length&&(c=v(g[0],"prefix")));if(c.length)for(Yi.lastIndex=0;;){g=Yi.exec(c);if(!g)break;aj(this,g[2],g[4])}else for(c=a.attributes,g=0;g<c.length;g++)if(f=c[g],e=f.nodeName.toLowerCase(),e=Zi.exec(e))f=f.nodeValue,(f=$i.exec(f))&&aj(this,e[1],f[1]);null==lf(this.c,(bj(),kj))&&nf(this.c,kj,"og");null==lf(this.c,gj)&&nf(this.c,gj,"profile");null==lf(this.c,
hj)&&nf(this.c,hj,"article");Ci(d,this.g,"OpenGraphProtocolParser.findPrefixes");d=P();var l,p;if("function"==typeof a.querySelectorAll){e="";for(g=new tf((new sf(this.c)).a);vf(g.a);)c=(g.b=wf(g.a),new xf(g.c,g.b)),e+='meta[property^\x3d"'+c.b.b[c.a.b]+'"],';e=e.substr(0,e.length-1-0);c=a.querySelectorAll(e)}else c=a.getElementsByTagName("META");for(g=0;g<c.length;g++)for(f=c[g],p=v(f,"property").toLowerCase(),e=0;e<this.e.length;e++){l=lf(this.c,this.e[e].c)+":";var z=l+this.e[e].a;p.substr(0,z.length)===
z&&(p=ed(p,l.length),l=!0,this.e[e].b&&(l=this.e[e].b.vb(p,f.content,this.f)),l&&H(this.f,this.e[e].a,f.content))}Ci(d,this.g,"OpenGraphProtocolParser.parseMetaTags");d=P();c=this.b;if(0!=c.a.b.length)for(g=c.a.b.length-1;0<=g;g--)e=J(c.a,g)[0],null!=e&&e.length||c.a.S(g);Ci(d,this.g,"OpenGraphProtocolParser.imageParser.verify");d=P();c=lf(this.c,kj)+":";if(!(F(this.f,"title")?G(this.f,"title"):"").length)throw new Fb('Required "'+c+'title" property is missing.');if(!(F(this.f,"type")?G(this.f,"type"):
"").length)throw new Fb('Required "'+c+'type" property is missing.');if(!(F(this.f,"url")?G(this.f,"url"):"").length)throw new Fb('Required "'+c+'url" property is missing.');if(0==rj(this.b).length)throw new Fb('Required "'+c+'image" property is missing.');Ci(d,this.g,"OpenGraphProtocolParser.checkRequired")}k(92,1,{},Ti);
_.lb=function(){var a;a=new Oi;a.d=F(this.f,"published_time")?G(this.f,"published_time"):"";a.c=F(this.f,"modified_time")?G(this.f,"modified_time"):"";a.b=F(this.f,"expiration_time")?G(this.f,"expiration_time"):"";a.e=F(this.f,"section")?G(this.f,"section"):"";var b;b=this.a;b=gf(b.a,B(m,2,b.a.b.length,4));a.a=b;return a.e.length||a.d.length||a.c.length||a.b.length||0!=a.a.length?a:null};
_.mb=function(){var a;var b=this.f;this.d.b?(a=b.c.bb("first_name"),null==a&&(a=""),b=b.c.bb("last_name"),null!=b&&a.length&&b.length&&(a+=" "),a+=b):a="";return a};_.nb=function(){return""};_.ob=function(){return F(this.f,"description")?G(this.f,"description"):""};_.pb=function(){return rj(this.b)};_.qb=function(){return F(this.f,"site_name")?G(this.f,"site_name"):""};_.rb=function(){return F(this.f,"title")?G(this.f,"title"):""};
_.sb=function(){var a;a=F(this.f,"type")?G(this.f,"type"):"";return D(a,"article")?"Article":""};_.tb=function(){return F(this.f,"url")?G(this.f,"url"):""};_.ub=function(){return!1};var Zi,$i,Yi;s(92);function nj(){this.b=!1;this.a=new L}k(95,1,{},nj);_.vb=function(a,b,c){this.b||(c=c.c.bb("type"),this.b=null!=c&&D(c,"article"));return this.b?"author"===a?(K(this.a,b),!1):!0:!1};_.b=!1;s(95);
function rj(a){var b,c,d,e;e=B(Qi,19,a.a.b.length,0);for(b=0;b<a.a.b.length;b++)c=J(a.a,b),d=new Pi,e[b]=d,d.e=null!=c[1]&&c[1].length?c[1]:c[0],null!=c[2]&&(d.c=c[2]),null!=c[3]&&(d.d=c[3]),null!=c[4]&&(d.f=Bi(c[4])),null!=c[5]&&(d.b=Bi(c[5]));return e}function lj(){this.b=x(Db(m,1),da,2,4,"image image:url image:secure_url image:type image:width image:height".split(" "));this.a=new L}k(93,1,{},lj);
_.vb=function(a,b){var c,d;if("image"===a)d=B(m,2,this.b.length,4),d[0]=b,K(this.a,d);else for(0==this.a.b.length?(d=B(m,2,this.b.length,4),K(this.a,d)):d=J(this.a,this.a.b.length-1),c=1;c<this.b.length;c++)if(a===this.b[c]){d[c]=b;break}return!1};s(93);function bj(){bj=h;kj=new uj("OG",0);gj=new uj("PROFILE",1);hj=new uj("ARTICLE",2)}function uj(a,b){this.a=a;this.b=b}k(28,12,{3:1,15:1,12:1,28:1},uj);var hj,kj,gj,qj=Bb(28,function(){bj();return x(Db(qj,1),da,28,0,[kj,gj,hj])});
function mj(){this.b=this.a=!1}k(94,1,{},mj);_.vb=function(a,b,c){this.a||(a=c.c.bb("type"),this.b=null!=a&&D(a,"profile"),this.a=!0);return this.b};_.a=!1;_.b=!1;s(94);function pj(a,b,c){this.a=a;this.c=b;this.b=c}k(10,1,{10:1},pj);_.a=null;_.b=null;var oj=s(10);function Xi(a,b){if(b!=a.a)return!1;var c=a.b;a.a=c.b<c.d.H()?Ge(a.b):null;return!0}function Vi(a){this.b=new I(a);0==a.b.length||(this.a=Ge(this.b))}k(64,1,{},Vi);s(64);
function mi(){mi=h;ui=RegExp("(next|weiter|continue|\x3e([^\\|]|$)|\u00bb([^\\|]|$))","i");yi=RegExp("(prev|early|old|new|\x3c|\u00ab)","i");zi=/article|body|content|entry|hentry|main|page|pagination|post|text|blog|story/i;xi=RegExp("combx|comment|com-|contact|foot|footer|footnote|masthead|media|meta|outbrain|promo|related|shoutbox|sidebar|sponsor|shopping|tags|tool|widget","i");ri=/print|archive|comment|discuss|e[\-]?mail|share|reply|all|login|sign|single|as one|article/i;vi=/pag(e|ing|inat)/i;Ai=
/p(a|g|ag)?(e|ing|ination)?(=|\/)[0-9]{1,2}$/i;wi=/(first|last)/i;qi=/\/?(#.*)?$/;si=/\d/;ni=new M}function S(a,b){var c;3>Q||(c="",Cd(ni,a)&&(c=Xd(ni,a)),!c.length||(c+="; "),ve(ni,a,c+b))}function oi(a){var b,c;c=$doc.implementation.createHTMLDocument();b=c.createElement("base");b.href=a;(c.head||c.getElementsByTagName("head")[0]).appendChild(b);a=c.createElement("a");c.body.appendChild(a);return a}var ri,wi,qi,Ai,xi,ui,si,vi,zi,yi,ni;function ti(a,b,c){this.b=a;this.d=0;this.c=b;this.a=c}
k(79,1,{},ti);_.b=-1;_.d=0;s(79);function hi(){hi=h;vj=new Af;N(vj,"BR");N(vj,"FIGURE");N(vj,"IMG");N(vj,"VIDEO")}function ii(a,b){var c;this.e=new Vi(a);this.d=b;this.a=new L;c=null;a&&0<a.b.length&&(c=(u(0,a.b.length),a.b[0]));this.b=new Hi(c);this.c=new L}k(87,1,{},ii);var vj;s(87);function ji(a){this.b=a;this.a=!1}k(88,1,{},ji);_.jb=function(){};
_.kb=function(a){var b,c;if(!this.b.e.a&&!this.a)return!1;(b=Xi(this.b.e,a))&&K(this.b.a,a);switch(a.nodeType){case 3:return this.a=b||this.a&&!/\S/.test(a.nodeValue),!1;case 1:if(b)return!0;if(O(this.b.d,a))return!1;if(this.a&&O((hi(),vj),a.tagName)){var d;2>Q||(b=this.b.a.b.length-1,d=0>b?null:J(this.b.a,b),R("Adding [tag\x3d"+a.tagName+", id\x3d"+a.id+", parent\x3d"+w(a).tagName+(D("IMG",a.tagName)?", src\x3d"+v(a,"src"):"")+(D("IMG",a.tagName)?"":", class\x3d"+v(a,"class"))+", sz\x3d"+((a.offsetWidth||
0)|0)+"x"+((a.offsetHeight||0)|0)+"] after node "+b+(d?" [name\x3d"+d.nodeName+", value\x3d"+d.nodeValue+", parent\x3d"+w(d).tagName+"]":"")));return c=new wj(this.b),Hh(new Ih(c),a),!1}if("IMG"===a.tagName){d=0;if(a&&"IMG"===a.tagName)for(b=new I(this.b.b.a);b.b<b.d.H();)c=(t(b.b<b.d.H()),b.d.R(b.c=b.b++)),d+=c.zb(a);2>Q||(a?R("FINAL SCORE: "+d+" : "+v(a,"src")):R("Null image attempting to be scored!"));c=d;25<c&&(K(this.b.c,new yj(a,c)),K(this.b.a,a))}return!0;default:return!1}};_.a=!1;s(88);
function wj(a){this.a=a}k(89,1,{},wj);_.jb=function(){};_.kb=function(a){Xi(this.a.e,a);switch(a.nodeType){case 3:return K(this.a.a,a),!1;case 1:if(O(this.a.d,a))return!1;K(this.a.a,a);return!0;default:return!1}};s(89);function yj(a,b){this.a=a;this.b=b}k(90,1,{},yj);_.b=0;s(90);
function Aj(){Aj=h;Bj=new M;H(Bj,"http://schema.org/ImageObject",(U(),Cj));H(Bj,"http://schema.org/Article",Dj);H(Bj,"http://schema.org/BlogPosting",Dj);H(Bj,"http://schema.org/NewsArticle",Dj);H(Bj,"http://schema.org/ScholarlyArticle",Dj);H(Bj,"http://schema.org/TechArticle",Dj);H(Bj,"http://schema.org/Person",Ej);H(Bj,"http://schema.org/Organization",Gj);H(Bj,"http://schema.org/Corporation",Gj);H(Bj,"http://schema.org/EducationalOrganization",Gj);H(Bj,"http://schema.org/GovernmentOrganization",
Gj);H(Bj,"http://schema.org/NGO",Gj);V=new M;H(V,"IMG","SRC");H(V,"AUDIO","SRC");H(V,"EMBED","SRC");H(V,"IFRAME","SRC");H(V,"SOURCE","SRC");H(V,"TRACK","SRC");H(V,"VIDEO","SRC");H(V,"A","HREF");H(V,"LINK","HREF");H(V,"AREA","HREF");H(V,"META","CONTENT");H(V,"TIME","DATETIME");H(V,"OBJECT","DATA");H(V,"DATA","VALUE");H(V,"METER","VALUE")}function Hj(a){var b,c,d;b=new L;for(c=0;c<a.c.b.length;c++)d=J(a.c,c),d.c==(U(),Dj)&&K(b,d);return b}
function Ij(a,b,c){var d,e;d=b.tagName;(D(d,"A")||D(d,"LINK"))&&D(v(b,"REL"),"author")&&c.D(b);d=b.childNodes;for(e=0;e<d.length;e++)b=d[e],1==b.nodeType&&Ij(a,b,c)}function Mj(a,b,c){var d,e;(b.hasAttribute("ITEMPROP")||b.hasAttribute("ITEMSCOPE"))&&c.D(b);d=b.childNodes;for(e=0;e<d.length;e++)b=d[e],1==b.nodeType&&Mj(a,b,c)}function Nj(a,b){var c,d;d=null;for(c=b;c;){c=w(c);if(!c)break;if(c.hasAttribute("ITEMSCOPE")&&c.hasAttribute("ITEMTYPE")){Cd(a.b,c)&&(d=Xd(a.b,c));break}}return d}
function Sj(a,b,c){var d,e,f,g,l;e=null;d=b.hasAttribute("ITEMSCOPE")&&b.hasAttribute("ITEMTYPE");if(c){var p;f=v(b,"ITEMPROP");f.length?(p=dd(f,"\\s+"),f=0<p.length?p:x(Db(m,1),da,2,4,[f])):f=B(m,2,0,4)}else f=B(m,2,0,4);if(d){a:{var z;switch((z=v(b,"ITEMTYPE"),F(Bj,z)?G(Bj,z):(U(),Tj)).b){case 0:e=new bk;break;case 1:e=new gk;break;case 2:e=new ik;break;case 3:e=new jk;break;case 4:e=new kk;break;default:e=null;break a}}!e||e.c==(U(),Tj)||c&&c.c==(U(),Tj)&&0!=f.length||(K(a.c,e),ve(a.b,b,e))}if(0<
f.length&&c.c!=(U(),Tj)&&(!e||e.c!=(U(),Tj)))for(a=0;a<f.length;a++)e?F(c.a,f[a])&&H(c.a,f[a],e):(d=c,z=f[a],p=(g="",l=b.tagName,F(V,l)&&(g=v(b,G(V,l))),!g.length&&(g=b.textContent),g),F(d.b,z)&&!G(d.b,z).length&&H(d.b,z,p))}
function lk(a,b){Aj();var c;this.c=new L;this.b=new M;this.d=b;c=P();var d,e,f;if("function"==typeof a.querySelectorAll){d=a.querySelectorAll("[ITEMPROP],[ITEMSCOPE]");Sj(this,a,null);for(f=0;f<d.length;f++)e=d[f],Sj(this,e,Nj(this,e));d=a.querySelectorAll("A[rel\x3dauthor],LINK[rel\x3dauthor]");for(f=0;f<d.length;f++)e=d[f],!this.a.length&&(this.a=mk(e))}else{d=new L;Mj(this,a,d);for(d=new I(d);d.b<d.d.H();)e=(t(d.b<d.d.H()),d.d.R(d.c=d.b++)),Sj(this,e,Nj(this,e));d=new L;Ij(this,a,d);for(d=new I(d);d.b<
d.d.H();)e=(t(d.b<d.d.H()),d.d.R(d.c=d.b++)),!this.a.length&&(this.a=mk(e))}Ci(c,this.d,"SchemaOrgParser.parse")}function nk(a,b){Aj();var c;c=a;a.length&&b.length&&(c+=" ");return c+b}function mk(a){var b,c;b="";c=a.tagName;(D(c,"A")||D(c,"LINK"))&&D(v(a,"REL"),"author")&&(b=a.textContent);return b}k(107,1,{},lk);_.a="";var V,Bj;s(107);function ok(a,b){return F(a.b,b)?G(a.b,b):""}
function Ek(a){this.c=a;this.b=new M;this.a=new M;H(this.b,"name","");H(this.b,"url","");H(this.b,"description","");H(this.b,"image","")}k(29,1,{});s(29);
function Fk(a,b){var c,d,e,f;c=F(a.b,b)?G(a.b,b):"";if(c.length)return c;(d=F(a.a,b)?G(a.a,b):null)&&(d.c==(U(),Ej)?c=(e=F(d.b,"name")?G(d.b,"name"):"",e.length?e:nk(F(d.b,"givenName")?G(d.b,"givenName"):"",F(d.b,"familyName")?G(d.b,"familyName"):"")):d.c==Gj&&(c=(f=F(d.b,"name")?G(d.b,"name"):"",f.length?f:F(d.b,"legalName")?G(d.b,"legalName"):"")));return c}
function gk(){Ek.call(this,(U(),Dj));H(this.b,"headline","");H(this.b,"publisher","");H(this.b,"copyrightHolder","");H(this.b,"copyrightYear","");H(this.b,"dateModified","");H(this.b,"datePublished","");H(this.b,"author","");H(this.b,"creator","");H(this.b,"articleSection","");ve(this.a,"publisher",null);ve(this.a,"copyrightHolder",null);ve(this.a,"author",null);ve(this.a,"creator",null);ve(this.a,"associatedMedia",null);ve(this.a,"encoding",null)}k(109,29,{},gk);s(109);
function bk(){Ek.call(this,(U(),Cj));H(this.b,"contentUrl","");H(this.b,"encodingFormat","");H(this.b,"caption","");H(this.b,"representativeOfPage","");H(this.b,"width","");H(this.b,"height","")}k(108,29,{},bk);s(108);function jk(){Ek.call(this,(U(),Gj));H(this.b,"legalName","")}k(111,29,{},jk);s(111);function ik(){Ek.call(this,(U(),Ej));H(this.b,"familyName","");H(this.b,"givenName","")}k(110,29,{},ik);s(110);
function U(){U=h;Cj=new Gk("IMAGE",0);Dj=new Gk("ARTICLE",1);Ej=new Gk("PERSON",2);Gj=new Gk("ORGANIZATION",3);Tj=new Gk("UNSUPPORTED",4)}function Gk(a,b){this.a=a;this.b=b}k(22,12,{3:1,15:1,12:1,22:1},Gk);var Dj,Cj,Gj,Ej,Tj,Hk=Bb(22,function(){U();return x(Db(Hk,1),da,22,0,[Cj,Dj,Ej,Gj,Tj])});function kk(){Ek.call(this,(U(),Tj))}k(112,29,{},kk);s(112);function Ui(a,b){this.a=new lk(a,b)}k(96,1,{},Ui);
_.lb=function(){var a;a=Hj(this.a);if(0==a.b.length)a=null;else{a=(u(0,a.b.length),a.b[0]);var b,c;b=new Oi;b.d=F(a.b,"datePublished")?G(a.b,"datePublished"):"";b.c=F(a.b,"dateModified")?G(a.b,"dateModified"):"";b.e=F(a.b,"articleSection")?G(a.b,"articleSection"):"";c=Fk(a,"author");!c.length&&(c=Fk(a,"creator"));b.a=c.length?x(Db(m,1),da,2,4,[c]):B(m,2,0,4);a=b}return a};
_.mb=function(){var a,b;b="";a=Hj(this.a);0!=a.b.length&&(a=(u(0,a.b.length),a.b[0]),b=Fk(a,"author"),!b.length&&(b=Fk(a,"creator")));return b.length?b:this.a.a};_.nb=function(){var a;a=Hj(this.a);0==a.b.length?a="":(a=(u(0,a.b.length),a.b[0]),a=nk(F(a.b,"copyrightYear")?G(a.b,"copyrightYear"):"",Fk(a,"copyrightHolder")),a=a.length?"Copyright "+a:a);return a};_.ob=function(){var a;a=Hj(this.a);return 0==a.b.length?"":ok((u(0,a.b.length),a.b[0]),"description")};
_.pb=function(){var a,b,c,d,e,f,g,l;g=new L;b=Hj(this.a);c=null;for(d=0;d<b.b.length;d++){a=(u(d,b.b.length),b.b[d]);if(!c&&(c=(e=F(a.a,"associatedMedia")?G(a.a,"associatedMedia"):null,!e&&(e=F(a.a,"encoding")?G(a.a,"encoding"):null),e&&e.c==(U(),Cj)?e:null)))continue;var p=f=void 0,p=F(a.b,"image")?G(a.b,"image"):"";p.length?(f=new Pi,f.e=p,a=f):a=null;a&&(g.b[g.b.length]=a)}d=this.a;b=new L;for(a=0;a<d.c.b.length;a++)e=J(d.c,a),e.c==(U(),Cj)&&K(b,e);d=!1;for(e=0;e<b.b.length;e++)f=(u(e,b.b.length),
b.b[e]),a=(l=new Pi,l.e=F(f.b,"contentUrl")?G(f.b,"contentUrl"):"",!l.e.length&&(l.e=F(f.b,"url")?G(f.b,"url"):""),l.d=F(f.b,"encodingFormat")?G(f.b,"encodingFormat"):"",l.a=F(f.b,"caption")?G(f.b,"caption"):"",l.f=Bi(F(f.b,"width")?G(f.b,"width"):""),l.b=Bi(F(f.b,"height")?G(f.b,"height"):""),l),f==c||!d&&D(F(f.b,"representativeOfPage")?G(f.b,"representativeOfPage"):"","true")?(d=!0,pc(0,g.b.length),g.b.splice(0,0,a)):g.b[g.b.length]=a;return gf(g,B(Qi,19,g.b.length,0))};
_.qb=function(){var a,b;b="";a=Hj(this.a);0!=a.b.length&&(a=(u(0,a.b.length),a.b[0]),b=Fk(a,"publisher"),!b.length&&(b=Fk(a,"copyrightHolder")));return b};_.rb=function(){var a,b,c;c="";a=Hj(this.a);for(b=0;b<a.b.length&&!c.length;b++)c=ok((u(b,a.b.length),a.b[b]),"headline");for(b=0;b<a.b.length&&!c.length;b++)c=ok((u(b,a.b.length),a.b[b]),"name");return c};_.sb=function(){return 0==Hj(this.a).b.length?"":"Article"};
_.tb=function(){var a;a=Hj(this.a);return 0==a.b.length?"":ok((u(0,a.b.length),a.b[0]),"url")};_.ub=function(){return!1};s(96);function zh(a){return(a=a.match(/(\S*[\w\u00C0-\u1FFF\u2C00-\uD7FF]\S*)/g))?a.length:0}
function Ik(){Ik=h;Jk=new M;H(Jk,"COLGROUP",(Nc(),Oc));H(Jk,"COL",Oc);H(Jk,"TH",Qc);Kk=new M;H(Kk,"EMBED",Oc);H(Kk,"OBJECT",Oc);H(Kk,"APPLET",Oc);H(Kk,"IFRAME",Oc);Lk=new Af;N(Lk,"grid");N(Lk,"treegrid");Mk=new Af;N(Mk,"gridcell");N(Mk,"columnheader");N(Mk,"row");N(Mk,"rowgroup");N(Mk,"rowheader");Nk=new Af;N(Nk,"application");N(Nk,"banner");N(Nk,"complementary");N(Nk,"contentinfo");N(Nk,"form");N(Nk,"main");N(Nk,"navigation");N(Nk,"search")}
function Ok(a,b){var c,d,e;for(d=new I(a);d.b<d.d.H();)if(c=(t(d.b<d.d.H()),d.d.R(d.c=d.b++)),e=c.tagName,null==e?Wd(b.a,null):void 0!==b.c.bb(e))return!(null==e?nd(Wd(b.a,null)):b.c.bb(e)).a||Pk(c);return!1}function Pk(a){a=a.innerText;return!!a.length&&!!/\S/.test(a)}function X(a,b,c){2<=Q&&R(a+b+" -\x3e "+c);return c}
function Qk(a){Ik();var b,c,d,e,f,g,l,p;Rk();for(f=w(a);f;){if(D("INPUT",f.tagName)||D(v(f,"contenteditable"),"true"))return X(Sk,"",(Z(),Tk));f=w(f)}f=v(a,"role").toLowerCase();if("presentation"===f)return X(Uk,"_"+f,(Z(),Tk));if(O(Lk,f)||O(Nk,f))return X(Uk,"_"+f,(Z(),Vk));f=new L;g=a.getElementsByTagName("*");if(0<a.getElementsByTagName("TABLE").length)for(e=0;e<g.length;e++)for(c=g[e],d=w(c);d;){if(D("TABLE",d.tagName)){d==a&&(f.b[f.b.length]=c);break}d=w(d)}else for(e=0;e<g.length;e++)K(f,g[e]);
for(g=new I(f);g.b<g.d.H();)if(b=(t(g.b<g.d.H()),g.d.R(g.c=g.b++)),c=v(b,"role").toLowerCase(),O(Mk,c)||O(Nk,c))return X(Wk,"_"+c,(Z(),Vk));if("0"===v(a,"datatable"))return X(Xk,"",(Z(),Tk));if(0<a.getElementsByTagName("TABLE").length)return X(Yk,"",(Z(),Tk));g=a.rows;if(1>=g.length)return X(Zk,"",(Z(),Tk));c=null;for(d=b=0;d<g.length;d++)e=g[d].cells,e.length>b&&(b=e.length,c=e);d=c;if(!d||1>=d.length)return X($k,"",(Z(),Tk));if((c=a.caption)&&Pk(c)||a.tHead||a.tFoot||Ok(f,Jk))return X(al,"",(Z(),
Vk));c=new L;for(e=new I(f);e.b<e.d.H();)b=(t(e.b<e.d.H()),e.d.R(e.c=e.b++)),D("TD",b.tagName)&&(c.b[c.b.length]=b);for(e=new I(c);e.b<e.d.H();){b=(t(e.b<e.d.H()),e.d.R(e.c=e.b++));if(b.hasAttribute("abbr")||b.hasAttribute("headers")||b.hasAttribute("scope"))return X(bl,"",(Z(),Vk));b=b.getElementsByTagName("*");if(1==b.length&&D("ABBR",b[0].tagName))return X(cl,"",(Z(),Vk))}e=a.ownerDocument.documentElement;b=(e.offsetWidth||0)|0;if(0<b&&((a.offsetWidth||0)|0)>0.95*b){p=!1;b=e.getElementsByTagName("META");
for(l=0;l<b.length&&!p;l++)p=b[l],p=D(p.name,"viewport");if(!p)return X(dl,"",(Z(),Tk))}if(a.hasAttribute("summary"))return X(el,"",(Z(),Vk));if(5<=d.length)return X(fl,"",(Z(),Vk));for(d=new I(c);d.b<d.d.H();)if(b=(t(d.b<d.d.H()),d.d.R(d.c=d.b++)),b=getComputedStyle(b,null).borderStyle,b.length&&"none"!==b&&"hidden"!==b)return X(gl,"_"+b,(Z(),Vk));l=null;for(b=0;b<g.length;b++)if(d=getComputedStyle(g[b],null).backgroundColor,null==l)l=d;else if(!D(l,d))return X(hl,"",(Z(),Vk));if(20<=g.length)return X(il,
"",(Z(),Vk));if(10>=c.b.length)return X(jl,"",(Z(),Tk));if(Ok(f,Kk))return X(kl,"",(Z(),Tk));f=(e.offsetHeight||0)|0;return 0<f&&((a.offsetHeight||0)|0)>0.9*f?X(ll,"",(Z(),Tk)):X(ml,"",(Z(),Vk))}var Nk,Mk,Lk,Jk,Kk;
function Rk(){Rk=h;Sk=new $("INSIDE_EDITABLE_AREA",0);Uk=new $("ROLE_TABLE",1);Wk=new $("ROLE_DESCENDANT",2);Xk=new $("DATATABLE_0",3);al=new $("CAPTION_THEAD_TFOOT_COLGROUP_COL_TH",4);bl=new $("ABBR_HEADERS_SCOPE",5);cl=new $("ONLY_HAS_ABBR",6);dl=new $("MORE_95_PERCENT_DOC_WIDTH",7);el=new $("SUMMARY",8);Yk=new $("NESTED_TABLE",9);Zk=new $("LESS_EQ_1_ROW",10);$k=new $("LESS_EQ_1_COL",11);fl=new $("MORE_EQ_5_COLS",12);gl=new $("CELLS_HAVE_BORDER",13);hl=new $("DIFFERENTLY_COLORED_ROWS",14);il=new $("MORE_EQ_20_ROWS",
15);jl=new $("LESS_EQ_10_CELLS",16);kl=new $("EMBED_OBJECT_APPLET_IFRAME",17);ll=new $("MORE_90_PERCENT_DOC_HEIGHT",18);ml=new $("DEFAULT",19);nl=new $("UNKNOWN",20)}function $(a,b){this.a=a;this.b=b}k(8,12,{3:1,15:1,12:1,8:1},$);var bl,al,gl,Xk,ml,hl,kl,Sk,jl,$k,Zk,ll,dl,il,fl,Yk,cl,Wk,Uk,el,nl,ol=Bb(8,function(){Rk();return x(Db(ol,1),da,8,0,[Sk,Uk,Wk,Xk,al,bl,cl,dl,el,Yk,Zk,$k,fl,gl,hl,il,jl,kl,ll,ml,nl])});function Z(){Z=h;Vk=new pl("DATA",0);Tk=new pl("LAYOUT",1)}
function pl(a,b){this.a=a;this.b=b}k(39,12,{3:1,15:1,12:1,39:1},pl);var Vk,Tk,ql=Bb(39,function(){Z();return x(Db(ql,1),da,39,0,[Vk,Tk])});function rl(a){return gi(J(a.j,J(a.i,0).a))}function sl(a,b){return O(a.b,b)}function Xh(a,b){a.g+="\n";a.g+=b.g;a.d+=b.d;a.e+=b.e;a.c=0==a.d?0:a.e/a.d;a.a|=b.a;df(a.i,b.i);a.b.F(b.b);a.f=Yc(a.f,b.f)}function Rh(a,b){if(b==a.a)return!1;a.a=b;return!0}
function tl(a){var b;b="["+(J(a.j,J(a.i,0).a).i+"-"+J(a.j,J(a.i,a.i.b.length-1).a).i+";");b+="tl\x3d"+a.f+";";b+="nw\x3d"+a.d+";";b+="ld\x3d"+a.c+";";b=b+"]\t"+((a.a?"\u001b[0;32mCONTENT":"\u001b[0;35mboilerplate")+"\u001b[0m,");b+="\u001b[1;30m"+jd(new wh(a.b))+"\u001b[0m";return b+="\n"+a.g}function Kh(a,b){var c,d;this.j=a;this.i=new L;K(this.i,Uc(b));c=J(this.j,b);this.b=(d=c.d,c.d=new Af,d);this.d=c.g;this.e=c.f;this.f=c.k;this.g=c.n;this.c=0==this.d?0:this.e/this.d}k(116,1,{},Kh);_.tS=function(){return tl(this)};
_.a=!1;_.c=0;_.d=0;_.e=0;_.f=0;s(116);function Lh(a){this.a=a}k(100,1,{},Lh);s(100);function ul(){ul=h;vl=new Af;N(vl,"BLOCKQUOTE");N(vl,"IFRAME")}
function wl(a){var b;if(-1==(a.className||"").indexOf("twitter-tweet"))return null;a=a.getElementsByTagName("a");if(0==a.length)return null;a=a[a.length-1];if(!Fi(a.href,"twitter.com"))return null;a:{b=dd(qc(a,"pathname"),"/");for(a=b.length-1;0<=a;a--)if(0<b[a].length){b=b[a];break a}b=null}if(null==b)return null;a=new M;a.c.eb("tweetid",b);return new xl(a)}
function yl(a){var b;if("IFRAME"!==a.tagName||a.src.length)return null;a=a.contentWindow.document;if(!a)return null;a=a.getElementsByTagName("blockquote");if(1>a.length)return null;b=v(a[0],"data-tweet-id");if(!b.length)return null;a=new M;a.c.eb("tweetid",b);return new xl(a)}function zl(){ul()}k(113,1,{},zl);
_.wb=function(a){var b;if(!a||!O(vl,a.tagName))return null;b=null;"BLOCKQUOTE"===a.tagName?b=wl(a):"IFRAME"===a.tagName&&(b=yl(a));b&&2<=Q&&(R("Twitter embed extracted:"),R("    ID: "+G(b.a,"tweetid")));return b};_.xb=function(){return vl};var vl;s(113);function Al(){Al=h;Bl=new Af;N(Bl,"IFRAME")}function Cl(){Al()}k(114,1,{},Cl);
_.wb=function(a){var b;if(!a||!O(Bl,a.tagName))return null;b=a.src;if(!Fi(b,"player.vimeo.com"))return null;a=$doc.createElement("a");a.href=b;b=qc(a,"pathname");a=Gi(ed(qc(a,"search"),1));a:{var c;c=dd(b,"/");for(b=c.length-1;0<=b&&"video"!==c[b];b--)if(0<c[b].length){b=c[b];break a}b=null}if(null==b)return null;a.c.eb("videoid",b);2<=Q&&(R("Vimeo embed extracted:"),R("    ID:    "+a.c.bb("videoid")));return new xl(a)};_.xb=function(){return Bl};var Bl;s(114);
function Dl(){Dl=h;El=new Af;N(El,"IFRAME")}function Fl(){Dl()}k(115,1,{},Fl);_.wb=function(a){var b;if(!a||!O(El,a.tagName))return null;b=a.src;if(!Fi(b,"youtube.com"))return null;a=$doc.createElement("a");a.href=b;b=qc(a,"pathname");a=Gi(ed(qc(a,"search"),1));a:{var c;c=dd(b,"/");for(b=c.length-1;0<=b&&"embed"!==c[b];b--)if(0<c[b].length){b=c[b];break a}b=null}if(null==b)return null;a.c.eb("videoid",b);2<=Q&&(R("YouTube embed extracted:"),R("    ID:    "+a.c.bb("videoid")));return new xl(a)};
_.xb=function(){return El};var El;s(115);function Mh(a,b,c){if(!(1>Q))if(b){R("\u001b[0;34m\x3c\x3c\x3c\x3c\x3c "+c+" \x3e\x3e\x3e\x3e\x3e");if(!(1>Q)){b="";for(c=new I(a.a);c.b<c.d.H();)a=(t(c.b<c.d.H()),c.d.R(c.c=c.b++)),b+=tl(a)+"\n";R(b)}R("\u001b[0;34m\x3c\x3c\x3c\x3c\x3c                \x3e\x3e\x3e\x3e\x3e")}else R("\u001b[0;31m~~~~~ No Changes: "+c+" ~~~~~")}
function Nh(){Nh=h;Oh=RegExp("(^(comments|\u00a9 reuters|please rate this|post a comment|\\d+\\s+(comments|users responded in))|what you think\\.\\.\\.|add your comment|add comment|reader views|have your say|reader comments|r\u00e4tta artikeln|^thanks for your comments - this feedback is now closed$)","i")}var Oh;function Zh(){Zh=h;$h=new Gl(!1);ci=new Gl(!0)}
function Yh(a,b){var c,d,e,f,g;c=b.a;if(2>c.b.length)return!1;d=!1;g=(u(0,c.b.length),c.b[0]);for(f=new Ie(c,1);f.b<f.d.H();)c=(t(f.b<f.d.H()),f.d.R(f.c=f.b++)),c.a&&g.a?(e=J(c.j,J(c.i,0).a).i-J(g.j,J(g.i,g.i.b.length-1).a).i-1,1>=e?(e=!0,a.a?g.f!=c.f&&(e=!1):O(c.b,"BOILERPLATE_HEADING_FUSED")&&(e=!1),O(g.b,"STRICTLY_NOT_CONTENT")!=O(c.b,"STRICTLY_NOT_CONTENT")&&(e=!1),O(g.b,"de.l3s.boilerpipe/TITLE")!=O(c.b,"de.l3s.boilerpipe/TITLE")&&(e=!1),!g.a&&O(g.b,"de.l3s.boilerpipe/LI")&&!O(c.b,"de.l3s.boilerpipe/LI")&&
(e=!1),e?(Xh(g,c),He(f),d=!0):g=c):g=c):g=c;return d}function Gl(a){this.a=a}k(61,1,{},Gl);_.tS=function(){return pb(Hl),Hl.n+": postFiltering\x3d"+this.a};_.a=!1;var ci,$h,Hl=s(61);function Il(){Il=h;Qh=RegExp("[\\?\\!\\.\\-\\:]+","g")}function Jl(a,b,c){var d,e;e=dd(b,c);if(1!=e.length)for(b=0;b<e.length;b++)d=e[b],-1==d.indexOf(".com")&&(c=zh(d),4<=c&&N(a,d))}
function Kl(a,b){var c,d,e,f,g,l;l=dd(a,b);if(1==l.length)return null;d=0;e="";for(c=0;c<l.length;c++)if(g=l[c],-1==g.indexOf(".com")&&(f=zh(g),f>d||g.length>e.length))d=f,e=g;return 0==e.length?null:fd(e)}
function Ph(a){Il();var b;if(a)for(this.a=new Af,a=af(a,0);a.b!=a.d.c;){b=(t(a.b!=a.d.c),a.c=a.b,a.b=a.b.a,++a.a,a.c.c);var c=void 0;b=$c(b);b=ad(b);b=fd(b).toLowerCase();0!=b.length&&N(this.a,b)&&(c=Kl(b,"[ ]*[\\|\u00bb|-][ ]*"),null!=c&&N(this.a,c),c=Kl(b,"[ ]*[\\|\u00bb|:][ ]*"),null!=c&&N(this.a,c),c=Kl(b,"[ ]*[\\|\u00bb|:\\(\\)][ ]*"),null!=c&&N(this.a,c),c=Kl(b,"[ ]*[\\|\u00bb|:\\(\\)\\-][ ]*"),null!=c&&N(this.a,c),c=Kl(b,"[ ]*[\\|\u00bb|,|:\\(\\)\\-][ ]*"),null!=c&&N(this.a,c),c=Kl(b,"[ ]*[\\|\u00bb|,|:\\(\\)\\-\u00a0][ ]*"),
null!=c&&N(this.a,c),Jl(this.a,b,"[ ]+[\\|][ ]+"),Jl(this.a,b,"[ ]+[\\-][ ]+"),N(this.a,cd(b," - [^\\-]+$")),N(this.a,cd(b,"^[^\\-]+ - ")))}else this.a=null}k(117,1,{},Ph);var Qh;s(117);function di(){di=h;ei=new Ll(!0)}function Ll(a){this.a=a}k(63,1,{},Ll);_.a=!1;var ei;s(63);function Ml(a,b,c){b=J(a.d,b);c=J(a.d,c);return a.c||(b.nodeType!=c.nodeType?0:1!=b.nodeType||b.nodeName===c.nodeName)?b.parentNode==c.parentNode:!1}
function Vh(a,b){var c,d,e,f,g,l,p,z,y,W;a.g=b.a;if(2>a.g.b.length)return!1;d=a.g;e=$doc.documentElement;l=new L;for(f=0;f<d.b.length;++f){g=f+1==d.b.length?e:rl((u(f+1,d.b.length),d.b[f+1]));0==f?p=e:(p=(u(f-1,d.b.length),d.b[f-1]),p=fi(J(p.j,J(p.i,p.i.b.length-1).a)));y=p;p=rl((u(f,d.b.length),d.b[f]));for(z=p.parentNode;!z.contains(y)&&!z.contains(g);)p=z,z=z.parentNode;l.b[l.b.length]=p}a.d=l;l=B(Nl,0,a.g.b.length,7);z=p=0;d=B(Nl,0,a.g.b.length,7);f=e=0;g=!1;for(y=0;y<a.g.b.length;y++)if(!a.b&&
sl(J(a.g,y),"de.l3s.boilerpipe/TITLE")||!a.a&&sl(J(a.g,y),"de.l3s.boilerpipe/HEADING"))p=z,e=f;else if(J(a.g,y).a&&!sl(J(a.g,y),"STRICTLY_NOT_CONTENT")&&!sl(J(a.g,y),"de.l3s.boilerpipe/TITLE"))for(l[z++]=y,W=e;W<f;W++)c=d[W],y-c>a.e?W==e&&++e:Ml(a,y,c)&&(g=!0,Rh(J(a.g,c),!0),d[W]=d[e++]);else if(J(a.g,y).c<=a.f&&!J(a.g,y).a&&!sl(J(a.g,y),"STRICTLY_NOT_CONTENT")&&!sl(J(a.g,y),"de.l3s.boilerpipe/TITLE")){for(W=p;W<z;W++)if(c=l[W],y-c>a.e)W==p&&++p;else if(Ml(a,y,c)){g=!0;Rh(J(a.g,y),!0);l[W]=l[p++];
break}W==z?d[f++]=y:l[z++]=y}return g}function Ol(a,b,c,d,e){this.b=a;this.a=b;this.c=c;this.f=d;this.e=e}k(119,1,{},Ol);_.a=!1;_.b=!1;_.c=!1;_.e=0;_.f=0;s(119);function Uh(){var a=new Pl;a.a=!0;return a}function Wh(a){return new Ol(a.b,a.a,a.c,a.e,a.d)}function Pl(){this.c=this.a=this.b=!1;this.d=this.e=0}k(60,1,{},Pl);_.a=!1;_.b=!1;_.c=!1;_.d=0;_.e=0;s(60);function ai(){ai=h;bi=new Ql("de.l3s.boilerpipe/TITLE")}function Ql(a){this.a=a}k(62,1,{},Ql);var bi;s(62);
function Sh(){Sh=h;Th=new Rl(x(Db(m,1),da,2,4,["STRICTLY_NOT_CONTENT"]))}function Rl(a){this.a=a}k(118,1,{},Rl);var Th;s(118);k(169,1,{});_.zb=function(a){var b;b=0;a&&(b=this.yb(a));2<=Q&&R(wb(this.cZ)+": "+b+"/"+this.Ab());return Yc(b,this.Ab())};s(169);function Ii(){this.b=25;this.c=75E3;this.a=2E5}k(132,169,{},Ii);_.yb=function(a){a=((a.offsetWidth||0)|0)*((a.offsetHeight||0)|0);if(a<this.c)return 0;a=mb((a-this.c)/(this.a-this.c)*this.b);return Yc(a,this.b)};_.Ab=function(){return this.b};
_.a=0;_.b=0;_.c=0;s(132);function Ji(){this.a=25}k(133,169,{},Ji);_.yb=function(a){var b,c;b=(a.offsetHeight||0)|0;if(0>=b)return 0;c=(a.offsetWidth||0)|0;a=0;b=c/b;1.4500000476837158<b&&1.7999999523162842>b?a=1:1.2999999523162842<b&&2.200000047683716>b&&(a=0.4000000059604645);return mb(this.a*a)};_.Ab=function(){return this.a};_.a=0;s(133);function Ki(a){this.b=25;this.a=a}k(134,169,{},Ki);
_.yb=function(a){var b;if(!this.a)return 0;b=Ei(this.a).b.length-1;var c;for(c=this.a;c&&!c.contains(a);)c=c.parentNode;a=b-(Ei(c).b.length-1);b=0;4>a?b=1:6>a?b=0.6000000238418579:8>a&&(b=0.20000000298023224);return mb(this.b*b)};_.Ab=function(){return this.b};_.b=0;s(134);function Li(){this.a=15}k(135,169,{},Li);_.yb=function(a){var b;a=Ei(a);for(b=new I(a);b.b<b.d.H();)if(a=(t(b.b<b.d.H()),b.d.R(b.c=b.b++)),1==a.nodeType&&"FIGURE"===a.tagName)return this.a;return 0};_.Ab=function(){return this.a};
_.a=0;s(135);
function Sl(a,b){var c,d;d=pi(b);2>Q||(c=getComputedStyle(b,null),R((d?"KEEP ":"SKIP ")+b.tagName+": id\x3d"+b.id+", dsp\x3d"+c.display+", vis\x3d"+c.visibility+", opaq\x3d"+c.opacity));if(!d)return N(a.d,b),!1;if(O(a.b,b.tagName))for(d=new I(a.c);d.b<d.d.H();)if(c=(t(d.b<d.d.H()),d.d.R(d.c=d.b++)),c=c.wb(b))return K(a.a.b.a,c),!1;switch(b.tagName){case "TABLE":d=Qk(b);2>Q||(c=w(b),R("TABLE: "+d+", id\x3d"+b.id+", class\x3d"+(b.className||"")+", parent\x3d["+c.tagName+", id\x3d"+c.id+", class\x3d"+
(c.className||"")+"]"));if(d==(Z(),Vk))return K(a.a.b.a,new Tl(b)),!1;break;case "FIGURE":case "VIDEO":return 2<=Q&&R("SKIP "+b.tagName+" from processing. It may be restored later."),!1;case "OPTION":case "OBJECT":case "EMBED":case "APPLET":return a.a.c=!0,!1;case "HEAD":case "STYLE":case "SCRIPT":case "LINK":case "NOSCRIPT":return!1}d=a.a;Ul();var e,f,g;g=getComputedStyle(b,null);c=new rm;switch(g.display){case "inline":break;case "inline-block":case "inline-flex":c.a=!0;break;default:c.b=!0,c.a=
!0}g=b.tagName;if("BODY"!==g){e=v(b,"class");f=v(b,"id");if(sm.test(e)||sm.test(f))e=c.d,e[e.length]="STRICTLY_NOT_CONTENT";switch(g){case "ASIDE":case "NAV":g=c.d;g[g.length]="STRICTLY_NOT_CONTENT";break;case "LI":g=c.d;g[g.length]="de.l3s.boilerpipe/LI";break;case "H1":g=c.d;g[g.length]="de.l3s.boilerpipe/H1";g=c.d;g[g.length]="de.l3s.boilerpipe/HEADING";break;case "H2":g=c.d;g[g.length]="de.l3s.boilerpipe/H2";g=c.d;g[g.length]="de.l3s.boilerpipe/HEADING";break;case "H3":g=c.d;g[g.length]="de.l3s.boilerpipe/H3";
g=c.d;g[g.length]="de.l3s.boilerpipe/HEADING";break;case "A":c.a=!0,b.hasAttribute("href")&&(c.c=!0)}}K(d.a.a,c);c.a&&++d.e;c.c&&(g=d.f,g.e=!0,g.j+=" ");d.c|=c.b;return!0}function Gh(a){var b;this.d=new Af;this.a=a;this.c=new L;K(this.c,new zl);K(this.c,new Cl);K(this.c,new Fl);this.b=new Af;for(b=new I(this.c);b.b<b.d.H();)a=(t(b.b<b.d.H()),b.d.R(b.c=b.b++)),id(this.b,a.xb())}k(99,1,{},Gh);
_.jb=function(){var a=this.a,b;b=a.a;var c;c=b.a.b.length;if(0<c)b=(ch(c-1,b.a.b.length),J(b.a,c-1));else throw new kf;b.a&&--a.e;(a.c||b.b)&&Jh(a);b.c&&(b=a.f,b.e=!1,b.j+=" ");a=a.a;b=a.a.b.length;if(0<b)ch(b-1,a.a.b.length),a.a.S(b-1);else throw new kf;};
_.kb=function(a){switch(a.nodeType){case 3:var b=this.a;b.c&&(Jh(b),b.c=!1);var c=b.f,b=b.e,d;d=a.data;d.length&&(c.j+=d,K(c.a,a),/\S/.test(d)&&(a=zh(d),c.i+=a,c.e&&(c.g+=a),c.f=c.a.b.length-1,c.d<c.c&&(c.d=c.f),-1==c.b&&(c.b=b)));return!1;case 1:return Sl(this,a);default:return!1}};s(99);function Ul(){Ul=h;sm=/\bcomments?\b/}function rm(){this.d=[]}k(136,1,{},rm);_.a=!1;_.b=!1;_.c=!1;var sm;s(136);function tm(){this.a=new L}k(86,1,{},tm);s(86);
function Jh(a){var b;b=a.f;var c=a.d;b.c==b.a.b.length?b=null:b.d<b.c?(um(b),b=null):(c=new vm(b.j,b.a,b.c,b.a.b.length,b.d,b.f,b.i,b.g,b.b,c),um(b),b=c);if(b){++a.d;var d,e;for(d=new I(a.a.a);d.b<d.d.H();)for(c=(t(d.b<d.d.H()),d.d.R(d.c=d.b++)),e=0;e<c.d.length;e++)N(b.d,c.d[e]);K(a.b.a,b)}}function Fh(){this.b=new tm;this.a=new dh;this.f=new wm}k(98,1,{},Fh);_.c=!1;_.d=0;_.e=0;s(98);k(167,1,{});_.o=!1;s(167);function xl(a){this.a=a}k(38,167,{},xl);_.Bb=function(){};s(38);
function Tl(a){this.a=a}k(46,167,{46:1},Tl);_.Bb=function(a){Hh(new Ih(new xm(a)),this.a)};s(46);function xm(a){this.a=a}k(101,1,{},xm);_.jb=function(){};_.kb=function(a){switch(a.nodeType){case 3:return K(this.a,a),!1;case 1:if(!pi(a))return!1;K(this.a,a);return!0;default:return!1}};s(101);function gi(a){return J(a.a,a.c)}function fi(a){return J(a.a,a.e)}function vm(a,b,c,d,e,f,g,l,p,z){this.n=a;this.a=b;this.j=c;this.b=d;this.c=e;this.e=f;this.g=g;this.f=l;this.d=new Af;this.k=p;this.i=z}
k(35,167,{35:1},vm);_.Bb=function(a,b){!b&&O(this.d,"de.l3s.boilerpipe/TITLE")||df(a,new Je(this.a,this.j,this.b))};_.b=0;_.c=0;_.e=0;_.f=0;_.g=0;_.i=0;_.j=0;_.k=0;s(35);function um(a){a.j="";a.i=0;a.g=0;a.c=a.a.b.length;a.b=-1}function wm(){this.a=new L}k(131,1,{},wm);_.b=-1;_.c=0;_.d=-1;_.e=!1;_.f=0;_.g=0;_.i=0;_.j="";s(131);var Nl,ym;ym=zb("I");ym.k="I";ym.f=1;Nl=ym;s(150);s(152);s(null);s(155);Jf=Cb();
_=function(a){var b=this;if("$wnd"==a)return $wnd;if(""===a)return b;"$wnd."==a.substring(0,5)&&(b=$wnd,a=a.substring(5));a=a.split(".");a[0]in b||!b.execScript||b.execScript("var "+a[0]);for(var c;a.length&&(c=a.shift());)b[c]?b=b[c]:b=b[c]={};return b}("org.chromium.distiller.DomDistiller");_.apply=function(){var a;return Eh((a={},a))};_.applyWithOptions=Eh;
function zm(a){return function(){var b;a:{var c=arguments,d;0!=Nb&&(d=Date.now?Date.now():(new Date).getTime(),2E3<d-$b&&($b=d,Zb=$wnd.setTimeout(Lb,10)));if(0==Nb++){d=(ac(),bc);var e,f;if(d.a){f=null;do e=d.a,d.a=null,f=dc(e,f);while(d.a);d.a=f}d=!0}else d=!1;try{b=a.apply(this,c);break a}finally{if(c=d)if(d=(ac(),bc),d.b){f=null;do e=d.b,d.b=null,f=dc(e,f);while(d.b);d.b=f}--Nb;c&&-1!=Zb&&($wnd.clearTimeout(Zb),Zb=-1)}b=void 0}return b}}
var gwtOnLoad=gwtOnLoad=function(a,b,c){function d(){for(var a=0;a<e.length;a++)e[a]()}null==ja&&(ja=[]);var e=ja;$moduleName=b;$moduleBase=c;if(a)try{zm(d)()}catch(f){a(b,f)}else zm(d)()};(function(){null==ja&&(ja=[]);for(var a=ja,b=0;b<arguments.length;b++)a.push(arguments[b])})(function(){$wnd.setTimeout(zm(xc));var a,b,c;b=$doc.compatMode;a=x(Db(m,1),da,2,4,["CSS1Compat"]);for(c=0;c<a.length&&a[c]!==b;c++);});var Am=[[["locale","default"],["user.agent","safari"]]];
"object"===typeof window&&"object"===typeof window.$gwt&&(window.$gwt.permProps=Am);window.gwtOnLoad=gwtOnLoad;gwtOnLoad(undefined, "domdistiller", "", 0);})();
    }
    var context = Object.create(window);
    context.setTimeout = function() {};
    context.clearTimeout = function() {};
    initialize(context);

    var distiller = context.org.chromium.distiller.DomDistiller;
    var res = distiller.applyWithOptions(options);
    return res;
  } catch (e) {
    window.console.error("Error during distillation: " + e);
    if (e.stack != undefined) window.console.error(e.stack);
  }
  return undefined;
// The OPTIONS placeholder will be replaced with the DomDistillerOptions at
// runtime.
})($$OPTIONS)
