// Copyright 2017 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#ifndef CHROME_BROWSER_CHROMEOS_LOGIN_SCREENS_SCREEN_EXIT_CODE_H_
#define CHROME_BROWSER_CHROMEOS_LOGIN_SCREENS_SCREEN_EXIT_CODE_H_

#include <string>

namespace chromeos {

// Each login screen or a view shown within login wizard view is itself a
// state. Upon exit each view returns one of the results by calling
// the BaseScreenDelegate::OnExit() method. Depending on the result and the
// current view or state the login wizard decides what is the next view to show.
//
// There must be an exit code for each way to exit the screen for each screen.
//
// Numeric ids are provided to facilitate interpretation of log files only,
// they are subject to change without notice.
enum class ScreenExitCode {
  // "Continue" was pressed on welcome screen.
  DEPRECATED_WELCOME_CONTINUED = 0,
  DEPRECATED_HID_DETECTION_COMPLETED = 1,
  // Connection failed while trying to load a WebPageScreen.
  DEPRECATED_CONNECTION_FAILED = 2,
  DEPRECATED_UPDATE_INSTALLED = 3,
  // This exit code means EITHER that there was no update, OR that there
  // was an update, but that it was not a "critical" update. "Critical" updates
  // are those that have a deadline and require the device to reboot.
  DEPRECATED_UPDATE_NOUPDATE = 4,
  DEPRECATED_UPDATE_ERROR_CHECKING_FOR_UPDATE = 5,
  DEPRECATED_UPDATE_ERROR_UPDATING = 6,
  DEPRECATED_USER_IMAGE_SELECTED = 7,
  DEPRECATED_EULA_ACCEPTED = 8,
  DEPRECATED_EULA_BACK = 9,
  DEPRECATED_ENTERPRISE_AUTO_ENROLLMENT_CHECK_COMPLETED = 10,
  DEPRECATED_ENTERPRISE_ENROLLMENT_COMPLETED = 11,
  DEPRECATED_ENTERPRISE_ENROLLMENT_BACK = 12,
  DEPRECATED_RESET_CANCELED = 13,
  DEPRECATED_KIOSK_AUTOLAUNCH_CANCELED = 14,
  DEPRECATED_KIOSK_AUTOLAUNCH_CONFIRMED = 15,
  DEPRECATED_KIOSK_ENABLE_COMPLETED = 16,
  DEPRECATED_TERMS_OF_SERVICE_DECLINED = 17,
  DEPRECATED_TERMS_OF_SERVICE_ACCEPTED = 18,
  DEPRECATED_WRONG_HWID_WARNING_SKIPPED = 19,
  DEPRECATED_ENABLE_DEBUGGING_FINISHED = 21,
  DEPRECATED_ENABLE_DEBUGGING_CANCELED = 22,
  DEPRECATED_ARC_TERMS_OF_SERVICE_SKIPPED = 23,
  DEPRECATED_ARC_TERMS_OF_SERVICE_ACCEPTED = 24,
  DEPRECATED_UPDATE_ERROR_UPDATING_CRITICAL_UPDATE = 25,
  DEPRECATED_ENCRYPTION_MIGRATION_FINISHED = 26,
  DEPRECATED_ENCRYPTION_MIGRATION_SKIPPED = 27,
  DEPRECATED_SYNC_CONSENT_FINISHED = 32,
  DEPRECATED_DEMO_MODE_SETUP_FINISHED = 33,
  DEPRECATED_DEMO_MODE_SETUP_CANCELED = 34,
  DEPRECATED_RECOMMEND_APPS_SKIPPED = 35,
  DEPRECATED_RECOMMEND_APPS_SELECTED = 36,
  DEPRECATED_DEMO_MODE_PREFERENCES_CONTINUED = 37,
  DEPRECATED_DEMO_MODE_PREFERENCES_CANCELED = 38,
  DEPRECATED_APP_DOWNLOADING_FINISHED = 39,
  DEPRECATED_ARC_TERMS_OF_SERVICE_BACK = 40,
  DEPRECATED_DISCOVER_FINISHED = 41,
  DEPRECATED_NETWORK_BACK = 42,
  DEPRECATED_NETWORK_CONNECTED = 43,
  DEPRECATED_NETWORK_OFFLINE_DEMO_SETUP = 44,
  DEPRECATED_FINGERPRINT_SETUP_FINISHED = 45,
  DEPRECATED_MARKETING_OPT_IN_FINISHED = 46,
  DEPRECATED_ASSISTANT_OPTIN_FLOW_FINISHED = 47,
  DEPRECATED_MULTIDEVICE_SETUP_FINISHED = 48,
  DEPRECATED_UPDATE_REJECT_OVER_CELLULAR = 49,
  DEPRECATED_SUPERVISION_TRANSITION_FINISHED = 50,
  EXIT_CODES_COUNT  // not a real code, must be the last
};

std::string ExitCodeToString(ScreenExitCode code);

}  // namespace chromeos

#endif  // CHROME_BROWSER_CHROMEOS_LOGIN_SCREENS_SCREEN_EXIT_CODE_H_
