// Copyright (c) 2012 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

namespace basic_type {
  // Documentation for BasicType.
  dictionary BasicType {
    // Documentation for the String s.
    DOMString s;

    // Documentation for the int i.
    int i;

    // Documentation for the long l.
    long l;

    // Documentation for the double d.
    double d;
  };
};
