# Copyright 2013 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

{
  'variables': {
    'webkit_browser_appcache_sources': [
      '../browser/appcache/appcache.cc',
      '../browser/appcache/appcache.h',
      '../browser/appcache/appcache_backend_impl.cc',
      '../browser/appcache/appcache_backend_impl.h',
      '../browser/appcache/appcache_database.cc',
      '../browser/appcache/appcache_database.h',
      '../browser/appcache/appcache_disk_cache.cc',
      '../browser/appcache/appcache_disk_cache.h',
      '../browser/appcache/appcache_entry.h',
      '../browser/appcache/appcache_group.cc',
      '../browser/appcache/appcache_group.h',
      '../browser/appcache/appcache_histograms.cc',
      '../browser/appcache/appcache_histograms.h',
      '../browser/appcache/appcache_host.cc',
      '../browser/appcache/appcache_host.h',
      '../browser/appcache/appcache_interceptor.cc',
      '../browser/appcache/appcache_interceptor.h',
      '../browser/appcache/appcache_policy.h',
      '../browser/appcache/appcache_quota_client.cc',
      '../browser/appcache/appcache_quota_client.h',
      '../browser/appcache/appcache_request_handler.cc',
      '../browser/appcache/appcache_request_handler.h',
      '../browser/appcache/appcache_response.cc',
      '../browser/appcache/appcache_response.h',
      '../browser/appcache/appcache_service.cc',
      '../browser/appcache/appcache_service.h',
      '../browser/appcache/appcache_storage.cc',
      '../browser/appcache/appcache_storage.h',
      '../browser/appcache/appcache_storage_impl.cc',
      '../browser/appcache/appcache_storage_impl.h',
      '../browser/appcache/appcache_working_set.cc',
      '../browser/appcache/appcache_working_set.h',
      '../browser/appcache/appcache_update_job.cc',
      '../browser/appcache/appcache_update_job.h',
      '../browser/appcache/appcache_url_request_job.cc',
      '../browser/appcache/appcache_url_request_job.h',
      '../browser/appcache/manifest_parser.cc',
      '../browser/appcache/manifest_parser.h',
      '../browser/appcache/view_appcache_internals_job.h',
      '../browser/appcache/view_appcache_internals_job.cc',
    ],
  },
}
