#!/usr/bin/env bash

# Copyright (c) 2017 Google Inc. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.


# Execute whatever is printed by autoninja.py.
# Also print it to reassure that the right settings are being used.
command=$(python $(dirname -- "$0")/autoninja.py "$@")
echo $command
exec $command
