#!/bin/sh
# Copyright 2013 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# git-number -- a git-command for calculating and displaying the generation
# number of a commit.

# Test if this script is running under a MSys install.  If it is, we will
# hardcode the path to Python where possible.
OUTPUT="$(uname | grep 'MINGW')"
MINGW=$?

if [ $MINGW = 0 ]; then
  base_dir="${0%\\*}"
else
  base_dir=$(dirname "$0")
fi

# Uncomment this line if you never use gclient.
# "$base_dir"/update_depot_tools

if [ -e "$base_dir/python.bat" -a $MINGW = 0 ]; then
  PYTHONDONTWRITEBYTECODE=1 cmd.exe //c "$base_dir\\python.bat" "$base_dir\\git_number.py" "$@"
else
  PYTHONDONTWRITEBYTECODE=1 exec "$base_dir/git_number.py" "$@"
fi
