#!/bin/sh
# Copyright (c) 2011 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
git grep -n -e "$@" -- "*.h" "*.hpp" "*.cpp" "*.c" "*.cc" "*.cpp" "*.inl"\
   "*.grd" "*.idl" "*.m" "*.mm" "*.py" "*.sh" "*.cfg" "*.tac"\
   "*SConscript" "SConscript*" "*.scons" "*.vcproj" "*.vsprops" "*.make"\
   "*.gyp" "*.gypi" "*.js" "*.html" "*.css"
