#!/bin/bash

while test "$PWD" != "/"; do
  if test -f "$PWD/src/.gitmodules"; then
    break
  fi
  cd ..
done
if ! test -f "$PWD/src/.gitmodules"; then
  echo "Could not find the root of your checkout; aborting." 1>&2
  exit 1
fi

gclient_spec="solutions=[{'name':'src','url':None,'deps_file':'.DEPS.git'}]"
gclient runhooks --spec="$gclient_spec"
exit $?
