#!/bin/sh
# Copyright (c) 2009 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

base_dir=$(dirname "$0")

if [ ! -f "$base_dir/git-cl-repo/git-cl" ]; then
  git clone git://neugierig.org/git-cl.git $base_dir/git-cl-repo -q
fi

$base_dir/git-cl-repo/git-cl "$@"
