#!/usr/bin/env bash
# Copyright 2014 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# git_cherry_pick_upload.py -- Upload a cherry pick CL to rietveld.

. $(type -P python_git_runner.sh)
