#!/usr/bin/python

# TODO(mark): This script is temporary, and is only being used while Chromium
# is transitioning to GYP-based builds.  It is intended to be used as the
# action of a gclient hook.

import os
import sys

# GYP is now the official build system, so it runs for all platforms.
print 'Updating projects from gyp files...'

# Use Visual Studio 2005 when on buildbots.
if os.environ.get('CHROME_HEADLESS') == '1':
  os.environ['GYP_MSVS_VERSION'] = '2005'

try:
  import gyp
except ImportError, e:
  import os.path
  sys.path.append(os.path.join(os.path.dirname(sys.argv[0]), 'pylib'))
  import gyp

if __name__ == '__main__':
  sys.exit(gyp.main(sys.argv[1:]))
