#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Copyright 2018 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

"""Wrapper to find run_tests for the lazy people."""

from __future__ import print_function

import os
import sys


sys.argv[0] = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                           'scripts', 'run_tests')
os.execv(sys.argv[0], sys.argv)
