#!/bin/sh
#
# $XFree86$
#
LANG=C
export LANG
FONTDIRS=fontdirs$$
trap "rm $FONTDIRS" 0
sh ./findfonts ${1+"$@"} > $FONTDIRS
cp fonts.conf.in fonts.conf
chmod +w fonts.conf
ed fonts.conf << EOF
/FONTPATH_END/a
<!-- Font directory list configured on `date` -->
.
+r $FONTDIRS
a
	<dir>~/.fonts</dir>

.
/FONTPATH_START/,/FONTPATH_END/d

w
q
EOF

