# Copyright 2017 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
{
  'targets': [
    {
      'target_name': 'help',
      'variables': {
        'extra_inputs': [
          '<!@(python <(CLOSURE_DIR)/build/get_includes.py ../options/options_bundle.js)',
        ],
        'script_args': ['--custom_sources', '--custom_includes'],
        'source_files': [
          '<(DEPTH)/third_party/jstemplate/util.js',
          '<(DEPTH)/third_party/jstemplate/jsevalcontext.js',
          '<(DEPTH)/third_party/jstemplate/jstemplate.js',
          '<(DEPTH)/ui/webui/resources/cr_elements/chromeos/network/cr_onc_types.js',
          '<(DEPTH)/ui/webui/resources/js/action_link.js',
          '<(DEPTH)/ui/webui/resources/js/cr.js',
          '<(DEPTH)/ui/webui/resources/js/cr/event_target.js',
          '<(DEPTH)/ui/webui/resources/js/cr/ui.js',
          '<(DEPTH)/ui/webui/resources/js/cr/ui/array_data_model.js',
          '<(DEPTH)/ui/webui/resources/js/cr/ui/autocomplete_list.js',
          '<(DEPTH)/ui/webui/resources/js/cr/ui/bubble.js',
          '<(DEPTH)/ui/webui/resources/js/cr/ui/bubble_button.js',
          '<(DEPTH)/ui/webui/resources/js/cr/ui/command.js',
          '<(DEPTH)/ui/webui/resources/js/cr/ui/controlled_indicator.js',
          '<(DEPTH)/ui/webui/resources/js/cr/ui/focus_manager.js',
          '<(DEPTH)/ui/webui/resources/js/cr/ui/focus_outline_manager.js',
          '<(DEPTH)/ui/webui/resources/js/cr/ui/focus_without_ink.js',
          '<(DEPTH)/ui/webui/resources/js/cr/ui/list.js',
          '<(DEPTH)/ui/webui/resources/js/cr/ui/list_item.js',
          '<(DEPTH)/ui/webui/resources/js/cr/ui/list_selection_controller.js',
          '<(DEPTH)/ui/webui/resources/js/cr/ui/list_selection_model.js',
          '<(DEPTH)/ui/webui/resources/js/cr/ui/list_single_selection_model.js',
          '<(DEPTH)/ui/webui/resources/js/cr/ui/grid.js',
          '<(DEPTH)/ui/webui/resources/js/cr/ui/menu.js',
          '<(DEPTH)/ui/webui/resources/js/cr/ui/menu_item.js',
          '<(DEPTH)/ui/webui/resources/js/cr/ui/overlay.js',
          '<(DEPTH)/ui/webui/resources/js/cr/ui/position_util.js',
          '<(DEPTH)/ui/webui/resources/js/cr/ui/node_utils.js',
          '<(DEPTH)/ui/webui/resources/js/cr/ui/page_manager/page.js',
          '<(DEPTH)/ui/webui/resources/js/cr/ui/page_manager/page_manager.js',
          '<(DEPTH)/ui/webui/resources/js/cr/ui/repeating_button.js',
          '<(DEPTH)/ui/webui/resources/js/cr/ui/touch_handler.js',
          '<(DEPTH)/ui/webui/resources/js/cr/ui/tree.js',
          '<(DEPTH)/ui/webui/resources/js/event_tracker.js',
          '<(DEPTH)/ui/webui/resources/js/icon.js',
          '<(DEPTH)/ui/webui/resources/js/load_time_data.js',
          '<(DEPTH)/ui/webui/resources/js/parse_html_subset.js',
          '<(DEPTH)/ui/webui/resources/js/promise_resolver.js',
          '<(DEPTH)/ui/webui/resources/js/util.js',
          '../chromeos/keyboard/keyboard_utils.js',
          '<(DEPTH)/ui/webui/resources/js/i18n_behavior.js',
          '<(DEPTH)/ui/webui/resources/js/web_ui_listener_behavior.js',
          '../settings/page_visibility.js',
          '../settings/route.js',
          '../settings/people_page/easy_unlock_browser_proxy.js',
          '../settings/people_page/fingerprint_browser_proxy.js',
          '<(DEPTH)/third_party/polymer/v1_0/components-chromium/iron-a11y-keys-behavior/iron-a11y-keys-behavior-extracted.js',
          '<(DEPTH)/third_party/polymer/v1_0/components-chromium/iron-selector/iron-selection-extracted.js',
          '<(DEPTH)/third_party/polymer/v1_0/components-chromium/iron-selector/iron-selectable-extracted.js',
          '<(DEPTH)/third_party/polymer/v1_0/components-chromium/iron-selector/iron-multi-selectable-extracted.js',
          '<(DEPTH)/third_party/polymer/v1_0/components-chromium/iron-menu-behavior/iron-menu-behavior-extracted.js',
          '<(DEPTH)/third_party/polymer/v1_0/components-chromium/iron-menu-behavior/iron-menubar-behavior-extracted.js',
          '<(DEPTH)/ui/webui/resources/cr_elements/cr_profile_avatar_selector/cr_profile_avatar_selector_grid.js',
          '<(DEPTH)/ui/webui/resources/cr_elements/cr_profile_avatar_selector/cr_profile_avatar_selector.js',
          '../settings/people_page/lock_screen_constants.js',
          '<(DEPTH)/third_party/closure_compiler/externs/quick_unlock_private.js',
          '../settings/people_page/lock_state_behavior.js',
          '../settings/people_page/password_prompt_dialog.js',
          '<(DEPTH)/ui/webui/resources/js/assert.js',
          '<(DEPTH)/third_party/polymer/v1_0/components-chromium/iron-meta/iron-meta-extracted.js',
          '<(DEPTH)/third_party/polymer/v1_0/components-chromium/iron-icon/iron-icon-extracted.js',
          '<(DEPTH)/third_party/polymer/v1_0/components-chromium/iron-behaviors/iron-control-state-extracted.js',
          '<(DEPTH)/third_party/polymer/v1_0/components-chromium/iron-behaviors/iron-button-state-extracted.js',
          '<(DEPTH)/third_party/polymer/v1_0/components-chromium/paper-ripple/paper-ripple-extracted.js',
          '<(DEPTH)/third_party/polymer/v1_0/components-chromium/paper-behaviors/paper-ripple-behavior-extracted.js',
          '<(DEPTH)/third_party/polymer/v1_0/components-chromium/paper-behaviors/paper-inky-focus-behavior-extracted.js',
          '<(DEPTH)/third_party/polymer/v1_0/components-chromium/paper-icon-button/paper-icon-button-extracted.js',
          '<(DEPTH)/ui/webui/resources/cr_elements/cr_dialog/cr_dialog.js',
          '../settings/people_page/lock_screen.js',
          '<(DEPTH)/third_party/closure_compiler/externs/bluetooth.js',
          '<(DEPTH)/third_party/closure_compiler/externs/bluetooth_private.js',
          '<(DEPTH)/third_party/closure_compiler/externs/management.js',
          '<(DEPTH)/third_party/closure_compiler/externs/metrics_private.js',
          '<(DEPTH)/third_party/closure_compiler/externs/networking_private.js',
          '<(DEPTH)/third_party/closure_compiler/externs/chrome_send.js',
          '<(DEPTH)/third_party/closure_compiler/externs/web_animations.js',
          '<(DEPTH)/ui/webui/resources/cr_elements/chromeos/network/cr_network_icon_externs.js',
          '../options/options_bundle.js',
          # Note: ^ this is just a copy of
          # ../options/compiled_resources2.gyp:options_bundle#source_files. Most
          # of this code is deprecated, but please keep in sync if you really
          # need to change.
          'channel_change_page.js',
          'help_page.js',
        ],
      },
      'includes': ['../../../../third_party/closure_compiler/compile_js2.gypi'],
    }
  ],
}
