// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is automatically generated from the script in
// chrome/browser/extensions/activity_log/generate_ad_network_hashes.py.
// DO NOT MODIFY BY HAND!

#ifndef CHROME_BROWSER_EXTENSIONS_ACTIVITY_LOG_HASHED_AD_NETWORKS_H_
#define CHROME_BROWSER_EXTENSIONS_ACTIVITY_LOG_HASHED_AD_NETWORKS_H_

#include "base/basictypes.h"

namespace extensions {

extern const char* kHashedAdNetworks[];
extern const int kNumHashedAdNetworks;

}  // namespace extensions

#endif  // CHROME_BROWSER_EXTENSIONS_ACTIVITY_LOG_HASHED_AD_NETWORKS_H_
