/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "git-2016-02-05-e6e47f5"
#endif /* AVUTIL_FFVERSION_H */
