#!/bin/bash

TEST_FILE=${1##*/}
TEST_NAME=${TEST_FILE%.*}

if test -z "$TEST_NAME"; then
	echo "usage: $(basename $0) <test name>"
	exit 1;
fi

WESTON=$abs_builddir/weston
LOGDIR=$abs_builddir/logs

mkdir -p "$LOGDIR"

SERVERLOG="$LOGDIR/${TEST_NAME}-serverlog.txt"
OUTLOG="$LOGDIR/${TEST_NAME}-log.txt"

rm -f "$SERVERLOG"

if test -z "$BACKEND"; then
	BACKEND=headless-backend.so
fi

MODDIR=$abs_builddir/.libs

SHELL_PLUGIN=$MODDIR/desktop-shell.so
TEST_PLUGIN=$MODDIR/weston-test.so
XWAYLAND_PLUGIN=$MODDIR/xwayland.so

case $TEST_FILE in
	*.la|*.so)
		WESTON_BUILD_DIR=$abs_builddir \
		$WESTON --backend=$MODDIR/$BACKEND \
			--no-config \
			--shell=$SHELL_PLUGIN \
			--socket=test-${TEST_NAME} \
			--modules=$MODDIR/${TEST_FILE/.la/.so},$XWAYLAND_PLUGIN \
			--log="$SERVERLOG" \
			&> "$OUTLOG"
		;;
	*)
		WESTON_BUILD_DIR=$abs_builddir \
		WESTON_TEST_CLIENT_PATH=$abs_builddir/$TEST_FILE $WESTON \
			--socket=test-${TEST_NAME} \
			--backend=$MODDIR/$BACKEND \
			--no-config \
			--shell=$SHELL_PLUGIN \
			--log="$SERVERLOG" \
			--modules=$TEST_PLUGIN,$XWAYLAND_PLUGIN \
			$($abs_builddir/$TEST_FILE --params) \
			&> "$OUTLOG"
esac
