// Copyright 2018 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import "oaidl.idl";
import "ocidl.idl";

[
  object,
  oleautomation,
  uuid(A949CB4E-C4F9-44C4-B213-6BF8AA9AC69C),
  helpstring("IElevator Interface"),
  pointer_default(unique)
]
interface IElevator : IUnknown
{
  // Elevators are exposed as methods on IElevator, and provide High Integrity
  // actions. Any changes to add or change a method in IElevator will require a
  // security review.
  //
  // Runs the Chrome Recovery CRX elevated.
  //
  // @param crx_path Path for the recovery CRX.
  // @param browser_appid Omaha AppID for the version of Chrome being recovered.
  // @param browser_version Version of Chrome for the recovery CRX.
  // @param session_id Omaha Session Id.
  // @param caller_proc_id The process id of the calling process.
  // @param proc_handle The process handle valid in the calling process context.
  HRESULT RunRecoveryCRXElevated([in, string] const WCHAR* crx_path,
                                 [in, string] const WCHAR* browser_appid,
                                 [in, string] const WCHAR* browser_version,
                                 [in, string] const WCHAR* session_id,
                                 [in] DWORD caller_proc_id,
                                 [out] ULONG_PTR* proc_handle);
};

[
  uuid(0014D784-7012-4A79-8AB6-ADDB8193A06E),
  version(1.0),
  helpstring("Elevator 1.0 Type Library")
]
library ElevatorLib {
  importlib("stdole2.tlb");

  interface IElevator;
};
