#!/usr/bin/env python
# Copyright (c) 2012 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import os
import sys

import gpu_tools.skpicture_printer

if __name__ == '__main__':
  sys.exit(gpu_tools.skpicture_printer.Main())
