// Copyright 2017 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#ifndef CHROME_BROWSER_VR_ELEMENTS_UI_ELEMENT_NAME_H_
#define CHROME_BROWSER_VR_ELEMENTS_UI_ELEMENT_NAME_H_

#include <string>

namespace vr {

// These identifiers serve as stable, semantic identifiers for UI elements.
enum UiElementName {
  kNone = 0,
  kRoot,
  k2dBrowsingRepositioner,
  k2dBrowsingRoot,
  k2dBrowsingBackground,
  k2dBrowsingDefaultBackground,
  k2dBrowsingTexturedBackground,
  k2dBrowsingForeground,
  k2dBrowsingContentGroup,
  k2dBrowsingViewportAwareRoot,
  kWebVrRoot,
  kWebVrViewportAwareRoot,
  kContentResizer,
  kContentFrame,
  kContentFrameHitPlane,
  kContentQuad,
  kContentQuadShadow,
  kControllerRoot,
  kControllerGroup,
  kLaser,
  kController,
  kRepositionCursor,
  kReticle,
  kReticleLaserGroup,
  kKeyboardVisibilityControlForVoice,
  kKeyboardDmmRoot,
  kKeyboard,
  kBackplane,
  kCeiling,
  kFloor,
  kStars,
  kUpdateKeyboardPrompt,
  kUrlBarPositioner,
  kUrlBarDmmRoot,
  kUrlBar,
  kUrlBarLayout,
  kUrlBarBackButton,
  kUrlBarSeparator,
  kUrlBarSecurityButtonRegion,
  kUrlBarSecurityButton,
  kUrlBarOriginLayout,
  kUrlBarOriginRegion,
  kUrlBarUrlText,
  kUrlBarHintText,
  kUrlBarOverflowButton,
  kOverflowMenuBackplane,
  kOverflowMenu,
  kOverflowMenuLayout,
  kOverflowMenuFordwardButton,
  kOverflowMenuReloadButton,
  kOverflowMenuCloseAllIncognitoTabsItem,
  kOverflowMenuNewIncognitoTabItem,
  kOmniboxVisibiltyControlForVoice,
  kOmniboxVisibilityControlForAudioPermissionPrompt,
  kOmniboxDmmRoot,
  kOmniboxRoot,
  kOmniboxBackground,
  kOmniboxTextField,
  kOmniboxTextFieldLayout,
  kOmniboxVoiceSearchButton,
  kOmniboxCloseButton,
  kOmniboxSuggestions,
  kOmniboxSuggestionsOuterLayout,
  kOmniboxOuterLayout,
  kOmniboxShadow,
  k2dBrowsingVisibiltyControlForVoice,
  k2dBrowsingVisibilityControlForPrompt,
  k2dBrowsingVisibiltyControlForSiteInfoPrompt,
  k2dBrowsingOpacityControlForAudioPermissionPrompt,
  k2dBrowsingOpacityControlForNativeDialogPrompt,
  k2dBrowsingOpacityControlForUpdateKeyboardPrompt,
  kIndicatorBackplane,
  kIndicatorLayout,
  kAudioCaptureIndicator,
  kVideoCaptureIndicator,
  kScreenCaptureIndicator,
  kLocationAccessIndicator,
  kBluetoothConnectedIndicator,
  kWebVrAudioCaptureIndicator,
  kWebVrVideoCaptureIndicator,
  kWebVrScreenCaptureIndicator,
  kWebVrLocationAccessIndicator,
  kWebVrBluetoothConnectedIndicator,
  kLoadingIndicator,
  kLoadingIndicatorForeground,
  kCloseButton,
  kScreenDimmer,
  kExitWarningText,
  kExitWarningBackground,
  kExitPrompt,
  kAudioPermissionPrompt,
  kAudioPermissionPromptShadow,
  kAudioPermissionPromptBackplane,
  kPermissionDialogBackplane,
  kHostedUi,
  kHostedUiBackplane,
  kWebVrUrlToastTransientParent,
  kWebVrUrlToast,
  kExclusiveScreenToastTransientParent,
  kExclusiveScreenToast,
  kExclusiveScreenToastViewportAware,
  kSplashScreenRoot,
  kSplashScreenTransientParent,
  kSplashScreenViewportAwareRoot,
  kSplashScreenText,
  kBackgroundFront,
  kBackgroundLeft,
  kBackgroundBack,
  kBackgroundRight,
  kBackgroundTop,
  kBackgroundBottom,
  kWebVrTimeoutRoot,
  kWebVrTimeoutSpinner,
  kWebVrBackground,
  kWebVrTimeoutMessage,
  kWebVrTimeoutMessageLayout,
  kWebVrTimeoutMessageIcon,
  kWebVrTimeoutMessageText,
  kWebVrTimeoutMessageButton,
  kWebVrTimeoutMessageButtonText,
  kSpeechRecognitionRoot,
  kSpeechRecognitionCircle,
  kSpeechRecognitionMicrophoneIcon,
  kSpeechRecognitionResult,
  kSpeechRecognitionResultText,
  kSpeechRecognitionResultBackplane,
  kSpeechRecognitionListening,
  kSpeechRecognitionListeningGrowingCircle,
  kSpeechRecognitionListeningCloseButton,
  kDownloadedSnackbar,
  kControllerTrackpadLabel,
  kControllerTrackpadRepositionLabel,
  kControllerExitButtonLabel,
  kControllerBackButtonLabel,
  kControllerRepositionFinishLabel,
  kControllerTouchpadButton,
  kControllerAppButton,
  kControllerHomeButton,
  kContentRepositionLabel,
  kContentRepositionHitPlane,
  kContentRepositionVisibilityToggle,

  // This must be last.
  kNumUiElementNames,
};

std::string UiElementNameToString(UiElementName name);

}  // namespace vr

#endif  // CHROME_BROWSER_VR_ELEMENTS_UI_ELEMENT_NAME_H_
