#!/bin/bash

python ../../gyp --debug variables --debug general --format gypd --depth . commands.gyp > commands.gyp.stdout
python ../../gyp --ignore-environment --debug variables --debug general --format gypd --depth . commands.gyp > commands.gyp.ignore-env.stdout
cp -f commands.gypd commands.gypd.golden
