#!/bin/bash

# Copyright 2013 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

set -e

if [ "$1" = "purge" ]; then
  delgroup --quiet chrome-remote-desktop > /dev/null || true
fi

#DEBHELPER#
