exec('./goma.star')
exec('./consoles/chromium.goma.star')
exec('./consoles/chromium.goma.fyi.star')
exec('./consoles/chromium.goma.migration.star')
exec('./consoles/goma.latest.star')
exec('./consoles/luci.chromium.goma.star')
