#!/usr/bin/env python
# Copyright (c) 2012 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
import os
import sys

import perf_tools
from telemetry.page import record_wpr

if __name__ == '__main__':
  sys.exit(record_wpr.Main(os.path.dirname(__file__)))
