#!/usr/bin/env python
# Copyright 2012 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
import os
import sys


from chrome_telemetry_build import chromium_config
sys.path.append(chromium_config.GetTelemetryDir())

from telemetry import record_wpr


if __name__ == '__main__':
  _perf_dir = os.path.dirname(__file__)
  sys.exit(record_wpr.Main(_perf_dir))
