#!/usr/bin/env python
# Copyright (c) 2012 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import os
import sys


sys.path.append(os.path.join(os.path.dirname(__file__), os.pardir, 'telemetry'))

from telemetry.core import environment
from telemetry.core import util
from telemetry.page import page_measurement_runner
from telemetry.util import bootstrap


BASE_DIR = os.path.dirname(os.path.realpath(__file__))
CROS_BOOSTRAP_DEPS_PATH = os.path.join(
    util.GetChromiumSrcDir(), 'tools', 'cros', 'bootstrap_deps')


def main():
  if '--print-bootstrap-deps-cros' in sys.argv:
    print bootstrap.ListAllDepsPaths(CROS_BOOSTRAP_DEPS_PATH)
    return 0

  runner = page_measurement_runner.PageMeasurementRunner()
  env = environment.Environment([BASE_DIR])
  return runner.Run(env)


if __name__ == '__main__':
  sys.exit(main())
