#!/usr/bin/env python
# Copyright 2013 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

"""This script runs unit tests of the code in the perf directory.

This script DOES NOT run benchmarks. run_benchmark does that.
"""

import os
import subprocess
import sys


if __name__ == '__main__':
  perf_dir = os.path.dirname(os.path.realpath(__file__))
  telemetry_dir = os.path.realpath(os.path.join(perf_dir, '..', 'telemetry'))

  env = os.environ.copy()
  if 'PYTHONPATH' in env:
    env['PYTHONPATH'] = env['PYTHONPATH'] + os.pathsep + telemetry_dir
  else:
    env['PYTHONPATH'] = telemetry_dir

  path_to_run_tests = os.path.join(telemetry_dir, 'telemetry', 'unittest_util',
                                   'run_tests.py')
  argv = ['--top-level-dir', perf_dir] + sys.argv[1:]
  sys.exit(subprocess.call([sys.executable, path_to_run_tests] + argv, env=env))
