#!/usr/bin/env python
# Copyright (c) 2012 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import os
import sys


sys.path.append(os.path.join(os.path.dirname(__file__), os.pardir, 'telemetry'))

from telemetry.core import environment
from telemetry.core import util
from telemetry.page import page_measurement_runner
from telemetry.util import bootstrap


BASE_DIR = os.path.dirname(os.path.realpath(__file__))
CROS_BOOSTRAP_DEPS_PATH = os.path.join(
    util.GetChromiumSrcDir(), 'tools', 'cros', 'bootstrap_deps')


def main():
  if '--print-bootstrap-deps-cros' in sys.argv:
    print bootstrap.ListAllDepsPaths(CROS_BOOSTRAP_DEPS_PATH)
    return 0

  old_benchmark_names = {
  }

  # There are bots that are hard-coded to run some specific named tests.
  # Convert these to the current naming conventions by overriding them
  # in the runner.
  class MeasurementRunner(page_measurement_runner.PageMeasurementRunner):
    def GetModernizedTestName(self, arg):
      if arg not in old_benchmark_names:
        return arg
      sys.stderr.write(
          'An old name %s was given. Please use %s in the future.\n' % (
          arg,
          old_benchmark_names.get(arg)))
      return old_benchmark_names[arg]

  runner = MeasurementRunner()
  env = environment.Environment([BASE_DIR])
  return runner.Run(env)


if __name__ == '__main__':
  sys.exit(main())
