// Copyright (c) 2012 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is auto-generated from
// gpu/command_buffer/build_gles2_cmd_buffer.py
// DO NOT EDIT!

#ifndef GPU_COMMAND_BUFFER_COMMON_GLES2_CMD_IDS_AUTOGEN_H_
#define GPU_COMMAND_BUFFER_COMMON_GLES2_CMD_IDS_AUTOGEN_H_

#define GLES2_COMMAND_LIST(OP) \
  OP(ActiveTexture)                                            /* 256 */ \
  OP(AttachShader)                                             /* 257 */ \
  OP(BindAttribLocation)                                       /* 258 */ \
  OP(BindAttribLocationImmediate)                              /* 259 */ \
  OP(BindAttribLocationBucket)                                 /* 260 */ \
  OP(BindBuffer)                                               /* 261 */ \
  OP(BindFramebuffer)                                          /* 262 */ \
  OP(BindRenderbuffer)                                         /* 263 */ \
  OP(BindTexture)                                              /* 264 */ \
  OP(BlendColor)                                               /* 265 */ \
  OP(BlendEquation)                                            /* 266 */ \
  OP(BlendEquationSeparate)                                    /* 267 */ \
  OP(BlendFunc)                                                /* 268 */ \
  OP(BlendFuncSeparate)                                        /* 269 */ \
  OP(BufferData)                                               /* 270 */ \
  OP(BufferDataImmediate)                                      /* 271 */ \
  OP(BufferSubData)                                            /* 272 */ \
  OP(BufferSubDataImmediate)                                   /* 273 */ \
  OP(CheckFramebufferStatus)                                   /* 274 */ \
  OP(Clear)                                                    /* 275 */ \
  OP(ClearColor)                                               /* 276 */ \
  OP(ClearDepthf)                                              /* 277 */ \
  OP(ClearStencil)                                             /* 278 */ \
  OP(ColorMask)                                                /* 279 */ \
  OP(CompileShader)                                            /* 280 */ \
  OP(CompressedTexImage2D)                                     /* 281 */ \
  OP(CompressedTexImage2DBucket)                               /* 282 */ \
  OP(CompressedTexSubImage2D)                                  /* 283 */ \
  OP(CompressedTexSubImage2DImmediate)                         /* 284 */ \
  OP(CompressedTexSubImage2DBucket)                            /* 285 */ \
  OP(CopyTexImage2D)                                           /* 286 */ \
  OP(CopyTexSubImage2D)                                        /* 287 */ \
  OP(CreateProgram)                                            /* 288 */ \
  OP(CreateShader)                                             /* 289 */ \
  OP(CullFace)                                                 /* 290 */ \
  OP(DeleteBuffers)                                            /* 291 */ \
  OP(DeleteBuffersImmediate)                                   /* 292 */ \
  OP(DeleteFramebuffers)                                       /* 293 */ \
  OP(DeleteFramebuffersImmediate)                              /* 294 */ \
  OP(DeleteProgram)                                            /* 295 */ \
  OP(DeleteRenderbuffers)                                      /* 296 */ \
  OP(DeleteRenderbuffersImmediate)                             /* 297 */ \
  OP(DeleteShader)                                             /* 298 */ \
  OP(DeleteTextures)                                           /* 299 */ \
  OP(DeleteTexturesImmediate)                                  /* 300 */ \
  OP(DepthFunc)                                                /* 301 */ \
  OP(DepthMask)                                                /* 302 */ \
  OP(DepthRangef)                                              /* 303 */ \
  OP(DetachShader)                                             /* 304 */ \
  OP(Disable)                                                  /* 305 */ \
  OP(DisableVertexAttribArray)                                 /* 306 */ \
  OP(DrawArrays)                                               /* 307 */ \
  OP(DrawElements)                                             /* 308 */ \
  OP(Enable)                                                   /* 309 */ \
  OP(EnableVertexAttribArray)                                  /* 310 */ \
  OP(Finish)                                                   /* 311 */ \
  OP(Flush)                                                    /* 312 */ \
  OP(FramebufferRenderbuffer)                                  /* 313 */ \
  OP(FramebufferTexture2D)                                     /* 314 */ \
  OP(FrontFace)                                                /* 315 */ \
  OP(GenBuffers)                                               /* 316 */ \
  OP(GenBuffersImmediate)                                      /* 317 */ \
  OP(GenerateMipmap)                                           /* 318 */ \
  OP(GenFramebuffers)                                          /* 319 */ \
  OP(GenFramebuffersImmediate)                                 /* 320 */ \
  OP(GenRenderbuffers)                                         /* 321 */ \
  OP(GenRenderbuffersImmediate)                                /* 322 */ \
  OP(GenTextures)                                              /* 323 */ \
  OP(GenTexturesImmediate)                                     /* 324 */ \
  OP(GetActiveAttrib)                                          /* 325 */ \
  OP(GetActiveUniform)                                         /* 326 */ \
  OP(GetAttachedShaders)                                       /* 327 */ \
  OP(GetAttribLocation)                                        /* 328 */ \
  OP(GetAttribLocationImmediate)                               /* 329 */ \
  OP(GetAttribLocationBucket)                                  /* 330 */ \
  OP(GetBooleanv)                                              /* 331 */ \
  OP(GetBufferParameteriv)                                     /* 332 */ \
  OP(GetError)                                                 /* 333 */ \
  OP(GetFloatv)                                                /* 334 */ \
  OP(GetFramebufferAttachmentParameteriv)                      /* 335 */ \
  OP(GetIntegerv)                                              /* 336 */ \
  OP(GetProgramiv)                                             /* 337 */ \
  OP(GetProgramInfoLog)                                        /* 338 */ \
  OP(GetRenderbufferParameteriv)                               /* 339 */ \
  OP(GetShaderiv)                                              /* 340 */ \
  OP(GetShaderInfoLog)                                         /* 341 */ \
  OP(GetShaderPrecisionFormat)                                 /* 342 */ \
  OP(GetShaderSource)                                          /* 343 */ \
  OP(GetString)                                                /* 344 */ \
  OP(GetTexParameterfv)                                        /* 345 */ \
  OP(GetTexParameteriv)                                        /* 346 */ \
  OP(GetUniformfv)                                             /* 347 */ \
  OP(GetUniformiv)                                             /* 348 */ \
  OP(GetUniformLocation)                                       /* 349 */ \
  OP(GetUniformLocationImmediate)                              /* 350 */ \
  OP(GetUniformLocationBucket)                                 /* 351 */ \
  OP(GetVertexAttribfv)                                        /* 352 */ \
  OP(GetVertexAttribiv)                                        /* 353 */ \
  OP(GetVertexAttribPointerv)                                  /* 354 */ \
  OP(Hint)                                                     /* 355 */ \
  OP(IsBuffer)                                                 /* 356 */ \
  OP(IsEnabled)                                                /* 357 */ \
  OP(IsFramebuffer)                                            /* 358 */ \
  OP(IsProgram)                                                /* 359 */ \
  OP(IsRenderbuffer)                                           /* 360 */ \
  OP(IsShader)                                                 /* 361 */ \
  OP(IsTexture)                                                /* 362 */ \
  OP(LineWidth)                                                /* 363 */ \
  OP(LinkProgram)                                              /* 364 */ \
  OP(PixelStorei)                                              /* 365 */ \
  OP(PolygonOffset)                                            /* 366 */ \
  OP(ReadPixels)                                               /* 367 */ \
  OP(ReleaseShaderCompiler)                                    /* 368 */ \
  OP(RenderbufferStorage)                                      /* 369 */ \
  OP(SampleCoverage)                                           /* 370 */ \
  OP(Scissor)                                                  /* 371 */ \
  OP(ShaderBinary)                                             /* 372 */ \
  OP(ShaderSource)                                             /* 373 */ \
  OP(ShaderSourceImmediate)                                    /* 374 */ \
  OP(ShaderSourceBucket)                                       /* 375 */ \
  OP(StencilFunc)                                              /* 376 */ \
  OP(StencilFuncSeparate)                                      /* 377 */ \
  OP(StencilMask)                                              /* 378 */ \
  OP(StencilMaskSeparate)                                      /* 379 */ \
  OP(StencilOp)                                                /* 380 */ \
  OP(StencilOpSeparate)                                        /* 381 */ \
  OP(TexImage2D)                                               /* 382 */ \
  OP(TexParameterf)                                            /* 383 */ \
  OP(TexParameterfv)                                           /* 384 */ \
  OP(TexParameterfvImmediate)                                  /* 385 */ \
  OP(TexParameteri)                                            /* 386 */ \
  OP(TexParameteriv)                                           /* 387 */ \
  OP(TexParameterivImmediate)                                  /* 388 */ \
  OP(TexSubImage2D)                                            /* 389 */ \
  OP(Uniform1f)                                                /* 390 */ \
  OP(Uniform1fv)                                               /* 391 */ \
  OP(Uniform1fvImmediate)                                      /* 392 */ \
  OP(Uniform1i)                                                /* 393 */ \
  OP(Uniform1iv)                                               /* 394 */ \
  OP(Uniform1ivImmediate)                                      /* 395 */ \
  OP(Uniform2f)                                                /* 396 */ \
  OP(Uniform2fv)                                               /* 397 */ \
  OP(Uniform2fvImmediate)                                      /* 398 */ \
  OP(Uniform2i)                                                /* 399 */ \
  OP(Uniform2iv)                                               /* 400 */ \
  OP(Uniform2ivImmediate)                                      /* 401 */ \
  OP(Uniform3f)                                                /* 402 */ \
  OP(Uniform3fv)                                               /* 403 */ \
  OP(Uniform3fvImmediate)                                      /* 404 */ \
  OP(Uniform3i)                                                /* 405 */ \
  OP(Uniform3iv)                                               /* 406 */ \
  OP(Uniform3ivImmediate)                                      /* 407 */ \
  OP(Uniform4f)                                                /* 408 */ \
  OP(Uniform4fv)                                               /* 409 */ \
  OP(Uniform4fvImmediate)                                      /* 410 */ \
  OP(Uniform4i)                                                /* 411 */ \
  OP(Uniform4iv)                                               /* 412 */ \
  OP(Uniform4ivImmediate)                                      /* 413 */ \
  OP(UniformMatrix2fv)                                         /* 414 */ \
  OP(UniformMatrix2fvImmediate)                                /* 415 */ \
  OP(UniformMatrix3fv)                                         /* 416 */ \
  OP(UniformMatrix3fvImmediate)                                /* 417 */ \
  OP(UniformMatrix4fv)                                         /* 418 */ \
  OP(UniformMatrix4fvImmediate)                                /* 419 */ \
  OP(UseProgram)                                               /* 420 */ \
  OP(ValidateProgram)                                          /* 421 */ \
  OP(VertexAttrib1f)                                           /* 422 */ \
  OP(VertexAttrib1fv)                                          /* 423 */ \
  OP(VertexAttrib1fvImmediate)                                 /* 424 */ \
  OP(VertexAttrib2f)                                           /* 425 */ \
  OP(VertexAttrib2fv)                                          /* 426 */ \
  OP(VertexAttrib2fvImmediate)                                 /* 427 */ \
  OP(VertexAttrib3f)                                           /* 428 */ \
  OP(VertexAttrib3fv)                                          /* 429 */ \
  OP(VertexAttrib3fvImmediate)                                 /* 430 */ \
  OP(VertexAttrib4f)                                           /* 431 */ \
  OP(VertexAttrib4fv)                                          /* 432 */ \
  OP(VertexAttrib4fvImmediate)                                 /* 433 */ \
  OP(VertexAttribPointer)                                      /* 434 */ \
  OP(Viewport)                                                 /* 435 */ \
  OP(BlitFramebufferEXT)                                       /* 436 */ \
  OP(RenderbufferStorageMultisampleEXT)                        /* 437 */ \
  OP(FramebufferTexture2DMultisampleEXT)                       /* 438 */ \
  OP(TexStorage2DEXT)                                          /* 439 */ \
  OP(GenQueriesEXT)                                            /* 440 */ \
  OP(GenQueriesEXTImmediate)                                   /* 441 */ \
  OP(DeleteQueriesEXT)                                         /* 442 */ \
  OP(DeleteQueriesEXTImmediate)                                /* 443 */ \
  OP(BeginQueryEXT)                                            /* 444 */ \
  OP(EndQueryEXT)                                              /* 445 */ \
  OP(InsertEventMarkerEXT)                                     /* 446 */ \
  OP(PushGroupMarkerEXT)                                       /* 447 */ \
  OP(PopGroupMarkerEXT)                                        /* 448 */ \
  OP(GenVertexArraysOES)                                       /* 449 */ \
  OP(GenVertexArraysOESImmediate)                              /* 450 */ \
  OP(DeleteVertexArraysOES)                                    /* 451 */ \
  OP(DeleteVertexArraysOESImmediate)                           /* 452 */ \
  OP(IsVertexArrayOES)                                         /* 453 */ \
  OP(BindVertexArrayOES)                                       /* 454 */ \
  OP(SwapBuffers)                                              /* 455 */ \
  OP(GetMaxValueInBufferCHROMIUM)                              /* 456 */ \
  OP(GenSharedIdsCHROMIUM)                                     /* 457 */ \
  OP(DeleteSharedIdsCHROMIUM)                                  /* 458 */ \
  OP(RegisterSharedIdsCHROMIUM)                                /* 459 */ \
  OP(EnableFeatureCHROMIUM)                                    /* 460 */ \
  OP(ResizeCHROMIUM)                                           /* 461 */ \
  OP(GetRequestableExtensionsCHROMIUM)                         /* 462 */ \
  OP(RequestExtensionCHROMIUM)                                 /* 463 */ \
  OP(GetMultipleIntegervCHROMIUM)                              /* 464 */ \
  OP(GetProgramInfoCHROMIUM)                                   /* 465 */ \
  OP(CreateStreamTextureCHROMIUM)                              /* 466 */ \
  OP(DestroyStreamTextureCHROMIUM)                             /* 467 */ \
  OP(GetTranslatedShaderSourceANGLE)                           /* 468 */ \
  OP(PostSubBufferCHROMIUM)                                    /* 469 */ \
  OP(TexImageIOSurface2DCHROMIUM)                              /* 470 */ \
  OP(CopyTextureCHROMIUM)                                      /* 471 */ \
  OP(DrawArraysInstancedANGLE)                                 /* 472 */ \
  OP(DrawElementsInstancedANGLE)                               /* 473 */ \
  OP(VertexAttribDivisorANGLE)                                 /* 474 */ \
  OP(GenMailboxCHROMIUM)                                       /* 475 */ \
  OP(ProduceTextureCHROMIUM)                                   /* 476 */ \
  OP(ProduceTextureCHROMIUMImmediate)                          /* 477 */ \
  OP(ConsumeTextureCHROMIUM)                                   /* 478 */ \
  OP(ConsumeTextureCHROMIUMImmediate)                          /* 479 */ \
  OP(BindUniformLocationCHROMIUM)                              /* 480 */ \
  OP(BindUniformLocationCHROMIUMImmediate)                     /* 481 */ \
  OP(BindUniformLocationCHROMIUMBucket)                        /* 482 */ \
  OP(BindTexImage2DCHROMIUM)                                   /* 483 */ \
  OP(ReleaseTexImage2DCHROMIUM)                                /* 484 */ \
  OP(TraceBeginCHROMIUM)                                       /* 485 */ \
  OP(TraceEndCHROMIUM)                                         /* 486 */ \
  OP(AsyncTexSubImage2DCHROMIUM)                               /* 487 */ \
  OP(AsyncTexImage2DCHROMIUM)                                  /* 488 */ \
  OP(WaitAsyncTexImage2DCHROMIUM)                              /* 489 */ \
  OP(DiscardFramebufferEXT)                                    /* 490 */ \
  OP(DiscardFramebufferEXTImmediate)                           /* 491 */ \
  OP(LoseContextCHROMIUM)                                      /* 492 */ \
  OP(InsertSyncPointCHROMIUM)                                  /* 493 */ \
  OP(WaitSyncPointCHROMIUM)                                    /* 494 */ \
  OP(DrawBuffersEXT)                                           /* 495 */ \
  OP(DrawBuffersEXTImmediate)                                  /* 496 */ \

enum CommandId {
  kStartPoint = cmd::kLastCommonId,  // All GLES2 commands start after this.
#define GLES2_CMD_OP(name) k ## name,
  GLES2_COMMAND_LIST(GLES2_CMD_OP)
#undef GLES2_CMD_OP
  kNumCommands
};

#endif  // GPU_COMMAND_BUFFER_COMMON_GLES2_CMD_IDS_AUTOGEN_H_

