// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is auto-generated from
// gpu/command_buffer/build_gles2_cmd_buffer.py
// It's formatted by clang-format using chromium coding style:
//    clang-format -i -style=chromium filename
// DO NOT EDIT!

#ifndef GPU_COMMAND_BUFFER_COMMON_GLES2_CMD_IDS_AUTOGEN_H_
#define GPU_COMMAND_BUFFER_COMMON_GLES2_CMD_IDS_AUTOGEN_H_

#define GLES2_COMMAND_LIST(OP)                           \
  OP(ActiveTexture)                            /* 256 */ \
  OP(AttachShader)                             /* 257 */ \
  OP(BindAttribLocationBucket)                 /* 258 */ \
  OP(BindBuffer)                               /* 259 */ \
  OP(BindBufferBase)                           /* 260 */ \
  OP(BindBufferRange)                          /* 261 */ \
  OP(BindFramebuffer)                          /* 262 */ \
  OP(BindRenderbuffer)                         /* 263 */ \
  OP(BindSampler)                              /* 264 */ \
  OP(BindTexture)                              /* 265 */ \
  OP(BindTransformFeedback)                    /* 266 */ \
  OP(BlendColor)                               /* 267 */ \
  OP(BlendEquation)                            /* 268 */ \
  OP(BlendEquationSeparate)                    /* 269 */ \
  OP(BlendFunc)                                /* 270 */ \
  OP(BlendFuncSeparate)                        /* 271 */ \
  OP(BufferData)                               /* 272 */ \
  OP(BufferSubData)                            /* 273 */ \
  OP(CheckFramebufferStatus)                   /* 274 */ \
  OP(Clear)                                    /* 275 */ \
  OP(ClearBufferfi)                            /* 276 */ \
  OP(ClearBufferfvImmediate)                   /* 277 */ \
  OP(ClearBufferivImmediate)                   /* 278 */ \
  OP(ClearBufferuivImmediate)                  /* 279 */ \
  OP(ClearColor)                               /* 280 */ \
  OP(ClearDepthf)                              /* 281 */ \
  OP(ClearStencil)                             /* 282 */ \
  OP(ColorMask)                                /* 283 */ \
  OP(CompileShader)                            /* 284 */ \
  OP(CompressedTexImage2DBucket)               /* 285 */ \
  OP(CompressedTexImage2D)                     /* 286 */ \
  OP(CompressedTexSubImage2DBucket)            /* 287 */ \
  OP(CompressedTexSubImage2D)                  /* 288 */ \
  OP(CopyBufferSubData)                        /* 289 */ \
  OP(CopyTexImage2D)                           /* 290 */ \
  OP(CopyTexSubImage2D)                        /* 291 */ \
  OP(CreateProgram)                            /* 292 */ \
  OP(CreateShader)                             /* 293 */ \
  OP(CullFace)                                 /* 294 */ \
  OP(DeleteBuffersImmediate)                   /* 295 */ \
  OP(DeleteFramebuffersImmediate)              /* 296 */ \
  OP(DeleteProgram)                            /* 297 */ \
  OP(DeleteRenderbuffersImmediate)             /* 298 */ \
  OP(DeleteSamplersImmediate)                  /* 299 */ \
  OP(DeleteSync)                               /* 300 */ \
  OP(DeleteShader)                             /* 301 */ \
  OP(DeleteTexturesImmediate)                  /* 302 */ \
  OP(DeleteTransformFeedbacksImmediate)        /* 303 */ \
  OP(DepthFunc)                                /* 304 */ \
  OP(DepthMask)                                /* 305 */ \
  OP(DepthRangef)                              /* 306 */ \
  OP(DetachShader)                             /* 307 */ \
  OP(Disable)                                  /* 308 */ \
  OP(DisableVertexAttribArray)                 /* 309 */ \
  OP(DrawArrays)                               /* 310 */ \
  OP(DrawElements)                             /* 311 */ \
  OP(Enable)                                   /* 312 */ \
  OP(EnableVertexAttribArray)                  /* 313 */ \
  OP(FenceSync)                                /* 314 */ \
  OP(Finish)                                   /* 315 */ \
  OP(Flush)                                    /* 316 */ \
  OP(FramebufferRenderbuffer)                  /* 317 */ \
  OP(FramebufferTexture2D)                     /* 318 */ \
  OP(FramebufferTextureLayer)                  /* 319 */ \
  OP(FrontFace)                                /* 320 */ \
  OP(GenBuffersImmediate)                      /* 321 */ \
  OP(GenerateMipmap)                           /* 322 */ \
  OP(GenFramebuffersImmediate)                 /* 323 */ \
  OP(GenRenderbuffersImmediate)                /* 324 */ \
  OP(GenSamplersImmediate)                     /* 325 */ \
  OP(GenTexturesImmediate)                     /* 326 */ \
  OP(GenTransformFeedbacksImmediate)           /* 327 */ \
  OP(GetActiveAttrib)                          /* 328 */ \
  OP(GetActiveUniform)                         /* 329 */ \
  OP(GetAttachedShaders)                       /* 330 */ \
  OP(GetAttribLocation)                        /* 331 */ \
  OP(GetBooleanv)                              /* 332 */ \
  OP(GetBufferParameteriv)                     /* 333 */ \
  OP(GetError)                                 /* 334 */ \
  OP(GetFloatv)                                /* 335 */ \
  OP(GetFramebufferAttachmentParameteriv)      /* 336 */ \
  OP(GetIntegerv)                              /* 337 */ \
  OP(GetInternalformativ)                      /* 338 */ \
  OP(GetProgramiv)                             /* 339 */ \
  OP(GetProgramInfoLog)                        /* 340 */ \
  OP(GetRenderbufferParameteriv)               /* 341 */ \
  OP(GetSamplerParameterfv)                    /* 342 */ \
  OP(GetSamplerParameteriv)                    /* 343 */ \
  OP(GetShaderiv)                              /* 344 */ \
  OP(GetShaderInfoLog)                         /* 345 */ \
  OP(GetShaderPrecisionFormat)                 /* 346 */ \
  OP(GetShaderSource)                          /* 347 */ \
  OP(GetString)                                /* 348 */ \
  OP(GetTexParameterfv)                        /* 349 */ \
  OP(GetTexParameteriv)                        /* 350 */ \
  OP(GetUniformfv)                             /* 351 */ \
  OP(GetUniformiv)                             /* 352 */ \
  OP(GetUniformLocation)                       /* 353 */ \
  OP(GetVertexAttribfv)                        /* 354 */ \
  OP(GetVertexAttribiv)                        /* 355 */ \
  OP(GetVertexAttribPointerv)                  /* 356 */ \
  OP(Hint)                                     /* 357 */ \
  OP(InvalidateFramebufferImmediate)           /* 358 */ \
  OP(InvalidateSubFramebufferImmediate)        /* 359 */ \
  OP(IsBuffer)                                 /* 360 */ \
  OP(IsEnabled)                                /* 361 */ \
  OP(IsFramebuffer)                            /* 362 */ \
  OP(IsProgram)                                /* 363 */ \
  OP(IsRenderbuffer)                           /* 364 */ \
  OP(IsSampler)                                /* 365 */ \
  OP(IsShader)                                 /* 366 */ \
  OP(IsSync)                                   /* 367 */ \
  OP(IsTexture)                                /* 368 */ \
  OP(IsTransformFeedback)                      /* 369 */ \
  OP(LineWidth)                                /* 370 */ \
  OP(LinkProgram)                              /* 371 */ \
  OP(PauseTransformFeedback)                   /* 372 */ \
  OP(PixelStorei)                              /* 373 */ \
  OP(PolygonOffset)                            /* 374 */ \
  OP(ReadBuffer)                               /* 375 */ \
  OP(ReadPixels)                               /* 376 */ \
  OP(ReleaseShaderCompiler)                    /* 377 */ \
  OP(RenderbufferStorage)                      /* 378 */ \
  OP(ResumeTransformFeedback)                  /* 379 */ \
  OP(SampleCoverage)                           /* 380 */ \
  OP(SamplerParameterf)                        /* 381 */ \
  OP(SamplerParameterfvImmediate)              /* 382 */ \
  OP(SamplerParameteri)                        /* 383 */ \
  OP(SamplerParameterivImmediate)              /* 384 */ \
  OP(Scissor)                                  /* 385 */ \
  OP(ShaderBinary)                             /* 386 */ \
  OP(ShaderSourceBucket)                       /* 387 */ \
  OP(StencilFunc)                              /* 388 */ \
  OP(StencilFuncSeparate)                      /* 389 */ \
  OP(StencilMask)                              /* 390 */ \
  OP(StencilMaskSeparate)                      /* 391 */ \
  OP(StencilOp)                                /* 392 */ \
  OP(StencilOpSeparate)                        /* 393 */ \
  OP(TexImage2D)                               /* 394 */ \
  OP(TexImage3D)                               /* 395 */ \
  OP(TexParameterf)                            /* 396 */ \
  OP(TexParameterfvImmediate)                  /* 397 */ \
  OP(TexParameteri)                            /* 398 */ \
  OP(TexParameterivImmediate)                  /* 399 */ \
  OP(TexStorage3D)                             /* 400 */ \
  OP(TexSubImage2D)                            /* 401 */ \
  OP(TexSubImage3D)                            /* 402 */ \
  OP(Uniform1f)                                /* 403 */ \
  OP(Uniform1fvImmediate)                      /* 404 */ \
  OP(Uniform1i)                                /* 405 */ \
  OP(Uniform1ivImmediate)                      /* 406 */ \
  OP(Uniform1ui)                               /* 407 */ \
  OP(Uniform1uivImmediate)                     /* 408 */ \
  OP(Uniform2f)                                /* 409 */ \
  OP(Uniform2fvImmediate)                      /* 410 */ \
  OP(Uniform2i)                                /* 411 */ \
  OP(Uniform2ivImmediate)                      /* 412 */ \
  OP(Uniform2ui)                               /* 413 */ \
  OP(Uniform2uivImmediate)                     /* 414 */ \
  OP(Uniform3f)                                /* 415 */ \
  OP(Uniform3fvImmediate)                      /* 416 */ \
  OP(Uniform3i)                                /* 417 */ \
  OP(Uniform3ivImmediate)                      /* 418 */ \
  OP(Uniform3ui)                               /* 419 */ \
  OP(Uniform3uivImmediate)                     /* 420 */ \
  OP(Uniform4f)                                /* 421 */ \
  OP(Uniform4fvImmediate)                      /* 422 */ \
  OP(Uniform4i)                                /* 423 */ \
  OP(Uniform4ivImmediate)                      /* 424 */ \
  OP(Uniform4ui)                               /* 425 */ \
  OP(Uniform4uivImmediate)                     /* 426 */ \
  OP(UniformMatrix2fvImmediate)                /* 427 */ \
  OP(UniformMatrix2x3fvImmediate)              /* 428 */ \
  OP(UniformMatrix2x4fvImmediate)              /* 429 */ \
  OP(UniformMatrix3fvImmediate)                /* 430 */ \
  OP(UniformMatrix3x2fvImmediate)              /* 431 */ \
  OP(UniformMatrix3x4fvImmediate)              /* 432 */ \
  OP(UniformMatrix4fvImmediate)                /* 433 */ \
  OP(UniformMatrix4x2fvImmediate)              /* 434 */ \
  OP(UniformMatrix4x3fvImmediate)              /* 435 */ \
  OP(UseProgram)                               /* 436 */ \
  OP(ValidateProgram)                          /* 437 */ \
  OP(VertexAttrib1f)                           /* 438 */ \
  OP(VertexAttrib1fvImmediate)                 /* 439 */ \
  OP(VertexAttrib2f)                           /* 440 */ \
  OP(VertexAttrib2fvImmediate)                 /* 441 */ \
  OP(VertexAttrib3f)                           /* 442 */ \
  OP(VertexAttrib3fvImmediate)                 /* 443 */ \
  OP(VertexAttrib4f)                           /* 444 */ \
  OP(VertexAttrib4fvImmediate)                 /* 445 */ \
  OP(VertexAttribI4i)                          /* 446 */ \
  OP(VertexAttribI4ivImmediate)                /* 447 */ \
  OP(VertexAttribI4ui)                         /* 448 */ \
  OP(VertexAttribI4uivImmediate)               /* 449 */ \
  OP(VertexAttribIPointer)                     /* 450 */ \
  OP(VertexAttribPointer)                      /* 451 */ \
  OP(Viewport)                                 /* 452 */ \
  OP(BlitFramebufferCHROMIUM)                  /* 453 */ \
  OP(RenderbufferStorageMultisampleCHROMIUM)   /* 454 */ \
  OP(RenderbufferStorageMultisampleEXT)        /* 455 */ \
  OP(FramebufferTexture2DMultisampleEXT)       /* 456 */ \
  OP(TexStorage2DEXT)                          /* 457 */ \
  OP(GenQueriesEXTImmediate)                   /* 458 */ \
  OP(DeleteQueriesEXTImmediate)                /* 459 */ \
  OP(BeginQueryEXT)                            /* 460 */ \
  OP(BeginTransformFeedback)                   /* 461 */ \
  OP(EndQueryEXT)                              /* 462 */ \
  OP(EndTransformFeedback)                     /* 463 */ \
  OP(InsertEventMarkerEXT)                     /* 464 */ \
  OP(PushGroupMarkerEXT)                       /* 465 */ \
  OP(PopGroupMarkerEXT)                        /* 466 */ \
  OP(GenVertexArraysOESImmediate)              /* 467 */ \
  OP(DeleteVertexArraysOESImmediate)           /* 468 */ \
  OP(IsVertexArrayOES)                         /* 469 */ \
  OP(BindVertexArrayOES)                       /* 470 */ \
  OP(SwapBuffers)                              /* 471 */ \
  OP(GetMaxValueInBufferCHROMIUM)              /* 472 */ \
  OP(EnableFeatureCHROMIUM)                    /* 473 */ \
  OP(ResizeCHROMIUM)                           /* 474 */ \
  OP(GetRequestableExtensionsCHROMIUM)         /* 475 */ \
  OP(RequestExtensionCHROMIUM)                 /* 476 */ \
  OP(GetProgramInfoCHROMIUM)                   /* 477 */ \
  OP(GetTranslatedShaderSourceANGLE)           /* 478 */ \
  OP(PostSubBufferCHROMIUM)                    /* 479 */ \
  OP(TexImageIOSurface2DCHROMIUM)              /* 480 */ \
  OP(CopyTextureCHROMIUM)                      /* 481 */ \
  OP(DrawArraysInstancedANGLE)                 /* 482 */ \
  OP(DrawElementsInstancedANGLE)               /* 483 */ \
  OP(VertexAttribDivisorANGLE)                 /* 484 */ \
  OP(GenMailboxCHROMIUM)                       /* 485 */ \
  OP(ProduceTextureCHROMIUMImmediate)          /* 486 */ \
  OP(ProduceTextureDirectCHROMIUMImmediate)    /* 487 */ \
  OP(ConsumeTextureCHROMIUMImmediate)          /* 488 */ \
  OP(CreateAndConsumeTextureCHROMIUMImmediate) /* 489 */ \
  OP(BindUniformLocationCHROMIUMBucket)        /* 490 */ \
  OP(GenValuebuffersCHROMIUMImmediate)         /* 491 */ \
  OP(DeleteValuebuffersCHROMIUMImmediate)      /* 492 */ \
  OP(IsValuebufferCHROMIUM)                    /* 493 */ \
  OP(BindValuebufferCHROMIUM)                  /* 494 */ \
  OP(SubscribeValueCHROMIUM)                   /* 495 */ \
  OP(PopulateSubscribedValuesCHROMIUM)         /* 496 */ \
  OP(UniformValuebufferCHROMIUM)               /* 497 */ \
  OP(BindTexImage2DCHROMIUM)                   /* 498 */ \
  OP(ReleaseTexImage2DCHROMIUM)                /* 499 */ \
  OP(TraceBeginCHROMIUM)                       /* 500 */ \
  OP(TraceEndCHROMIUM)                         /* 501 */ \
  OP(AsyncTexSubImage2DCHROMIUM)               /* 502 */ \
  OP(AsyncTexImage2DCHROMIUM)                  /* 503 */ \
  OP(WaitAsyncTexImage2DCHROMIUM)              /* 504 */ \
  OP(WaitAllAsyncTexImage2DCHROMIUM)           /* 505 */ \
  OP(DiscardFramebufferEXTImmediate)           /* 506 */ \
  OP(LoseContextCHROMIUM)                      /* 507 */ \
  OP(InsertSyncPointCHROMIUM)                  /* 508 */ \
  OP(WaitSyncPointCHROMIUM)                    /* 509 */ \
  OP(DrawBuffersEXTImmediate)                  /* 510 */ \
  OP(DiscardBackbufferCHROMIUM)                /* 511 */ \
  OP(ScheduleOverlayPlaneCHROMIUM)             /* 512 */ \
  OP(SwapInterval)                             /* 513 */ \
  OP(MatrixLoadfCHROMIUMImmediate)             /* 514 */ \
  OP(MatrixLoadIdentityCHROMIUM)               /* 515 */ \
  OP(BlendBarrierKHR)                          /* 516 */

enum CommandId {
  kStartPoint = cmd::kLastCommonId,  // All GLES2 commands start after this.
#define GLES2_CMD_OP(name) k##name,
  GLES2_COMMAND_LIST(GLES2_CMD_OP)
#undef GLES2_CMD_OP
      kNumCommands
};

#endif  // GPU_COMMAND_BUFFER_COMMON_GLES2_CMD_IDS_AUTOGEN_H_
