// Copyright 2013 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Tests an invalid IDL file.

namespace test {
  // Trailing comma in block.
  enum TrailingComma {
    name1,
    name2,
  };
};
