SRC=\
src/implicit.c \
src/mcf.c \
src/mcfutil.c \
src/output.c \
src/pbeampp.c \
src/pbla.c \
src/pflowup.c \
src/psimplex.c \
src/pstart.c \
src/readmin.c \
src/treeup.c

IT=mcf

CFLAGS = -DWANT_STDC_PROTO
include ../Makefile.common

