SRC=\
src/bits.c \
src/deflate.c \
src/gzip.c \
src/getopt.c \
src/inflate.c \
src/lzw.c \
src/spec.c \
src/trees.c \
src/unlzh.c \
src/unlzw.c \
src/unpack.c \
src/unzip.c \
src/util.c \
src/zip.c

IT=gzip

CFLAGS_EXTRA = -DSPEC_CPU2000
include ../Makefile.common

