#!/bin/sh

# Quicky script to copy from a chrome tree to here.

if [ $# -ne 1 ] ; then
  echo usage: ${0} /path/to/chrome/src >& 2
  exit 1
fi

HERE="$(dirname ${0})"
. "${HERE}/samples.sh"

for GYP in ${GYPS} ; do
  cp "${1}/${GYP}" "${HERE}"
done
