application: chrome-apps-doc
version: 2-16-0
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /robots\.txt
  static_files: robots.txt
  upload: robots.txt
- url: /favicon\.ico
  static_files: chrome-32.ico
  upload: chrome-32.ico
- url: /.*
  script: appengine_main.py
