// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Setup related functions for a Google Cloud Devices (GCD) target device
// running on Chrome OS Core. The actual bootstrapping and GCD registration is
// handled by the privetd and buffet system daemons.
namespace shell.gcd {
 
  callback PingCallback = void(boolean success);

  interface Functions {
    // Attempts to ping the daemon via D-Bus.
    static void ping(PingCallback callback);
  };
};
