// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Use the <code>chrome.shell.identity</code> API to retrieve OAuth2 tokens
// for user accounts.  See also <code>chrome.identity</code>.
namespace shell.identity {

  interface Functions {
    // TODO(jamescook): Implement this with options and a callback.
    static void getAuthToken();
  };

};
