/* Copyright (c) 2012 The Chromium Authors. All rights reserved.
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

/**
 * This file defines the <code>PPP_ContentDecryptor_Private</code>
 * interface. Note: This is a special interface, only to be used for Content
 * Decryption Modules, not normal plugins.
 */
label Chrome {
  M24 = 0.3
};

/**
 * <code>PPP_ContentDecryptor_Private</code> structure contains the function
 * pointers the decryption plugin must implement to provide services needed by
 * the browser. This interface provides the plugin side support for the Content
 * Decryption Module (CDM) for v0.1 of the proposed Encrypted Media Extensions:
 * http://goo.gl/rbdnR
 */
interface PPP_ContentDecryptor_Private {
  /**
   * Generates a key request. key_system specifies the key or licensing system
   * to use. init_data is a data buffer containing data for use in generating
   * the request.
   *
   * Note: <code>GenerateKeyRequest()</code> must create the session ID used in
   * other methods on this interface. The session ID must be provided to the
   * browser by the CDM via <code>KeyMessage()</code> on the
   * <code>PPB_ContentDecryptor_Private</code> interface.
   *
   * @param[in] key_system A <code>PP_Var</code> of type
   * <code>PP_VARTYPE_STRING</code> containing the name of the key system.
   *
   * @param[in] init_data A <code>PP_Var</code> of type
   * <code>PP_VARTYPE_ARRAYBUFFER</code> containing container specific
   * initialization data.
   */
  void GenerateKeyRequest(
      [in] PP_Instance instance,
      [in] PP_Var key_system,
      [in] PP_Var init_data);

  /**
   * Provides a key or license to the decryptor for decrypting media data.
   *
   * When the CDM needs more information to complete addition of the key it
   * will call <code>KeyMessage()</code> on the
   * <code>PPB_ContentDecryptor_Private</code> interface, which the browser
   * passes to the application. When the key is ready to use, the CDM
   * must call call <code>KeyAdded()</code> on the
   * <code>PPB_ContentDecryptor_Private</code> interface, and the browser
   * must notify the web application.
   *
   * @param[in] session_id A <code>PP_Var</code> of type
   * <code>PP_VARTYPE_STRING</code> containing the session ID.
   *
   * @param[in] key A <code>PP_Var</code> of type
   * <code>PP_VARTYPE_ARRAYBUFFER</code> containing the decryption key, license,
   * or other message for the given session ID.
   *
   * @param[in] init_data A <code>PP_Var</code> of type
   * <code>PP_VARTYPE_ARRAYBUFFER</code> containing container specific
   * initialization data.
   */
  void AddKey(
      [in] PP_Instance instance,
      [in] PP_Var session_id,
      [in] PP_Var key,
      [in] PP_Var init_data);

  /**
   * Cancels a pending key request for the specified session ID.
   *
   * @param[in] session_id A <code>PP_Var</code> of type
   * <code>PP_VARTYPE_STRING</code> containing the session ID.
   */
  void CancelKeyRequest(
      [in] PP_Instance instance,
      [in] PP_Var session_id);

  /**
   * Decrypts the block and returns the unencrypted block via
   * <code>DeliverBlock()</code> on the
   * <code>PPB_ContentDecryptor_Private</code> interface. The returned block
   * contains encoded data.
   *
   * @param[in] resource A <code>PP_Resource</code> corresponding to a
   * <code>PPB_Buffer_Dev</code> resource that contains an encrypted data
   * block.
   *
   * @param[in] encrypted_block_info A <code>PP_EncryptedBlockInfo</code> that
   * contains all auxiliary information needed for decryption of the
   * <code>encrypted_block</code>.
   */
  void Decrypt(
      [in] PP_Instance instance,
      [in] PP_Resource encrypted_block,
      [in] PP_EncryptedBlockInfo encrypted_block_info);

 /**
  * Initializes the video decoder using codec and settings in
  * <code>decoder_config</code>, and returns the result of the initialization
  * request to the browser using the <code>DecoderInitialized()</code> method
  * on the <code>PPB_ContentDecryptor_Private</code> interface.
  *
  * @param[in] decoder_config A <code>PP_VideoDecoderConfig</code> that
  * contains video decoder settings and a request ID. The request ID is passed
  * to the <code>DecoderInitialized()</code> method on the
  * <code>PPB_ContentDecryptor_Private</code> interface to allow clients to
  * associate the result with a video decoder initialization request.
  *
  * @param[in] codec_extra_data A <code>PP_Resource</code> corresponding to a
  * <code>PPB_Buffer_Dev</code> resource containing codec setup data required
  * by some codecs. It should be set to 0 when the codec being initialized
  * does not require it.
  */
  void InitializeVideoDecoder(
      [in] PP_Instance instance,
      [in] PP_VideoDecoderConfig decoder_config,
      [in] PP_Resource codec_extra_data);

  /**
   * Decrypts encrypted_video_frame, decodes it, and returns the unencrypted
   * uncompressed (decoded) video frame to the browser via the
   * <code>DeliverFrame()</code> method on the
   * <code>PPB_ContentDecryptor_Private</code> interface.
   *
   * @param[in] encrypted_video_frame A <code>PP_Resource</code> corresponding
   * to a <code>PPB_Buffer_Dev</code> resource that contains an encrypted video
   * frame.
   *
   * @param[in] encrypted_video_frame_info A
   * <code>PP_EncryptedVideoFrameInfo</code> that contains all information
   * needed to decrypt and decode <code>encrypted_video_frame</code>.
   */
  void DecryptAndDecodeFrame(
      [in] PP_Instance instance,
      [in] PP_Resource encrypted_video_frame,
      [in] PP_EncryptedVideoFrameInfo encrypted_video_frame_info);
};
