#!/bin/sh

# Copyright (c) 2009 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# This script is intended to run from a "postbuild" action from within Xcode.
# It will create any symlinks needed to sync up what comes from the GRIT files
# with what Cocoa would like.

set -e

# Working in the resources directory
cd "${BUILT_PRODUCTS_DIR}/${CONTENTS_FOLDER_PATH}/Resources"

# Provide an link for en.lproj that points to en_US.lproj.

# The standard OS language list includes English (en) and not a specific
# "flavor" such as U.S. English (en_US). When checking for a language match,
# the OS will remove subtags if no exact match is found, so that en will be
# used if the user's preferred language list only contains British English
# (en_GB) and no specific en_GB translation is available.
#
# To ensure that users with the default language list, which contains English
# without any regional subtag, as well as users with a specific variant of
# English with a regional subtag, will have access to an English-localized
# application, a symbolic link from en.lproj to en_US.lproj is provided.
ln -fhs "en_US.lproj" "en.lproj"
