/* Copyright (c) 2012 The Chromium Authors. All rights reserved.
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

/*
 * This file defines the trusted file IO interface
 */

label Chrome {
  M14= 0.4
};

// Available only to trusted implementations.
interface PPB_FileIOTrusted {
  /**
   * Returns a file descriptor corresponding to the given FileIO object. On
   * Windows, returns a HANDLE; on all other platforms, returns a POSIX file
   * descriptor. The FileIO object must have been opened with a successful
   * call to FileIO::Open.  The file descriptor will be closed automatically
   * when the FileIO object is closed or destroyed.
   *
   * TODO(hamaji): Remove this and use RequestOSFileHandle instead.
   */
  int32_t GetOSFileDescriptor([in] PP_Resource file_io);
};
