include ../config.mk

cursor_images =					\
	bottom_left_corner.png			\
	bottom_right_corner.png			\
	bottom_side.png				\
	grabbing.png				\
	left_ptr.png				\
	left_side.png				\
	right_side.png				\
	top_left_corner.png			\
	top_right_corner.png			\
	top_side.png				\
	xterm.png


all :

install :
	install -d $(datadir)/wayland
	install $(cursor_images) $(datadir)/wayland
