 /*
  * Copyright 2010 The Native Client Authors. All rights reserved.
  * Use of this source code is governed by a BSD-style license that can
  * be found in the LICENSE file.
  */

/*
 * NOTE: This file is empty now bu expected to be populated with code soon
 * with the implementation of miscellaneous intrinsics.
 */

#include "native_client/src/trusted/service_runtime/nacl_config.h"

    .text
    .section .text

