// Copyright 2013 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// The <code>chrome.webrtc.castUdpTransport</code> API represents a UDP
// transport for Cast RTP streams. This API is not useful when standalone
// since it does not have send and receive methods.
// It is used to configure the UDP transport used in Cast session.
namespace cast.streaming.udpTransport {
  // The UDP socket address and port.
  dictionary UdpParams {
    DOMString address;
    long port;
  };

  interface Functions {
    // Destroys a UDP transport.
    // |transportId| : The transport ID.
    [nocompile] static void destroy(long transportId);

    // Starts to use the transport by providing remote UDP info.
    // |transportId| : The transport ID.
    // |remoteParams| : The address and port to send packets to.
    [nocompile] static void start(long transportId, UdpParams remoteParams);
  };
};
