// Copyright (c) 2012 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// File-level comment to appease parser. Eventually this will not be necessary.
namespace experimental.systemInfo.cpu {

  dictionary CpuCoreInfo {
    // Indicates the load of CPU core, as a number between 0 and 100.
    long load;
  };
  
  dictionary CpuInfo {
    // The array of the CPU processors in the system.
    CpuCoreInfo[] cores;
  };

  callback CpuInfoCallback = void (CpuInfo prop);
  callback CpuUpdateCallback = void (ChangeInfo info);
  
  interface Functions {
    // Get CPU property.
    static void get(CpuInfoCallback callback);
  };
};
