// Copyright (c) 2012 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

[nodoc] namespace experimental.notification {
  dictionary ShowOptions {
    DOMString iconUrl;
    DOMString title;
    DOMString message;
    DOMString? extraField;
    DOMString? secondExtraField;
    DOMString replaceId;

    // Used for internal event routing. Do not set or rely on its value.
    [nodoc] long? srcId;
  };

  dictionary ShowInfo {
    boolean result;
  };

  callback ShowCallback = void (ShowInfo showInfo);

  interface Functions {
    static void show(ShowOptions options, ShowCallback callback);
  };

};
