// Copyright (c) 2013 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

[nodoc] namespace experimental.notification {
  enum TemplateType {
    // icon, title, message
    simple,

    // icon, title, message, expandedMessage, up to two buttons
    basic,

    // icon, title, message, expandedMessage, image, up to two buttons
    image,

    // icon, title, message, items, up to two buttons
    list
  };

  dictionary NotificationItem {
    // Title of one item of a list notification.
    DOMString title;

    // Additional details about this item.
    DOMString message;
  };

  dictionary NotificationButton {
    DOMString title;
    DOMString? iconUrl;
  };

  dictionary NotificationOptions {
    // Which type of notification to display.
    TemplateType templateType;

    // Sender's avatar, app icon, or a thumbnail for image notifications.
    // TODO(miket): see browserAction.setIcon() for a better approach.
    DOMString iconUrl;

    // Title of the notification (e.g. sender name for email).
    DOMString title;

    // Main notification content.
    DOMString message;

    // Priority ranges from -2 to 2. -2 is lowest priority. 2 is highest. Zero
    // is default.
    long? priority;

    // A timestamp associated with the notification, in milliseconds past the
    // epoch (e.g. <code>Date.now() + n</code>).
    double? eventTime;

    // Smaller version of the icon.
    DOMString? secondIconUrl;

    // Text and icons of notification action buttons.
    NotificationButton[]? buttons;

    // Secondary notification content.
    DOMString? expandedMessage;

    // Image thumbnail for image-type notifications.
    DOMString? imageUrl;

    // Items for multi-item notifications.
    NotificationItem[]? items;
  };

  callback CreateCallback = void (DOMString notificationId);

  callback UpdateCallback = void (boolean wasUpdated);

  callback DeleteCallback = void (boolean wasDeleted);

  interface Functions {
    // Creates and displays a notification having the contents in |options|,
    // identified by the id |notificationId|. If |notificationId| is empty,
    // |create| generates an id. If |notificationId| matches an existing
    // notification, |create| first deletes that notification before proceeding
    // with the create operation. |callback| returns the notification id
    // (either supplied or generated) that represents the created notification.
    static void create(DOMString notificationId,
                       NotificationOptions options,
                       CreateCallback callback);

    // Updates an existing notification having the id |notificationId| and the
    // options |options|. |callback| indicates whether a matching notification
    // existed.
    static void update(DOMString notificationId,
                       NotificationOptions options,
                       UpdateCallback callback);

    // Given a |notificationId| returned by the |create| method, deletes the
    // corresponding notification. |callback| indicates whether a matching
    // notification existed.
    static void delete(DOMString notificationId, DeleteCallback callback);
  };

  interface Events {
    // The system displayed the notification. Not all created notifications are
    // displayed; for example, a low-priority notification might simply appear
    // in the message center without interrupting the user.
    static void onDisplayed(DOMString notificationId);

    // The notification closed, either by the system or by user action.
    static void onClosed(DOMString notificationId, boolean byUser);

    // The user clicked in a non-button area of the notification.
    static void onClicked(DOMString notificationId);

    // The user pressed a button in the notification.
    static void onButtonClicked(DOMString notificationId, long buttonIndex);
  };

};
