// Copyright (c) 2012 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// File-level comment to appease parser. Eventually this will not be necessary.
namespace experimental.systemInfo.cpu {

  dictionary CpuInfo {
    // The number of logical processors.
    long numOfProcessors;
    // The architecture name of the processors.
    DOMString archName;
    // The model name of the processors.
    DOMString modelName;
  };

  dictionary CpuUpdateInfo {
    // The average usage percent of all processors, as a number 
    // between 0 and 100.
    double averageUsage;
    // The CPU usage array for each logic processor.
    double[] usagePerProcessor;
  };

  callback CpuInfoCallback = void (CpuInfo info);
  
  interface Functions {
    // Get CPU information.
    static void get(CpuInfoCallback callback);
  };
};
