// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// The <code>chrome.launcherPage</code> API provides launcher pages in the App
// Launcher with the capabilities and events they need.
namespace launcherPage {
  interface Events {
    static void onTransitionChanged(double progress);
  };
};
