// Copyright 2015 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Use the <code>chrome.settingsPrivate</code> API to get or set preferences
// from the settings UI.
namespace settingsPrivate {
  // Type of a pref.
  enum PrefType { BOOLEAN, NUMBER, STRING, URL, LIST };

  // Policy source of a pref.
  enum PolicySource { DEVICE, USER };

  // Policy enforcement of a pref.
  enum PolicyEnforcement { ENFORCED, RECOMMENDED };

  dictionary PrefObject {
    // The key for the pref.
    DOMString key;

    // The type of the pref (e.g., boolean, string, etc.).
    PrefType type;

    // The current value of the pref.
    any value;

    // The policy source of the pref; an undefined value means there is no
    // policy.
    PolicySource? policySource;

    // The policy enforcement of the pref; must be specified if policySource is
    // also present.
    PolicyEnforcement? policyEnforcement;
  };

  callback OnPrefSetCallback = void (boolean success);
  callback GetAllPrefsCallback = void (PrefObject[] prefs);
  callback GetPrefCallback = void (PrefObject pref);

  interface Functions {
    // Sets a settings value.
    // |name|: The name of the pref.
    // |value|: The new value of the pref.
    // |pageId|: The user metrics identifier or null.
    // |callback|: The callback for whether the pref was set or not.
    static void setPref(DOMString name, any value,
        DOMString pageId, OnPrefSetCallback callback);

    // Gets an array of all the prefs.
    static void getAllPrefs(GetAllPrefsCallback callback);

    // Gets the value of a specific pref.
    static void getPref(DOMString name, GetPrefCallback callback);
  };

  interface Events {
    // Fired when a set of prefs has changed.
    //
    // |prefs| The prefs that changed.
    static void onPrefsChanged(PrefObject[] prefs);
  };
};
