# Copyright 2010 The Native Client Authors.  All rights reserved.
# Use of this source code is governed by a BSD-style license that can
# be found in the LICENSE file.

srcdir = @srcdir@
prefix = @prefix@

install_root = $(prefix)

all:

install:
	install -d $(install_root)/bin
	install $(srcdir)/hellow $(install_root)/bin
