// Copyright (c) 2012 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import "oaidl.idl";
import "ocidl.idl";

[
  object,
  uuid(GENERATED_UUID),
  oleautomation,
  nonextensible,
  pointer_default(unique)
]
interface IDummy : IUnknown {
  HRESULT Dummy();
};
