#!/usr/bin/env python
# Copyright (c) 2012 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
import os
import sys


sys.path.append(os.path.join(os.path.dirname(__file__), ".."))

import chrome_remote_control

def Main(args):
  options = chrome_remote_control.BrowserOptions()
  parser = options.CreateParser(
      "list_available_browsers <sitelist>")
  options, args = parser.parse_args()
  browser_to_create = chrome_remote_control.FindAllPossibleBrowsers(options)
  if not len(browser_to_create):
    sys.stderr.write("No browsers found.\n")
    return 1
  print ",".join([b.type for b in browser_to_create])
  return 0

if __name__ == "__main__":
  sys.exit(Main(sys.argv[1:]))
