#!/usr/bin/env node

// Generate a top-level cts.html file for WPT.
//
// In the default invocation (used by grunt), just generates a cts.html with one "variant" per test
// spec file (.spec.ts).
//
// In the advanced invocation, generate a list of variants, which are broken down as much as needed
// to accommodate a provided list of suppressions, and no further. This reduces the total runtime of
// the test suite by not generating an entire page load for every single test case.
// The resulting cts.html can be checked in and used to run tests within browser harnesses.
//
// For example, for the following 9 cases:
//
//   cts:a/foo:foo1={"x":1}
//   cts:a/foo:foo1={"x":2}
//   cts:a/foo:foo2={"x":1}
//   cts:a/foo:foo2={"x":2}
//   cts:a/bar:bar1={"x":1}
//   cts:a/bar:bar1={"x":2}
//   cts:a/bar:bar1={"x":3}
//   cts:a/bar:bar2={"x":1}
//   cts:a/bar:bar2={"x":2}
//
// and the following suppressions:
//
//   [ Win ] ?q=cts:a/bar:bar1={"x":1} [ Failure ]
//   [ Mac ] ?q=cts:a/bar:bar1={"x":3} [ Failure ]
//
// the following list of 5 variants gives enough granularity to suppress only the failing cases:
//
//   ?q=cts:a/foo:
//   ?q=cts:a/bar:bar1={"x":1} <- [ Win ]
//   ?q=cts:a/bar:bar1={"x":2}
//   ?q=cts:a/bar:bar1={"x":3} <- [ Mac ]
//   ?q=cts:a/bar:bar2~

require('../src/tools/setup-ts-in-node.js');
require('../src/tools/gen_wpt_cts_html.ts');
