# $Id: Makefile.inc 1854 2007-05-31 06:16:49Z peter $

TESTS += modules/objfmts/macho/tests/nasm32/macho32_test.sh

EXTRA_DIST += modules/objfmts/macho/tests/nasm32/macho32_test.sh
EXTRA_DIST += modules/objfmts/macho/tests/nasm32/machotest.c
EXTRA_DIST += modules/objfmts/macho/tests/nasm32/machotest.asm
EXTRA_DIST += modules/objfmts/macho/tests/nasm32/machotest.hex
EXTRA_DIST += modules/objfmts/macho/tests/nasm32/macho-reloc.asm
EXTRA_DIST += modules/objfmts/macho/tests/nasm32/macho-reloc.hex
EXTRA_DIST += modules/objfmts/macho/tests/nasm32/macho32-sect.asm
EXTRA_DIST += modules/objfmts/macho/tests/nasm32/macho32-sect.errwarn
EXTRA_DIST += modules/objfmts/macho/tests/nasm32/macho32-sect.hex
