// Copyright 2019 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import "oaidl.idl";
import "ocidl.idl";

[
  object,
  dual,
  uuid(63B8FFB1-5314-48C9-9C57-93EC8BC6184B),
  helpstring("IUpdater Interface"),
  pointer_default(unique)
]
interface IUpdater : IUnknown {
  HRESULT CheckForUpdate([in, string] const WCHAR* guid);
  HRESULT Update([in, string] const WCHAR* guid);
};

[
  uuid(69464FF0-D9EC-4037-A35F-8AE4358106CC),
  version(1.0),
  helpstring("Omaha 4.0 Type Library")
]
library UpdaterLib {
  importlib("stdole2.tlb");

  interface IUpdater;

  [
    uuid(158428A4-6014-4978-83BA-9FAD0DABE791),
    helpstring("Updater Class")
  ]
  coclass UpdaterClass
  {
    [default] interface IUnknown;
  }
};
