/* Copyright (c) 2013 The Chromium Authors. All rights reserved.
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

/**
 * This file defines the <code>PPB_NetworkProxy_Dev</code> interface.
 */

[generate_thunk]

label Chrome {
  M29 = 0.1
};

[singleton]
interface PPB_NetworkProxy_Dev {
  /**
   * Retrieves the proxy that will be used for the given URL. The result will
   * be a string in PAC format. For more details about PAC format, please see
   * http://en.wikipedia.org/wiki/Proxy_auto-config
   */
  int32_t GetProxyForURL([in] PP_Instance instance,
                         [in] PP_Var url,
                         [out] PP_Var proxy_string,
                         [in] PP_CompletionCallback callback);
};
