/* Copyright 2013 The Chromium Authors. All rights reserved.
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

/**
 * This file defines the <code>PPB_VarResource</code> struct providing
 * a way to interact with resource vars.
 */

label Chrome {
  M32 = 0.1
};

[macro="PPB_VAR_RESOURCE_DEV_INTERFACE"]
interface PPB_VarResource_Dev {
  /**
   * Converts a resource-type var to a <code>PP_Resource</code>.
   *
   * @param[in] var A <code>PP_Var</code> struct containing a resource-type var.
   *
   * @return A <code>PP_Resource</code> retrieved from the var, or 0 if the var
   * is not a resource. The reference count of the resource is incremented on
   * behalf of the caller.
   */
  PP_Resource VarToResource([in] PP_Var var);

  /**
   * Creates a new <code>PP_Var</code> from a given resource.
   *
   * @param[in] resource A <code>PP_Resource</code> to be wrapped in a var.
   *
   * @return A <code>PP_Var</code> created for this resource, with type
   * <code>PP_VARTYPE_RESOURCE</code>. The reference count of the var is set to
   * 1 on behalf of the caller.
   */
  PP_Var VarFromResource([in] PP_Resource resource);
};
