/* Copyright (c) 2011 The Chromium Authors. All rights reserved.
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

/**
 * This file defines the <code>PPB_QueryPolicy_Dev</code> interface.
 */
label Chrome {
  M14 = 0.1
};

interface PPB_QueryPolicy_Dev {
  /**
   * Subscribes the instance to receive updates via the
   * <code>PPP_PolicyUpdate_Dev</code> interface.
   *
   * The plugin is guaranteed to get one update immediately via the
   * <code>PP_PolicyUpdate_Dev</code> interface. This allows the plugin to
   * retrieve the current policy when subscribing for the first time.
   *
   * @param[in] instance A <code>PP_Instance</code> indentifying one instance
   * of a module.
   */
  void SubscribeToPolicyUpdates([in] PP_Instance instance);
};
