/* Copyright (c) 2011 The Chromium Authors. All rights reserved.
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */


/**
 * This file defines the <code>PPB_Fullscreen_Dev</code> interface.
 */

label Chrome {
  M16 = 0.5
};

interface PPB_Fullscreen_Dev {
  /**
   * Checks whether the plugin instance is currently in fullscreen mode.
   */
  PP_Bool IsFullscreen(
      [in] PP_Instance instance);

  /**
   * Switches the plugin instance to/from fullscreen mode. Returns PP_TRUE on
   * success, PP_FALSE on failure.
   *
   * This unbinds the current 2D or 3D devices. Pending flushes and swapbuffers
   * will execute as if the resource was off-screen. The transition to and from
   * fullscreen is asynchronous. During the transition, IsFullscreen will
   * return the original value, and no 2D or 3D device can be bound.
   * The transition ends at the next DidChangeView.
   *
   * The transition to fullscreen can only occur while the browser is
   * processing a user gesture, even if PP_TRUE is returned. Note that two
   * DidChangeView calls will happen when switching to fullscreen:
   * one for moving the plugin to the middle of the window and one for
   * stretching the window placing the plugin in the middle of the screen.
   * Plugin size will not be affected.
   */
  PP_Bool SetFullscreen(
      [in] PP_Instance instance,
      [in] PP_Bool fullscreen);

  /**
   * Gets the size of the screen in pixels. When going fullscreen, the instance
   * will be resized to that size.
   */
  PP_Bool GetScreenSize(
      [in] PP_Instance instance,
      [out] PP_Size size);
};

