/* Copyright (c) 2011 The Chromium Authors. All rights reserved.
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

/**
 * This file defines the <code>PPP_PolicyUpdate_Dev</code> interface.
 */

label Chrome {
  M14 = 0.1
};

interface PPP_PolicyUpdate_Dev {
  /**
   * Signals that the policy has been updated, and provides it via a JSON
   * string.
   *
   * @param[in] instance A <code>PP_Instance</code> indentifying one instance
   * of a module.
   * @param[in] A <code>PP_Var</code> with a JSON string representing the
   * encoded policy.
   */
  void PolicyUpdated(
      [in] PP_Instance instance,
      [in] PP_Var policy_json);
};
