application: salsa
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest

handlers:
- url: /css
  static_dir: css

- url: /create
  script: create.app
  login: required

- url: /.*
  script: salsa.app
  login: required
